### ISSUE TITLE
Time formatting option in settings

### ISSUE THREAD

**Issue by Albinzr** [amir20/dozzle#1035]
**Is your feature request related to a problem? Please describe.**
Currently when we see logs its only show hour and min, it would be great to view sec also

**Describe the solution you'd like**
In settings, we can have a drop-down to show possible time formats(H/m/s) or a simple text field where the user can enter time format sting
**Describe alternatives you've considered**
A simple text field where the user can enter time format sting

**Comment by amir20** [comment]
Not against this but general principle has been to limit to only feasible options. I wouldn't add free text field because then I have to handle validation. 

Maybe just a toggle to show `ss`. 

Lots going on at work but if someone wants to send a PR I can review it. 

Thanks for the idea. I can see it being useful when looking at performance logs.
