### ISSUE TITLE
Group containers by stack

### ISSUE THREAD

**Issue by XPlantefeve** [amir20/dozzle#1196]
I find Dozzle amazing as is and I understand its intended scope is not big environments. Even in my smallish environment of three stacks totalling less than 20 containers, though, it would be nice to have the left menu grouped by stack (and nicer even to have some sort of an accordion menu).

Just an idea, as I do not speak Go at all. Feel free to close if you have better uses of your resources.

**Comment by amir20** [comment]
This is a fair ask @XPlantefeve. I use services myself. However, Dozzle doesn't know anything about services right now. Dozzle only knows only about containers. 

For this to really work, I'd like to support stacks, services and swarm natively. I just haven't had time to do it. I am also curious where docker swarm will go. There hasn't been much support from Docker since k8s got integrated. There has been too many bugs with `docker service log` command so I am even hesitant to support a buggy feature. 

By the way, I have used Dozzle up to 300 containers. That's why I added the search functionality. Theoretically, there shouldn't be any issues using it for big environment. It is highly optimized and uses very little memory. 

Closing for now until Docker Swam direction is figure out.
