### ISSUE TITLE
On Container Restart

### ISSUE THREAD

**Issue by Shadow58624** [amir20/dozzle#1246]
**Is your feature request related to a problem? Please describe.**
When a container is restarted, if the log is open it gets a red message and it stops updating permanently, even after the container is running again. Currently the only solution is to open another log and come back or to update the page.

**Describe the solution you'd like**
The log resumes once the container is restarted

**Comment by Shadow58624** [comment]
I realized this is a duplicate of #976

**Comment by amir20** [comment]
I think this might actually a bug. The other bug #976 is a little different (or at least how understood it). That bug was about going to the new container even if it is a new id. 

Docker creates a new id if the docker container is destroyed. However, in your case, the id never changes. 

So I think it is a bug because Dozzle should know a container stopped. I need to think about how to do this right because Dozzle doesn't know when something has restarted.

**Comment by amir20** [comment]
I may have a fix soon.

**Comment by amir20** [comment]
<img width="1252" alt="Screen Shot 2021-05-26 at 12 26 12 PM" src="https://user-images.githubusercontent.com/260667/119719392-9484eb00-be1d-11eb-8be5-bf0e7f45e3b7.png">

This should be fixed in `latest-dev`. I will release a build soon.

**Comment by amir20** [comment]
Should be fixed in 3.7.0
