### ISSUE TITLE
Safari Desktop Browser (12.0.1) is not working

### ISSUE THREAD

**Issue by rostchri** [amir20/dozzle#1358]
**Describe the bug**
Safari Desktop Browser (12.0.1) is not working because of an javascript error

**To Reproduce**
1. Open nozzle link in Safari Desktop Browser 12.0.1
2. redirection to <nozzle-url>/login is working
3. Safari Desktop Browser 12.0.1 only returns a black page and a javascript error: 
    SyntaxError: Unexpected token '?' in main.js:2

**Expected behavior**
Dozzle login screen should appear.
Chrome browser and mobile Safari (iOS) is working as expected.

**Desktop (please complete the following information):**
 - OS: OSX 10.14.1
 - Docker version
 - Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.3.3-0ubuntu2.3
  GitCommit:        
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:      
 - Browser: Safari Desktop Browser (12.0.1)
 - Dozzle-Version: amir20/dozzle:v3.7.1

"DOZZLE_LEVEL: debug" does not help and the main.js file only contains one long line,
which makes it difficult to find the exact position of the error. Maybe it would help to deliver 
a full main.js file in debug mode, to make it easier to track down these kind of javascript bugs ...

**Comment by amir20** [comment]
I think I know what the problem is. I use the [??](https://github.com/amir20/dozzle/blob/master/assets/components/LogEventSource.vue#L64) operator and according to [caniuse](https://caniuse.com/mdn-javascript_operators_nullish_coalescing), it was added in version 13.1. 

I am only trying to support the latest version of browsers and the latest for Safari is 14. 

>> Maybe it would help to deliver a full main.js file in debug mode,

Dozzle is small container. If I start doing adding debugging information, it would be more than 5 MB. 

What are you thoughts on the `??` operator? Version <14 is less than 0.5%. So I am hesitant to support it.

**Comment by rostchri** [comment]
Ok no problem. I will update my system :)

**Comment by amir20** [comment]
I was going to say update if you can. It’s easy enough to fix one operator. But there might be other things that dozzle wouldn’t support.
