### ISSUE TITLE
Window Jumpy When Small

### ISSUE THREAD

**Issue by Townsy45** [amir20/dozzle#1400]
**Describe the bug**
When I have the window in small window the consoles jitter, it seems to be the scrollbar being shown/hidden over and over, it's very distracting but not sure if this is a thing anyone else expirences, if I make the window bigger it stops but thought might as well report it anyways just in case.

Seems to be related to the content in the logs, bigger logs happen in a bigger window, with the dozzle logs the window has to be smaller as you will see in the gif.

**To Reproduce**
1. Launch Dozzle
2. Open two consoles
3. Make your window small
4. See jitters

**Expected behavior**
Well I would hope that no matter the size the consoles would not jitter from the scrollbar because it's distracting when reading logs.

**Screenshots**
https://recordit.co/lHs94eC91n

**Desktop (please complete the following information):**
 - OS: Win 10
 - Docker version 20.10.7
 - Browser: Chrome
 - Version v3.7.0

**Comment by amir20** [comment]
Hmm that does look pretty crappy.  Thanks for pointing it out. I have a Mac and it doesn't do the jitter.

Would you be able to debug a little to see what is happening? Otherwise, I don't have a way to reproduce. 

I think what is happening is that the console is scrolling to the bottom, Windows shows the scrollbar, making the width smaller and the jitter happens. 

I have no idea how to fix that.

**Comment by amir20** [comment]
Any update on this?
