### ISSUE TITLE
Keyword highlighting in logs

### ISSUE THREAD

**Issue by agneevX** [amir20/dozzle#1598]
Firstly, I'd like to say that I'm a big fan of dozzle, the ability to look up logs from any device, for any machine has made resolving issues so much faster and easier, so thank you!

**Is your feature request related to a problem? Please describe.**

Yes. While monitoring logs during troubleshooting, it can be quite useful to know at a glance, when there are errors or warnings in logs, especially when logs are written rapidly.

**Describe the solution you'd like**

Colors in individual log lines highlighting keywords. 

E.g. blue for `INFO`, yellow for `WARN/warning`, red for `ERROR` and so on.

**Describe alternatives you've considered**

**Additional context**

**Comment by Coteh** [comment]
I know at least in my case, logs are already colored (and I believe this is because the logger I'm using, winston for nodejs, colors them in):

![image](https://user-images.githubusercontent.com/3276350/141694092-cffbd37d-6b18-4178-bc9e-b02dffceadea.png)

I'm assuming your logger does not color your logs in the same way for your app? Some of the backend services at my job don't color logs in either, and it would be nice if dozzle could color them somehow, in this case.

Maybe we can override the text color of the line, or its background color, or both?

I imagine the solution could be as simple as checking each line against regexes for info, warning, error, debug, etc. keywords, but perhaps performance of a solution like that would need to be considered as well and optimized appropriately. Your thoughts @amir20 ?

**Comment by amir20** [comment]
I use `ansi-to-html` which converts terminal ansi colors to html. It works pretty well as you can see the image above. 

However, most logging frameworks have an auto detect feature which disable coloring when terminal is not interactive. For example, see Golan's [logrus](https://pkg.go.dev/github.com/sirupsen/logrus#TextFormatter) `ForceColors`. 

Aside from that, it is possible what @Coteh suggested. Search for things like info, error, etc... and convert them to colors. 

This feature was asked before and I stopped it for two reason: 

1. I didn't want logs to be full of colors. This could actually become really ugly and deter people from reading it. It would have to be something subtle like maybe just the word error or info change colors. Or even just a red dot next to logs with errors. 
2. Customization was out of my scope. Some people had asked for a full admin tool to allow regex and color settings. That's too hard at the moment because everything is processed on the browser. 

I am open to ideas if anybody wants to provide something easy and simple.

**Comment by Coteh** [comment]
I think a simple toggle to switch between ANSI colors and keyword coloring would be good.

(The keyword color setting could also preserve ANSI coloring in case something else in the logs is colored. Just the keywords themselves would have their colors switched)

**Comment by agneevX** [comment]
> It would have to be something subtle like maybe just the word error or info change colors.

Yep, similar to the screenshot above will do.

**Comment by amir20** [comment]
@agneevX can you send a PR for this?

**Comment by agneevX** [comment]
Nope, sorry.

**Comment by amir20** [comment]
Then I won't do it since it's not that important to me.

**Comment by agneevX** [comment]
@amir20 I came across the search feature and it looks to be quite useful in narrowing down logs. Does it auto update when new matching logs come in?

**Comment by amir20** [comment]
@agneevX yes the logs should update when searching. At least, that's the intention. If it doesn't, it's a bug.
