### ISSUE TITLE
Nice to have - Search history on filter logs

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1611]
**Is your feature request related to a problem? Please describe.**
It would be nice if user could press up arrow on keyboard to bring up past searches, much like what tools like VS Code do when searching for previous searches.

**Describe the solution you'd like**
Store past N searches in local storage or in-memory, where N is a reasonable amount of searches to keep in the history, and up press on keyboard when search box is focused will replace current search text with Mth last result on the list, where M is the number of times user pressed the key. Pressing down arrow can also navigate down to the next recent search, so in the other direction.

**Describe alternatives you've considered**
This is a nice to have feature for me.

**Additional context**
I would like to try implementing this if you're interested in this feature.

**Comment by amir20** [comment]
Which search? Logs or the containers?

**Comment by Coteh** [comment]
I meant logs but I suppose we could reuse it in container search as well.

**Comment by amir20** [comment]
I like the idea for logs first. Let me know if you need help. You can probably reuse the autocomplete component I did in fuzzy search component. 

There is currently a bug in the autocomplete ever since I updated to vue3. The up and down arrows don't work after searching. Honestly, if I had time I would just create my own auto complete component too. Oruga seems buggy.
