### ISSUE TITLE
Log repeats it self when scrolling to get back in time

### ISSUE THREAD

**Issue by sebastianarena** [amir20/dozzle#1615]
**Describe the bug**
Using the default setup, when scrolling back in time to see older logs, they start repeating itself when newer items, when there is in fact more log entries to get

**To Reproduce**
I have asked other friends to try this, and it seems I'm the only one with this problem
I'm running docker on a synology
I use Nginx, but I have reproduced this accesing the container port directly
You just need to scroll back in time to see the problem, and the logs repeating itself again

**Expected behavior**
Would love to be able to scroll in time indefinetely to the begining of the log recording for the containers

**Screenshots**
https://user-images.githubusercontent.com/640406/144052405-e30f8a3b-5a12-4daa-9476-062e299b6890.mov

**Desktop (please complete the following information):**
 - OS: macOS
 - Docker version:
    Synology
    Version:           18.09.8
    API version:       1.39
    Go version:        go1.11
    Git commit:        bfed4f5
    Built:             Thu Mar 18 02:58:09 2021
    OS/Arch:           linux/amd64
 - Browser & version: Brave Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (x86_64)
 - Version: 3.10 (latest)

Love this project, hopefully this makes sense, and is not a duplicated issue. I tried searching for a similar issue, but it seems I'm the only one :(

**Comment by amir20** [comment]
I have been able to go as back as three days. I think something is going on with your environment. 

1. Can you open your web console and check for any errors while scrolling? 
2. Can you check the network tab? There should be an api call similar to `/api/logs?id=f761b1a0ea37&from=2021-11-30T14:20:14.944Z&to=2021-11-30T16:00:11.450Z` Make sure those dates are correct. 
3. Is Dozzle container throwing any errors? I could see possibly a situation where it fails and then restarts which is why you see logs repeated. 

Let's try with those first and see if we can debug what else is going on. For the time being, don't use nginx so it is easier to debug.

**Comment by sebastianarena** [comment]
Hello back, first of all thanks for replying back!
I'm testing directly, without going through nginx during the testing.

1) Opening the web console, and scrolling, shows no errors. Just works fine.

2) Checking the network tag shows something weird... The API is requesting logs UP TO a certain hour/minute, but the reply comes back with many more records, which leads to this problem. The log repeats itself. The FROM seems to be ok, but not the TO. One important key aspect, is that the server is NOT running in UTC timezone, it's in UTC-3

<img width="885" alt="Screen Shot 2021-11-30 at 18 32 38" src="https://user-images.githubusercontent.com/640406/144132038-0e4cd503-52f4-4561-a055-b137d38d57a7.png">

<img width="363" alt="Screen Shot 2021-11-30 at 18 32 46" src="https://user-images.githubusercontent.com/640406/144132050-2248f9b7-9c55-4c34-8ffd-37cb551b2fa2.png">

3) The container has been running non-stop for 9hs, no errors, nothing
<img width="560" alt="Screen Shot 2021-11-30 at 18 37 11" src="https://user-images.githubusercontent.com/640406/144132022-f3f33bee-baae-4cb3-998a-ea0df99be184.png">
.

**Comment by amir20** [comment]
OK thanks. 

So no errors. 

re: timezone -- It should be ok. I use ISO format so it should be just a timestamp. 

So can you confirm if I am understanding something here. The screenshot API is until `2021-11-30 21:14:54` but data returned from API is clearly after that time. 

Is that correct?

**Comment by sebastianarena** [comment]
Exactly! the API is asking the correct info, the missing info, but the response was records beyond the "to" date

**Comment by sebastianarena** [comment]
Love this project, use me to test things if you have a beta or something, I can test any version if you push it to the hub

**Comment by amir20** [comment]
@sebastianarena I did some clean up https://github.com/amir20/dozzle/commit/2246b58aa9b3861ccba148b8756201ead8e71233

Try `master` on docker hub and enable debug mode with `--level debug`. You should see logs like 

```
[00] DEBUG fetch logs from Docker with option: {ShowStdout:true ShowStderr:true Since:2021-12-01T02:41:57Z Until:2021-12-01T02:44:37Z Timestamps:true Follow:false Tail: Details:false}
```

We can make sure there is nothing lost in translation. After that, if you can open command line and try do `docker logs --until .. --since ...` with same settings and see what docker returns. 

This might be a bug with v18 of docker. The version on Synology is old.

**Comment by sebastianarena** [comment]
@amir20 thanks for the update

1) I've installed the `master` version on the server, and used de `level` at `debug` to track

2) I did run the `docker logs --until .. --since ...` and indeed the `since` was not being acknowledged at all

3) I did check with the Synology control panel, and good thing, they have upgraded to v20. I did the upgrade, and re-run the command in 2) with the same results... the `since` gets ignored.

Attached screenshots of how your container asks for the correct date information, but the reply is wrong.

I checked, and the log driver for Synology is a custom one, and I believe it is ignoring the --since/--until command plain and simple. I'm checking to see if I can change the log driver.

Thanks!

<img width="212" alt="Screen Shot 2021-12-01 at 12 06 47" src="https://user-images.githubusercontent.com/640406/144261271-0eb624af-ea4a-4ad7-a4e6-50e6704d3975.png">

<img width="700" alt="Screen Shot 2021-12-01 at 12 07 37" src="https://user-images.githubusercontent.com/640406/144261276-c9e640a7-3038-4aab-81f0-a040d20e9b59.png">

**Comment by sebastianarena** [comment]
@amir20 ok, so I fixed the problem... switching all container to use log "json-file"
It seems the synology default custom driver "db" ignores the "--until" parameter, and just gives you bad data
99% of the containers work, I just have a problem with one that when I reach the top for some reason won't ask for more logs :( not even the api call gets called, so don't know what is up with that, but this is much better

**Comment by amir20** [comment]
That sounds good. Glad to hear it wasn't with Dozzle. I didn't even know some platform use a different driver. 

Dozzle only loads previous data if there is at least 300 log items. So that might be what's happening.

**Comment by guader** [comment]
I have the same issue, the last line of the log is repeated for a certain interval (maybe for 10 or 15 seconds?).

If I switch to another container and then switch back, that would be resolved, but starting to repeated the newest  line.

My dockerd is configured as default, and containers are started by docker-compose.

So could you please tell me how to solve this issue?

<img width="979" alt="image" src="https://user-images.githubusercontent.com/10419703/163318529-55c8e2f8-0ca2-4183-9fc7-a9cb40cef448.png">

**Comment by Lx** [comment]
For anyone else hitting this issue while running Docker on their Synology NAS:
- The issue is probably that Synology configures Docker to use a custom `db` logging driver.
- That driver [fails to honour `--until`](https://github.com/amir20/dozzle/issues/1615#issuecomment-983785796).  (Thanks @sebastianarena!)

The solution in this case is to:
- Tell your containers to use the [`json-file` logging driver](https://docs.docker.com/engine/logging/drivers/json-file/)
- Potentially change `/var/packages/ContainerManager/etc/dockerd.json` to use `json-file` instead of `db` for all containers, and then restart Docker, noting that this will impact the ability for logging to show up correctly in the Synology DiskStation Manager.

It would be great if someone else might be willing to report this issue to Synology so that this non-compliant custom logging driver can get fixed.

@amir20: as Synology devices are relatively common, is this potentially worth a FAQ entry?

**Comment by amir20** [comment]
Send a PR for the FAQ. That would be great. I had a Synology a couple years ago.
