### ISSUE TITLE
Nice to have: Save state of which split panes are open via URL parameter

### ISSUE THREAD

**Issue by Coteh** [amir20/dozzle#1645]
**Is your feature request related to a problem? Please describe.**
It would be cool if I could save the state of the open panes via url param, so that if I refresh, I don't need to bring the additional container logs back up.

**Describe the solution you'd like**
http://localhost:8888/container/1f5c09af476f&split=ade0995bc3c5,...

Will open a page with container 1f5c09af476f on the left, container ade0995bc3c5 to the right of it, and any other containers specified afterwards to the right of that.

**Describe alternatives you've considered**
Nice to have

**Comment by amir20** [comment]
I agree. This would be cool. I also have been wanting to do something like this. I stopped working on it because right now the panes are based on ids. When the container dies, the id will change and the URL won't mean much anymore. 

One idea would be to use the container name instead, but in some setups like swarm, that can also change. 

If you want to work on this, that would be great. I don't think vue-router supports a complicated URL structure like this. So it might have to be something more complicated. 

> so that if I refresh, I don't need to bring the additional container logs back up.

Also if it's just about refreshing and not sending the URL around the maybe localstorage or settings would be easier than putting it in the URL?
