### ISSUE TITLE
Vertical split button next to horizontal split

### ISSUE THREAD

**Issue by carlosfrutos** [amir20/dozzle#1708]
I just installed and enjoyed the ease of use of dozzle, but I'm surprised there's no option to split the current screen horizontally. Just a button next to the current vertical split would be great because sometimes you just need to see the last 2-3 lines of many containers and it's easier to read if you can have everything in the same line

In case of consecutive splits, I would consider the current pane as a single one and split it. That might be a pain if you have to resize the internal components accordingly unless you got it under control.

Anyway, I'm surprised nobody asked for this feature, I can survive with the current configuration using several browser windows, but it would add lots of additional frames and lose efficient view space.

This functionality will allow anybody to make views similar to this one:
![TKmKp](https://user-images.githubusercontent.com/6514649/162197311-e28045f0-6a53-4733-8b8c-931c1882826b.png)

Thank you very much for your effort for this cool docker log viewer!

**Comment by amir20** [comment]
Sorry haven't had time to read emails for a while. 

I don't disagree that horizontal splitting would be helpful. During implementation, I was looking at a lot libraries and I did find something that does work. But then the integration got really tricky. I had to spend a lot of time on getting the UI right, and figure out how to switch between vertically and horizontally. All while keeping Dozzle simple. 

So I decided to not implemented because it doesn't seem to be a "must have feature". 

For now, I am focused on features that makes the usage of dozzle expanded to other audiences. 

I'll let Github close this automtically.

**Comment by carlosfrutos** [comment]
How about an environment variable that switches the split from vertical to horizontal? Should be a lot easier to implement, while keeping simplicity.

**Comment by amir20** [comment]
The env variable would have to be passed from server to HTML pages and javascript. Then a lot needs to change to support both. Not worth doing it. 

PRs are welcomed of course. If you can think of a simple way and you know vuejs it should be easy.
