### ISSUE TITLE
Antivirus blocking requests 

### ISSUE THREAD

**Issue by Antoine2tt** [amir20/dozzle#1802]
Hello ! 

**Describe the bug**

Since last update (i never touch the docker compose file, every update are done by WatchTower), my container are not showing anymore in Dozzle... 

**To Reproduce**

Go to Dozzle main page

**Expected behavior**

My running container are here ! 

**Screenshots**

![Screenshot_51](https://user-images.githubusercontent.com/979136/178063457-d6763d80-5ffd-4b47-9eb4-f4924e4c5dbe.png)

**Desktop (please complete the following information):**

 - OS: Ubuntu : 22.04
 - Docker version : 20.10.16
 - Browser & version : Google Chrome 103.0.5060.114
 - Version : 3.12.7

**If applicable include logs with `--level debug` and browser logs**

```
level=info msg="Dozzle version v3.12.7"
level=debug msg="filterArgs = {map[]}"
level=info msg="Accepting connections on :8080"
level=debug msg="starting to stream stats for: 74ee6bf5943d"
level=debug msg="starting to stream stats for: 4a2099e9f593"
level=debug msg="starting to stream stats for: ca413099641f"
level=debug msg="starting to stream stats for: 087ed50422c4"
level=debug msg="starting to stream stats for: 1237bccfc883"
level=debug msg="starting to stream stats for: 1ca8affd3e8e"
level=debug msg="starting to stream stats for: 2a13a5f711c7"
level=debug msg="starting to stream stats for: 24c6418957a3"
level=debug msg="starting to stream stats for: a4e0e1d54734"
level=debug msg="starting to stream stats for: 3911b71a11b1"
level=debug msg="starting to stream stats for: 86037674e43d"
level=debug msg="starting to stream stats for: 2c900b784472"
level=debug msg="stopping stats streaming for container 24c6418957a3"
level=debug msg="stopping stats streaming for container 74ee6bf5943d"
level=debug msg="stopping stats streaming for container 2c900b784472"
level=debug msg="stopping stats streaming for container 2a13a5f711c7"
level=debug msg="stopping stats streaming for container 86037674e43d"
level=debug msg="stopping stats streaming for container 3911b71a11b1"
level=debug msg="stopping stats streaming for container a4e0e1d54734"
level=debug msg="stopping stats streaming for container 1237bccfc883"
level=debug msg="stopping stats streaming for container 4a2099e9f593"
level=debug msg="stopping stats streaming for container 087ed50422c4"
level=debug msg="stopping stats streaming for container ca413099641f"
level=debug msg="stopping stats streaming for container 1ca8affd3e8e"
level=debug msg="starting to stream stats for: 74ee6bf5943d"
level=debug msg="starting to stream stats for: 4a2099e9f593"
level=debug msg="starting to stream stats for: ca413099641f"
level=debug msg="starting to stream stats for: 087ed50422c4"
level=debug msg="starting to stream stats for: 1237bccfc883"
level=debug msg="starting to stream stats for: 1ca8affd3e8e"
level=debug msg="starting to stream stats for: 2a13a5f711c7"
level=debug msg="starting to stream stats for: 24c6418957a3"
level=debug msg="starting to stream stats for: a4e0e1d54734"
level=debug msg="starting to stream stats for: 3911b71a11b1"
level=debug msg="starting to stream stats for: 86037674e43d"
level=debug msg="starting to stream stats for: 2c900b784472"
```

Here here my compose file : 

```
version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOZZLE_LEVEL: debug
    ports:
      - 9999:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true
```

Thank you for your help ! ^^

**Comment by amir20** [comment]
So I went through changes [v3.12.6..v3.12.7](https://github.com/amir20/dozzle/compare/v3.12.6..v3.12.7) and the only major changes were dep updates, golang update and the removal of `--key`. 


I don't see anything wrong from the logs. Your compose file looks fine. I'll have to start guessing. See if you can answer these questions: 

1. Does the browser have any errors? 
2. Are you behind a proxy? 
3. What happens if you go to `https://<host>/api/events/stream` Do you see any data?

**Comment by amir20** [comment]
Oh do try to restart docker engine if you can...

**Comment by cikichen** [comment]
+1

**Comment by amir20** [comment]
I updated to version `Docker version 20.10.17, build 100c701`, running Ubuntu and still can't reproduce this error. Hmmm.......🤔

Can you try disabling your extensions? Might be related to #1803.

**Comment by amir20** [comment]
I am wondering if one of the containers is throwing an error and I am just not handling the exception correctly. 

Based on your previous answer `/api/events/stream` doesn't do anything. Which is the culprit because it should return the list of all containers.  But based on the logs, Dozzle sees all the containers and streams the stats. 

I am truly stumped.  Since you are not seeing any data from streams, let's debug what can be happening in the API. It's probably not client related. 

Try `curl  https://<host>/api/events/stream`. If that doesn't return any data then that's where the problem is....

Then I would suggest removing all containers and having just one test one.  You can use `docker run  amir20/random-logger 500 1000` if you'd like. I use that for testing. 

If you are still not seeing any logs with a single container, I will add a bit more debugging logs and have you try a dev build.

**Comment by amir20** [comment]
Sorry, I think you misunderstood.  `amir20/random-logger` is for testing with dozzle. Remove all containers, and just have dozzle AND `amir20/random-logger` for testing. 

But seems like according to `curl` it is actually working. So then maybe it is your browser. 

Are you sure `http://127.0.0.1:9999/api/events/stream` in the browser doesn't show anything? If it doesn't then it is something happening to your browser and I can't be much help.

**Comment by amir20** [comment]
It's ok. English is my second language too. 👍 

Try using a different browser. There was an update recently to Chrome so perhaps they introduced some security thing I am not aware of. 

Try going to be to Dozzle version and see if the problem goes away. I doubt it.

**Comment by amir20** [comment]
Is there a chance you're behind a proxy at work or somewhere? The only time I have seen this is behind a proxy that breaks the stream. And you are doing curl with `127.0.0.1` so you wouldn't see the problem.

**Comment by amir20** [comment]
@antoine2tt interesting. I hadn't thought of that. Turns out Sophons runs it's own proxy and proxies all HTTP through it. But unfortunately, Sophons doesn't properly support server side events. There is a lot about this on Google. I also found this [stackoverflow](https://stackoverflow.com/questions/62129788/on-a-machine-running-sophos-why-do-all-my-browsers-fail-to-receive-server-sent) question. 

Sounds like if you run Dozzle with HTTPS then the problem should go away. The other solution suggests send 2MB to reset the flush. I won't do that. :) 

Glad we were able to find the root cause.
