### ISSUE TITLE
Ability to pass username and password as query string

### ISSUE THREAD

**Issue by binaryfire** [amir20/dozzle#1840]
Hey Amir

First of all, great project!

Would it be possible to allow the username and password fields to be populated from query string values? We run Dozzle behind oauth2 reverse proxies but we've had misconfigurations which have exposed services in the past.

The password we've set isn't a secret- it's just a buffer to protect against that. We'd still admins to not have to enter credentials manually.

**Comment by amir20** [comment]
Hi @binaryfire, 

Glad you like the project. 

I'd like to understand your use case a little more. Exposing user/password with `GET` is a security flaw because all the logs now include this information. While this might be ok for you, I doubt it is ok for the majority of users and I wouldn't even want to allow it knowing it is an anti-pattern. 

What is exactly your use case? The username/password is meant to be a simple solution. Perhaps you can use an [nginx solution](https://github.com/oauth2-proxy/oauth2-proxy) which allows oauth.  Or just use basic auth. 

Other question, how would query parameters solve your problem? Could you use just do a post?

**Comment by amir20** [comment]
Hmm never heard back.  Closing.

**Comment by binaryfire** [comment]
@amir20 Hey Amir. Sorry about the delay.

Here's an example of what I mean:
https://github.com/linuxserver/docker-openvscode-server#application-setup
https://github.com/gitpod-io/openvscode-server#securing-access-to-your-ide

I hadn't considered the logging issue though. Maybe basic auth will be a better alternative

**Comment by amir20** [comment]
Thanks @binaryfire . Maybe I didn't understand something in those links, but sounds like the token based auth is pretty similar to the username/password solution I have now. 

Doesn't seem to be anymore secure. 

I think your best option is write an e2e test that makes sure Dozzle is never public. Or disable username and password and just place it under your own proxy with whitelisted IP addresses.
