### ISSUE TITLE
Option to hide / show time

### ISSUE THREAD

**Issue by eyalcha** [amir20/dozzle#1859]
Most of the logs includes time mark so there i no need for extra time added to each log line.

1. Globally enable/ disable time prefix
2. Configure hide / show time prefix per docker
3. Give option to set time pattern

**Comment by amir20** [comment]
Doing all kind of options is complicated because I have to test them all. 

> Globally enable/ disable time prefix

Do you mean the time as in `10:00 AM`? I don't think I would ever make this option because so many people want it. 

> Configure hide / show time prefix per docker

Settings per container isn't supported right now. But that's not a bad idea. I don't think I will prioritize it though. 

> Give option to set time pattern

What pattern did you want? So many people have asked to do this maybe I should just try it. The hard part is should it because completely configurable or a set in a drop down. What do you think? 


🎉

**Comment by eyalcha** [comment]
@amir20 you can see duplicate time field. One is from dozzle, one from the tool. It is redundant, so i think a flag should be added to allow show / hide of dozzle log entry time

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/64679987/187021974-3ea9551f-7de0-40b9-92cc-dd1776bce6d9.png">

**Comment by amir20** [comment]
That's already possible to hide the date and time. It's just not per container. Take a look at settings page.

**Comment by eyalcha** [comment]
Yes, it is in settings. Will be good to have it also as environment option.

**Comment by amir20** [comment]
That option should be a per user setting. Env var would be global which doesn't make sense.

**Comment by eyalcha** [comment]
@amir20 not sure I understand. Environment var is per user, it is not global.

**Comment by amir20** [comment]
Sorry @eyalcha I forgot to respond. 

There are three scopes of configurations in Dozzle: 

1. User scope which is specific to a browser (localstorage)
2. Deployment scope which is per install and configured for all users 
3. And no scope, something like hardcoded in binary 

I am talking about user scope while you are asking for deployment. My principle has been to allow for configuration at the lowest level needed but not higher because that makes things complicated. 

For this use case, if the deployment was to offer hiding timestamps, then I would have to either hide these settings from the browser or overwrite them which isn't easy. 

I want to keep Dozzle simple and not add a lot of customization. Testing is harder and edge cases are narrower.  Thus, I usually reject feature asks that are very specific to one's needs.
