### ISSUE TITLE
Timestamps in relative time format missing

### ISSUE THREAD

**Issue by agneevX** [amir20/dozzle#1889]
**Describe the bug**
Date formats are absolute, not relative.

Also, the date format does not match my region (which is set on the machine).

**To Reproduce**
1. View logs for any container

**Expected behavior**

Relative time to be shown.

**Screenshots**

<img width="252" alt="image" src="https://user-images.githubusercontent.com/19761269/192247739-30944c76-13df-47d5-ae38-29bbfe2a7fbc.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Windows or Mac Os]
 - Docker version [e.g. `docker version`'s output]
 - Browser & version [e.g. chrome, safari]
 - Version: 4.1.7

**If applicable include logs with `--level debug` and browser logs**

**Comment by amir20** [comment]
See https://github.com/amir20/dozzle/issues/1835

Relative timestamps were **removed** because I couldn't figure out how to support with browser natively for i18n.  Going forward, I won't support multiple language formats because it is just a headache to maintain. It was a hard decision but probably right one for me to reduce cost. 

The new version supports locale with `Intl.DateTimeFormat` package which should switch depending your browser settings. 

I don't have enough details to reproduce the bug.  The code change is https://github.com/amir20/dozzle/pull/1874/files#diff-06ec0f85fea122fe140aa5b93de48d0abda9c7d49de2c616d0a968a1b7ff4748R11 so please feel free to provide an alternative solution.

**Comment by amir20** [comment]
A quick search on [stackoverflow](https://stackoverflow.com/questions/57666095/browser-default-locale-intl-datetimeformat-vs-navigator-language),  suggests that locale by browser is ignored for `Intl.DateTimeFormat().resolvedOptions().locale`. It uses OS setting instead. I haven't tested this. But please confirm what you see with `Intl.DateTimeFormat().resolvedOptions().locale` and `navigator.language`. 

Thanks.

**Comment by agneevX** [comment]
> Relative timestamps were removed because I couldn't figure out how to support with browser natively for i18n.

The feature was functional, so sucks that it had to be removed.

> `Intl.DateTimeFormat().resolvedOptions().locale` and `navigator.language`.

Both are `en-US`.
