### ISSUE TITLE
Unable to see logs, 1min TTFB

### ISSUE THREAD

**Issue by TUNER88** [amir20/dozzle#193]
Looks like I'm running in same issue as #13

Locally it works fine, `api/logs/stream` returns some data almost immediately (*<40ms*)

But in our staging environment it takes ages to load some data, some request are running into timeouts without returning any data. I found out that only running containers are affected. Logs for stopped containers are available immediately. There seems to be some problem with requesting log data from docker, but `docker logs` forks fine. Any idea how I can debug it, any docker configs I can play with?

![Screenshot 2019-12-02 at 18 46 13](https://user-images.githubusercontent.com/1565397/69982171-1bf8e300-1534-11ea-8ffe-bbea4df21d1c.png)

Following errors are appearing in the browser console:
![Screenshot_2019-12-02_at_18_50_43](https://user-images.githubusercontent.com/1565397/69982489-e56f9800-1534-11ea-9e1e-0e193e023172.png)

**Comment by amir20** [comment]
I am pretty sure #13 was due to TTY being enabled which has been fixed since. Do you have a reverse proxy in front of dozzle? Most likely your server has some settings for keep alive connections that is limiting live updates. 

If you are using nginx, you may need to do something [like this](https://stackoverflow.com/questions/13672743/eventsource-server-sent-events-through-nginx).

**Comment by TUNER88** [comment]
@amir20 thanks for the hint, works like a charm now 👍
