### ISSUE TITLE
system and other servers logs

### ISSUE THREAD

**Issue by warlordattack** [amir20/dozzle#1962]
Would be so nice to have other systems and main synology nas logs inside dozzle :)

Best regards

**Comment by amir20** [comment]
Dozzle is for docker only. Supporting other logs would be too hard. Mainly because Doxker has APIs that expose the logs consistently. 

You can always do `tail -f` inside a container and mount any log you want.

**Comment by amir20** [comment]
@warlordattack I tried `docker run -v /var/log/syslog:/var/log/syslog busybox tail -f /var/log/syslog` and it worked great. It also only takes very little memory. Does something like this for you?

**Comment by warlordattack** [comment]
works fine, thank you 👍

**Comment by kernelkaribou** [comment]
Just wanted to add a little color to this in case someone else comes across this. I have fully adopted this into my modest homelab use as a longtime Dozzle user. Originally wanted to get something for logging and looked into solutions like Loki or Graylog Open log but they were all sledgehammers for what was wanting a place to review files in a more UI solution.

Using a tiny container like busybox I can tail logs I write to from some of my scripts and Dozzle makes it super easy to review and search through without much overhead.

Example of simple Docker Compose for a log
```
services:
  some-logs:
    image: busybox:latest
    container_name: some-logs
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /path/to/log.log:/mnt/log.log
    command: tail -Fc0 /mnt/log.log
```

I have three containers running solely because I wanted true log isolation. You could just do a directory of logs and tail out the directory of logs on the container side, tail does do some formatting to demonstrate which log is outputting.

With three containers on my own server the combined RAM usage is not even above 5MB with not even a measurement of CPU, <1%

If you are concerned about logs getting bloated, look at [logrotate](https://github.com/logrotate/logrotate). If you are using it with the tail command above for a container, make sure you use a `copytruncate` parameter for your rotate profile because after it gets rotated I found the tail would fail because the file handle breaks, this solved for me with no measurable impact.

The trifecta came with the scripts outputting logs also notifying to my [Ntfy](https://github.com/binwiederhier/ntfy) container that I would have it include a dozzle URL that had the [/show?name=container-name](https://dozzle.dev/guide/faq#we-have-tools-that-uses-dozzle-when-a-new-container-is-created-how-can-i-get-a-direct-link-to-a-container-by-name) as an action URL in the notification, taking me right to the logs in dozzle if there was an event I wanted to look into.

Overall a great lightweight solution for scenarios where you are logging your own details. I don't use it for more system logs like the original post but see no reason why this wouldn't be a great solution for that as well. Awesome to use a wonderful tool like Dozzle in multiple ways.

**Comment by amir20** [comment]
@kernelkaribou that's great! I love all the details you provided. Do you think anything can be improved at https://dozzle.dev/guide/log-files-on-disk? Please do send a PR if you think so. Thanks!

**Comment by kernelkaribou** [comment]
Had I saw your writeup I might not have written this one 😝. Will see if anything I can contribute.

**Comment by amir20** [comment]
😂 maybe it's hard to find. Any addition to make it easier to find is greatly appreciated.
