### ISSUE TITLE
[Feature request] Concatainer log?

### ISSUE THREAD

**Issue by ShagoY** [amir20/dozzle#2]
Hello:)

What do you think about adding the possibility to concatenate logs with a possibility to ignore based on the container name?

Regards,

**Comment by amir20** [comment]
You mean watching logs for multiple containers? I am not against it, but what's your use case?

**Comment by ShagoY** [comment]
Yes, I mainly use your application to check the proper functioning of my containers and to keep an eye on them.
Currently, having to "go back" etc. to look at each of my containers can be a little boring but it still works.

So I wondered if we could concatenate them or allow them to switch quickly with a drop-down menu for example?

It's just for "quality of life".

**Comment by amir20** [comment]
> Currently, having to "go back" etc. to look at each of my containers can be a little boring but it still works.

Yea this is a bit annoying as I had to do the same. 

> So I wondered if we could concatenate them or allow them to switch quickly with a drop-down menu (and filter) for example?

I think for v2, I want to have checkboxes next to container names. Checking each container will enable the logs. However, that's a bit of work. I think for v1, doing a drop down is a bit easier. I am thinking of doing something like a vertical sidebar where you can quickly switch between containers. What do you think? 

> I would also like to be able to link the concatenation to a dashboard. This way I could see all the logs live (with prefixes linked to the names of the containers for example).

Explain this one. Do you mean like an `iframe`? 

I also want to add a needed feature which only scrolls if the scrollbar is at the bottom. 

I will admit I need to still add a lot of UI first. I am working on that. It sounds like this tool would be helpful to many people. I am debating because on reddit not many people seemed to care. What do you think?

**Comment by amir20** [comment]
@ShagoY I have updated the latest UI and deployed it to docker hub. You should be able to play around with it and provide feedback.

**Comment by ShagoY** [comment]
hi Amir 20 :)

Sorry I was on a business trip....

I discovered your docker on Reddit, so don't worry if it's quiet, it doesn't mean anything ! ;-)

Yes I was talking about an iframe, for example, I use Organizr which allows you to use code on the home page.

Otherwise I'm not a fan of vertical menus because I find that we lose vertical space and with the long lines of the codes it can be less readable. But excellent work anyway! This is a step in the right direction:)

I would have seen a header with a drop-down menu.

So you plan to add a concatenation? With different colors per log, that would be great.
I don't really use "verbose logs" and I appreciate being able to see quickly if something is going wrong.
However, I still need to be able to "ignore" some containers (Example Unifi controller) because this one tends to spam... 

Anyway, thank you for your work! All that's missing now is some finishing touches to make it more popular, I'm sure!

Translated with www.DeepL.com/Translator

**Comment by amir20** [comment]
> Otherwise I'm not a fan of vertical menus because I find that we lose vertical space and with the long lines of the codes it can be less readable. But excellent work anyway! This is a step in the right direction:)

I am not a fan either. I tried different designed. To put the design horizontally, it meant I had less space. Also, when running swarm, the container names are very long. My other option was to make it a drop down. But I felt that bad UI because now it requires two clicks vs one. So I opted for left or right menu. 

The problem with drop down is when I add checkboxes. It wouldn't work really well when there are multiple containers being watched. 

> So you plan to add a concatenation? With different colors per log, that would be great.
I don't really use "verbose logs" and I appreciate being able to see quickly if something is going wrong.
However, I still need to be able to "ignore" some containers (Example Unifi controller) because this one tends to spam...

That's for v2. I did some investigation and Docker doesn't allow watching multiple logs. I would have to do it via websocket which is ok but I have to test it. I want to get some traction with the current design first.  :) 

You are welcome. Hopefully, you like the changes so far. Besides concatenation, are there any other features that are important to you?

**Comment by ShagoY** [comment]
Maybe a "responsive design" display (bootstrap makes it easy to do).

A possibility to delete logs etc... Or filtering and search menus.

**Comment by amir20** [comment]
I just added responsiveness with commit https://github.com/amir20/dozzle/commit/5979a6d0e5f9c119364d816b1133f3b2476b84ad. 

I am thinking about search but since the logs are not backed by a database then it would only filter the current view.

**Comment by ShagoY** [comment]
> I just added responsiveness with commit [5979a6d](https://github.com/amir20/dozzle/commit/5979a6d0e5f9c119364d816b1133f3b2476b84ad).

It works like a charm!

**Comment by jayalfredprufrock** [comment]
This would be an absolute killer feature. I think the current design with the containers in the left menu bar could continue to work as well. Perhaps a shift+click could allow you to select multiple containers to aggregate logs. Kitematic already gives me the ability to look at individual container logs (albeit in a less beautiful way than dozzle) but being able to aggregate them would make this app really stand out. Regardless, great work!
