### ISSUE TITLE
Color coding

### ISSUE THREAD

**Issue by saitoh183** [amir20/dozzle#2012]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Color coding for Errors/Warning so they stand out. when log is just scrolling by, you need to stop it so you can see if you missed any errors because they dont stand out. The time has color so if the text could also that  would be great.

**Comment by amir20** [comment]
This feature has been asked before. The part I was trying to avoid is having a bunch of configurations to change colors and regex to match with errors. 

With json logs, it's easy because I can just check for error level. But it's harder with plain logs.  Maybe just check for `error` text. 

It would be great to feedback on how to avoid all the different configurations because that takes the most amount of time.

**Comment by saitoh183** [comment]
You couldnt just check for the words Warning and Error + variation and change the color of just those words, not the error message

**Comment by amir20** [comment]
Do you mean could?

**Comment by amir20** [comment]
I did some research. I don't think I'll do this. Or it won't be easy. 

If it is structured data then I can easily check for `data[level]`. But if it is not, then I can't just search for "error".  Ideally, I would search for a line that starts with "ERROR". But a lot of logging utilities do other things. 

So for now, I won't do anything because it seems harder than expected.

**Comment by amir20** [comment]
I prototyped something simple so I am opening this again. It's not amazing but maybe it will be good enough.

**Comment by amir20** [comment]
#2013 is related to this

**Comment by amir20** [comment]
@chiqui3d It's a little more complicated because Docker send multi-line logs as separate events. So I am working on that right now. 

I don't think I am going to provide a lot of configuration as that is just too much work. Hopefully, the default colors are good enough for most.

**Comment by amir20** [comment]
Just a little preview...

<img width="1318" alt="Screenshot 2023-01-23 at 2 06 41 PM" src="https://user-images.githubusercontent.com/260667/214160851-16d95f06-d3c4-4d86-b0a5-ec8d30a760f9.png">

It looks really promising.  I have some bugs. But this like a pretty cool feature that labels level and clusters lines together.

**Comment by saitoh183** [comment]
I like it

**Comment by amir20** [comment]
PR is merged. I think it looks pretty good. I will release a build soon after some testing.

**Comment by amir20** [comment]
New version is out. Looks pretty nice. I have a bug with multiple lines but I'll let it get used for a while. Let me know what you think!
