### ISSUE TITLE
get logs from remote docker via API (using certificates)

### ISSUE THREAD

**Issue by MG-Sky** [amir20/dozzle#2028]
For now dozzle can only query local docker instances, would it be possible to gather that data from dockers on remote computer via API (using tls)? I dont want to set Dozzle on each node i use now.  and that option would be fantastic.

**Comment by amir20** [comment]
Hey @MG-Sky. If you look for `DOCKER_HOST` you'll see some issues that mention this. https://github.com/amir20/dozzle/issues/1608#issuecomment-1330007159 is similar which should work with certs. Dozzle uses the same library as Docker CLI so all ENV vars are supported. 

Please give it a try by setting `DOCKER_HOST`. 

Let me know if it works. If you have time, please update the README file since many people ask this question. 

The one thing that is not supported is multiple hosts.

**Comment by MG-Sky** [comment]
that's the case I wanted to attach to remote host also having logs from local docker where this container is deployed.

**Comment by amir20** [comment]
I do not support that right now. The closest would be some drop down that could switch between hosts but that's not something I have time for.

**Comment by amir20** [comment]
It is now possible to set up remote hosts. See https://github.com/amir20/dozzle/#connecting-to-remote-hosts and https://github.com/amir20/dozzle/pull/2059
