### ISSUE TITLE
Add a logs count graph 

### ISSUE THREAD

**Issue by obriat** [amir20/dozzle#2037]
In order to detect quickly issues, a graph of logs count per minutes could be a cool feature.
It  could be displayed next to the LOAD/MEM graphs.

An additional feature will be the possibility to select a time range with the mouse (click, drag, release)

**Comment by amir20** [comment]
Ooh great ideas. 

Realistically, I won't get to this given my current load. But let's discuss for more. 

I'd like to redesign the homepage so having log volume there would be a cool feature to sort.

**Comment by amir20** [comment]
Thinking more about this, it would be cool if the count per minute to be on the right as the user scrolls. That's a hard component to build. :P

**Comment by obriat** [comment]
The main idea behind these two issues (filter + graph) is to provide an lightweight ELK-like on the developer local stack. So they can easily see errors generated by their current codes modification.
The next feature will be field "detection"/ indexation, so filter could be apply on them: error levels, facility, tag, ...

**Comment by amir20** [comment]
Thanks @obriat 

I have been thinking about this.  Here are a couple issues that I see that might make implementing these features hard. Please tell me what you think: 

1. Currently all user settings are stored in `localStorage`. But if I was to introduce personalization, then I think they would need to be stored on the server as multiple people would want to reuse saved filters. That is hard because right now Dozzle is stateless. 
2. Log level detection already works. However, Dozzle is really about helping to debug in realtime. Meaning, there is no offline indexing. So a query like "find all errors in the last hour" wouldn't work. Instead the stream is analyzed real-time and the UI shows the different levels. 
3. Because the architecture is simple compared to ELK, I can focus more on the features needed to view logs in the near past instead of handling the large volume of logs. I don't have to worry about using too much disk, TTL or low latency queries that are not supported via the Docker client. 


I am not against supporting some of the suggested features. But the question that I have is -- **should Dozzle remain focused on live streams or expand its scope by also storing historical data?** 

Based on that answer, I could support other features similar to ELK or keep it limited and only support features that make sense to Dozzle's use case. 

I hope that makes sense. Excited to hear what you think...

🚀

**Comment by amir20** [comment]
Never heard back. Closing.

**Comment by obriat** [comment]
Sorry, miss your last response. Your answers make sense, dozzle is not mean to replace ELK, but I still think a option to store and load à config on disk could be a nice feature.
Nothing fancy, maybe something as simple as a json config file mounted as a docker volume? It will remain stateless but will a default config (filters) at startup

**Comment by amir20** [comment]
Thanks. If I find time, I'll just worry about having customization. Something simple like `json` file will do.
