### ISSUE TITLE
Logs of "Overseerr" are white font on white background = not readable

### ISSUE THREAD

**Issue by ManiMatter** [amir20/dozzle#2039]
**Describe the bug**
Logs of overseerr are shown with white font, on usual white background, thus unreadable.

**To Reproduce**
1. Install overseerr lscr.io/linuxserver/overseerr:latest
2. Go to dozzle 
3. look at logs for overseerr
4. see errors

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/124743318/217389944-795d75b9-d0b5-4af7-b9fe-f742ab62b41d.png)

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Docker version 
 Client: Docker Engine - Community
 Version:           23.0.0
 API version:       1.42
 Go version:        go1.19.5
 Git commit:        e92dd87
 Built:             Wed Feb  1 17:46:28 2023
 OS/Arch:           linux/arm64
 Context:           default

 - Dozzle Version 4.7.4

**Comment by amir20** [comment]
I have seen this before and unfortunately it is a bug with overseerr. It is outputting color coded logs which is why you see info and debug as different colors. But they are also emitting white text which breaks. You can validate this by doing `docker logs` and also seeing white text. 

I won't be able to fix this on my side.

**Comment by ManiMatter** [comment]
Thank you amir! I have taken your response and forwarded it to overseer:
https://discord.com/channels/783137440809746482/1019783950413082687/threads/1072646723933057094

**Comment by amir20** [comment]
You are welcome. I did some testing and it does look like my hunch is true. 

```
{"m":"2023-02-08T18:23:54.140Z [\u001b[32minfo\u001b[39m][Discover Slider]: Creating built-in discovery slider {\"slider\":{\"type\":5,\"enabled\":true,\"isBuiltIn\":true,\"order\":4}}","ts":1675880634140,"id":2838675091}
```

You can see above that [Discover slider] starts with `info\u001b[39m]` turns the text to white.

**Comment by ManiMatter** [comment]
Thank you very much - i'll paste your response to the discord channel - hopefully it will help the gents from overseerr.

Best
Ben

**Comment by ManiMatter** [comment]
hi Amir,

pasting here what the folks on discord opined. I am not very technical myself, thus I can't opine whether that makes much sense. Maybe you want to join the discord conversation yourself..


_This is inevitably gonna turn into a discussion about whose responsibility it is to do what, but my take is that colored output is a shell feature supported by almost all terminal applications, so an application that wraps completely standard CLI shell functionality should support colored output - and support doesn't just mean being able to display it as-is like Dozzle does now, but also properly displaying text that is not legible on a white background. Very few people use a white background in their terminal applications, because it's just not standard. Expecting the application that writes this output to not use a certain color because some other application might display it on a white background doesn't make much sense._

**Comment by amir20** [comment]
Ha. Well instead of having you be the middle man, let's just have solutions. 

> Very few people use a white background in their terminal applications, because it's just not standard

I would point out that the default terminal on Mac OS is actually light and the terminal is white. 

I don't know what logger they use, but they should detect terminal and disable colors accordingly.  That's what Dozzle does. On terminal it has colors, but it if detects colors are not supported then it is disabled. 

But since apparently, you are the few people who use light background 😆 -- what to do about it? Luckily, you can go to settings > color scheme and make it dark theme.   Dozzle will be dark now. 

I think that's the best solution without you having to be caught in the middle of who does what.

**Comment by ManiMatter** [comment]
Ha! thats a great suggestion.. and guess what - I am actually a Mac OS user and was surpised by that statemetn of "people not using white background" as well ;-)

Will turn Dozzle to dark.

Thanks for the awesome (dark) tool ;)
