### ISSUE TITLE
Search across *all* containers?

### ISSUE THREAD

**Issue by JaneJeon** [amir20/dozzle#2047]
I'm really sorry for the frequent requests, but I just came across a use case that I think would be nice to have in dozzle itself.

Basically, there are times (mainly when I'm doing systems-level configuration changes) where I want to search for a particular string across _all_ containers (e.g. "permission" to see if me touching the filesystem causes any apps to have permissions error when reading/writing files).

As of now, I have to search every container individually in dozzle, but I was wondering if it'd be possible to Ctrl+F directly from the "home page".

Thank you.

**Comment by amir20** [comment]
> I'm really sorry for the frequent requests, but I just came across a use case that I think would be nice to have in dozzle itself.

No apologies needed. I really enjoy learning about other peoples needs. Some times it is an easy feature and some times it requires a major redesign. For example, this feature ask is a hard one. 

> Basically, there are times (mainly when I'm doing systems-level configuration changes) where I want to search for a particular string across all containers (e.g. "permission" to see if me touching the filesystem causes any apps to have permissions error when reading/writing files).


That makes sense. I could see how that would be useful. There are two problems with the current architecture. Dozzle does searching in the browser only. So it would be impossible to search across all containers in the browser. 

The other solution would be to move search to the backend. This would be hard, but still slow. So now Dozzle would have to load all the logs and search each line. 

Docker CLI doesn't have a search option. The best solution would be to write all the logs to some database that would allow searching. Unfortunately, that doesn't seem to be in my scope.  See https://github.com/amir20/dozzle/issues/2037#issuecomment-1430112371 which I explain why that doesn't make sense. 

I am not against making some of these changes but Dozzle is really meant to view log streams. Not go back in time.  It would be a major redesign to allow that. 

> As of now, I have to search every container individually in dozzle, but I was wondering if it'd be possible to Ctrl+F directly from the "home page".

Have you used the split view mode? Search does work across all of them. You can have as many as logs open in split view.  Of course, if you have a lot of containers then this wouldn't work. But if you have just a few this is probably the best option.  In the future, I hope to support saving split screens so that could be very useful to you.

**Comment by JaneJeon** [comment]
Re: split view mode, yeah, it's kinda hard searching across 20 containers xP

I was wondering if some sort of client-side searching would be possible, even if it might be slow?

**Comment by amir20** [comment]
> I was wondering if some sort of client-side searching would be possible

I don't think it's even possible. I would have to load 20 containers in the browser and search. The browser would run out of memory.
