### ISSUE TITLE
Thank you so much to everyone who helped build this project! :heart: 

### ISSUE THREAD

**Issue by theSage21** [amir20/dozzle#2051]
**I love this project!**

- Following our entire product strategy, this project is small :smile: (<10 MiB runtime ram). Thank you so much for caring about size and speed.
- It does ONE thing and does it REALLY well. I'm sorry for the allcaps but this is the first time I've had an emotional response to discovering some software on github. It has saved me so much pain and stress.
- I just wanted to say thank you so much! To everyone who helped build this, maintain it, and make it so easy to use!

**Background**

- I run a system that is run entirely on a single machine using docker.
- I aggressively drop tech throughout the stack and choose to keep things very simple, self hosting when possible.
- Based on how many customers are logged in, production has anywhere from 5-100 containers running so I ended up having trouble monitoring / debugging customer problems without introducing HEAVY things.
- I tried datadog, loggly, docker over ssh + grep, docker desktop... and at some point I wrote my own thing as well.

**Why not <X tech/project>**

Most other tech / projects / services were discarded due to one or many of these reasons:

- Takes too much RAM / CPU as compared to what the product uses
- Too cumbersome to use
- Can't share easily with my teammates
- Will need to instrument product in order to be useful

**Comment by amir20** [comment]
It is comments like this that gives me the energy to create and maintain Dozzle. Thank you for the kind comments. The project was recently accepted in Docker's OSS which is also exciting. :) 

> re: Following our entire product strategy, this project is small

Oh yea! I care a lot. I have worked hard to keep the file size <4MB, memory footprint ~8MB and cpu usage very minimal. I think of this project as a pet a project that allows me to optimize every aspect. 

> re: One thing and does it well 

This is so funny. So many people keep asking for more features and I always push back. For example, https://github.com/amir20/dozzle/issues/2037#issuecomment-1430112371. I always think the best products are the ones that limit their scope and don't try to do too much. Thanks for validating that! 

Great to hear you use case. I also tried datadog and loggly. But I was just too cheap to pay for something I felt should be free. 😆

**Comment by amir20** [comment]
Also maybe the reason you have such great experience is because you and I run a very similar system on a single machine using docker. So it works out.

**Comment by theSage21** [comment]
> 

- It's nice to see another single machine enthusiast! :smile: 
- I'd be interested to know how you run your stuff. Is there a blog / book / paper you can point me to? I have a home cooked approach that works well for my case.
    - I have a single docker-compose file with separate profiles for dev/prod/staging
    - One nginx container that routes subdomains to container names and adds basic auth when required.
    - Some containers mount the docker socket so that they can manage customer containers.

**Comment by amir20** [comment]
I don't have any blogs. I mostly followed all options and tried to tailor the solution to myself. My projects are self-funded so I didn't want to spend a lot of money with tools or get huge instance in the cloud. 

* I used Docker Swarm on a single node. This makes services useful to scale up and scale down. I can also use healthcheck and make sure services are always running. I also think you can route resources to mesh which is nice. 
* I use [trafick](https://traefik.io/traefik/) and very happy with it. It supports TLS and can do a lot of configurations for each containers. It felt like an upgrade from nginx. I felt the DNS support was more intuitive. 
* I use Dozzle for logs and for everything else I ssh to debug. I keep it very lean because I only have 8gb which means I can't really run ELK or alike
* Deployment is a little wanky IMO. I still use `docker-machine` because it uses TLS authentication. I build containers locally, push to docker hub and then use `docker-machine` to update `DOCKER_HOST` and execute all commands against my remote host. The remote host will pull the images and update all the services to latest version. 
* I do have mounts for data. I also clear all stopped images via cron once a day to save on disk space. 
* On security, I use DigitalOcean and lock everything down with firewalls. I have monitors for CPU and disk usage because I am doing a lot of data analysis which very quickly uses all 100 GB 

That's about it. I have had to recreate everything a few times so I have gotten pretty good at doing the absolute minimum :)
