### ISSUE TITLE
Search per split pane if required

### ISSUE THREAD

**Issue by theSage21** [amir20/dozzle#2054]
**Is your feature request related to a problem? Please describe.**

- I'm running a compose file with nginx and a variable number of API instances for multiple clients
- Each API call goes to nginx with `X-ROUTING: asdf` header and is forwarded to a docker instance by nginx based on the routing key.
- The nginx logs display the routing key.
- However, the actual API instance logs do not display this identifier. They are unaware of it since the app is built in a single-tenant mode.
- When I search for this routing key in dozzle, ALL panes get filtered by this key. Nginx logs get filtered, which is good but consequently my API container logs get cleared since this key does not appear there.

**Describe the solution you'd like**

- It would be useful if I can optionally search for / not search for things per-split-pane. Using this I can drill down while following routing keys / session keys / job IDs across multiple services.

**Describe alternatives you've considered**

- Right now I'm restructuring my app so that it displays the routing key in it's logs.

**Additional context**

This is how it looks like when I currently search and when I don't do anything

- ![image](https://user-images.githubusercontent.com/7693265/219942660-e86e3e04-0cdc-4953-b380-19cebd4dffa2.png)
- ![image](https://user-images.githubusercontent.com/7693265/219942669-551f5445-8b32-470f-b3b2-fdd5aea4db72.png)

**Comment by amir20** [comment]
On phone so might have typos. 

Thanks for your explanation. It helps to understand your use case. The search happens on the browser so it would be easy to change functionally. However, the challenge is the UI. 

Some people want to search all columns and others just a select few. I can't think of an easy way to let users chose which columns to search. 

I am not a big fan of more pop ups. It also doesn't make sense to have hidden keyboard shortcuts that behave differently. Or clicking columns you want to search because that's just confusing. 

The best option I can think of is to have a setting to search all or just the active container which is the left most column. 

What do you think?

**Comment by theSage21** [comment]
- The active column idea sounds good. I'd be happy with that as well.
- We could also make the RAM / CPU bar roll over into a search bar. Then per-column we can have a separate search bar.
    - Moving across columns could be done with arrows/tab and Ctrl F opens search in single column /globally depending on settings.
    - ![image](https://user-images.githubusercontent.com/7693265/220000303-45cd4c9f-32d7-4d68-be08-8e2f2f16f9af.png)

**Comment by amir20** [comment]
That's a good idea. Your option seems to be the best choice depending on how long it takes me to do it. Right now the JavaScript supports only one filter so it would be a bit of work to have each split have its own filter. 

I usually only get a few hours to work on this per week. So let's keep it open and hopefully I can get to it. ❤️

**Comment by amir20** [comment]
@theSage21 how did you image `⌘+f` work? In your screenshot, only two of the three columns have search enabled. I don't think that makes sense because the shortcut is global so it would have to switch all columns to a search mode. 

You said `Moving across columns could be done with arrows/tab and Ctrl F opens search in single column`. How would that work not globally?

**Comment by theSage21** [comment]
> 

- The screenshot was just me doing inspect element and editing it there.
- I've been trying to see if I can help out with the PR but so far very little progress. Maybe I'll give it a go on the weekend after office.
- I was think of binding arrow/`hjkl` to move across panes and a global `Ctrl+f` to open up the search box in the pane that is in focus.
- To switch between global mode / per-pane mode I was thinking of either `Ctrl+F` vs `Ctrl+f` or to have a switch in the settings.

Does that make sense?

**Comment by amir20** [comment]
Any help would be great since there are few outstanding feature requests on my mind. 

> I was think of binding arrow/hjkl to move across panes and a global Ctrl+f to open up the search box in the pane that is in focus

I think to the average person having to focus is hard to grasp. This behavior I have found to be confusing and most people would open bugs for me. :P This is mostly why I have been avoiding any kind of cool shortcuts that are hard to find. 

> To switch between global mode / per-pane mode I was thinking of either Ctrl+F vs Ctrl+f or to have a switch in the settings.

I have settings page so I think that should just be an option. There is also the menu on the top right corner that say search only in this pane. We could use that if needed. 

So before starting implementation I think we should figure how the following scenarios work: 

- When setting is global, then I think `Ctrl+f` is easy. Just open the text box across all panes. We could even `tab` or your suggestions to move across text boxes in the panes. 
- When setting is scoped, then it gets confusing. The dropdown menu will be an obvious solution. But the keyboard shortcut is unclear which to open. 

Also another option which would be hard to implement is a `sync mode`. Have you ever used the AC mode in the car when the left and right have different settings? Then you can sync the temperature or have each side be different. 

Something like:

1. User does `Ctrl+f` and all panes open a search box
2. Searching will sync the value across all panes
3. There would be an icon that would say `enable sync` next to each search box
4. If user disables it then the sync doesn't work across all panes and each pane needs to be edited manually. 
5. Upon enabling the `sync mode` then the current search is copied across all panes. 

This is obviously harder to implement. But I do think part of Dozzle that has done so well is "easy to use".  The nice part of this is that there wouldn't be any global settings. It would just default to global and users can disable it temporary. 

What do you think?

**Comment by amir20** [comment]
@theSage21 also getting Dozzle up and running locally should be pretty easy. For the most part, you should be able to do `pnpm dev` and it should work.

**Comment by theSage21** [comment]
> 

- Sync mode sounds very good. I think I would go with that. Another place I've used it is sync-panes in tmux. You type in one of them and all the panes receive the same input.
- The way that works is to send input to all "visible" panes. Then when you "fullscreen" on one pane so that the others are not visible, typing will only send input there.
- This fullscreen / sync combo provides a very clean way to select "where" you're typing. Although to get this to work we would need to implement this "fullscreen" feature as well so I'm not so happy about that. A simple switch ought to be enough I think.

**Comment by amir20** [comment]
@theSage21 were you able to get Dozzle working locally?

**Comment by theSage21** [comment]
Hi! Nope I didn't get time yet. I'm planning to work on this tomorrow night.

**Comment by amir20** [comment]
Great! I just finished the support for multiple remote hosts #2059 which was a lot work. After a break, I can come back to this. Hopefully we can work together on it.

**Comment by amir20** [comment]
@theSage21 any update? Sadly I won't have time to work on this and it doesn't seem like a popular request.

**Comment by theSage21** [comment]
Hey! I ran into issues running the project with node / go in docker. I'll reopen it if I get time to work on it :+1:
