### ISSUE TITLE
Add hostnames/labels for remote hosts

### ISSUE THREAD

**Issue by psybernoid** [amir20/dozzle#2097]
Is there anyway, or a plan to add labels or hostnames to remote hosts?
Currently I see a list of tcp addresses, which whilst serviceable, isn't ideal.

**Comment by amir20** [comment]
I wasn't planning on it. I am looking at data and majority of people use only one or two hosts. So not a major priority for me.

**Comment by danktankk** [comment]
this would be something I would like very much as well in the future.  The data may suggest one or two hosts simply because they dont want to add it to multiple servers.  I have over 10 and it took more than a year for me to add a second instance.  All god if you dont want to obviously, but a centralized instance would be awesome.  Many thanks for your hard work!

**Comment by amir20** [comment]
I am just curious, what did you all have in mind? Another flag that maps ip address to labels? That seems messy and overly complicated. I wonder if there is a better way to provide a name. I hate having all kind of flags with complicated documentation.  And I really don't want to get in creating json files. 

@danktankk 

> centralized instance would be awesome

Isn't that already possible? Or are you saying you want labeling to be able to do that?

**Comment by danktankk** [comment]
> @danktankk
> 
> > centralized instance would be awesome
> 
> Isn't that already possible? Or are you saying you want labeling to be able to do that?

Im not sure how I would do it with the install of Dozzle I currently have.  Right now, Im not even sure how to add log files of things not in docker containers, like crowdsec for instance.

If I have missed some documentation on how to add that and I dont know anything about Dozzle being centralized to the point that you can add ip addresses or hostnames and pull log data to display either.  Sorry for the lack of a response.

**Comment by amir20** [comment]
I think you might be confused. Dozzle supports connecting to remote Docker hosts. That can be found [here](https://dozzle.dev/guide/remote-hosts).

 > Right now, Im not even sure how to add log files of things not in docker containers, like crowdsec for instance.

Dozzle doesn't support any log file. Only docker log files. If you are running something outside of Docker then you could create a tiny container and `tail -f` a mounted log. It's not great but it will do the job. Containers use very little memory. 

> Dozzle being centralized to the point that you can add ip addresses or hostnames and pull log data to display either

This is only possible using other Docker hosts. 

The ask in this issue is to also support labeling for IP addresses as the drop down could be confusing.

**Comment by amir20** [comment]
@psybernoid did you see my comment https://github.com/amir20/dozzle/issues/2097#issuecomment-1490739282? If there is an elegant way to provide labels then let me know. Otherwise, I won't have much time to work on it.

**Comment by saytesnake** [comment]
To be honest, at first I wanna some similar feature like that, but then I thought, maybe ELK or Loki is what I need. Dozzle keeping it simple is the right thing to do.

**Comment by amir20** [comment]
Keeping Dozzle is what makes it great. :) Not to say adding labels will make the hurt the simplicity. I just don't want to have too many flags.

**Comment by rpatel3001** [comment]
I think this feature would be nice too. Either an additional env var that contains a comma separated list of labels applied in order to the IPs (non breaking change), or use the existing env var to alternate labels and IPs (breaking change).

1. DOZZLE_REMOTE_HOST=IP1,IP2,IP3 and DOZZLE_REMOTE_LABELS=HOST1,HOST2,HOST3
2. DOZZLE_REMOTE_HOST=IP1,HOST1,IP2,HOST2,IP3,HOST3
3. Same as 2 but labels come first.

Of course it might be easier to simply set proper hostnames and use those instead of raw IPs.

**Comment by peterbuga** [comment]
for those looking for a temp solution for this, you could easily wrap a proxy in front of docker TCPs and give them some hostnames. mine (screenshot) is work-in-progress of a setup but you get the gist

<img width="289" alt="Screenshot 2023-05-19 at 11 19 27" src="https://github.com/amir20/dozzle/assets/6365174/ec3ad87f-9b99-43ef-afcc-1c9a481062e7">

**Comment by amir20** [comment]
Keep this open

**Comment by amir20** [comment]
I'll be releasing a big update for remote hosts so it's a good time to visit this feature. I'll see if I can implement something like https://github.com/amir20/dozzle/issues/2097#issuecomment-1507479531

**Comment by peterbuga** [comment]
@amir20 version `v4.10.17` already brings cleanup to the labels, thank you!
![Screenshot 2023-06-28 at 17 25 14](https://github.com/amir20/dozzle/assets/6365174/15ad5a12-8f2e-4b8e-8a12-f81b09254dbd)

**Comment by amir20** [comment]
Thanks. Yea I cleaned up a little. 

I have added support for labels in https://github.com/amir20/dozzle/pull/2276. Still no documentation. But seems to be workings.

**Comment by amir20** [comment]
OK merged in master and docs updated. https://dozzle.dev/guide/remote-hosts#adding-labels-to-hosts

Closing this. Will release maybe later today if someone can test it. Otherwise I'll wait until next week when I can test it more.

**Comment by alexdelprete** [comment]
> Will release maybe later today if someone can test it. Otherwise I'll wait until next week when I can test it more.

It's working fine, thank you for this.

Is there any way to also label the localhost (the local docker mounted via /var/run/docker.sock)? It's the only one we can't label...

![image](https://github.com/amir20/dozzle/assets/7027842/37f0195f-f314-4f1a-950a-afd1af058711)

**Comment by amir20** [comment]
Good to hear. 

> Is there any way to also label the localhost (the local docker mounted via /var/run/docker.sock)? It's the only one we can't label..

Ha I was thinking about that. I couldn't figure out a clean way to pass localhost name. Remote hosts are passed with `--remote-host` but localhost doesn't have a flag. 

I'll have to think about it... Perhaps, I can reuse the `--hostname` flag for localhost too.

**Comment by alexdelprete** [comment]
> I'll have to think about it... Perhaps, I can reuse the `--hostname` flag for localhost too.

What about a `DOZZLE_LOCAL_HOST` variable? Or...can we use localhost in `DOCKER_REMOTE_HOST`(with label)?
