### ISSUE TITLE
Enable loading of older logs when in search mode

### ISSUE THREAD

**Issue by bluepuma77** [amir20/dozzle#2143]
**Is your feature request related to a problem? Please describe.**
I would like to filter my logs by a device ID that is included in every log line. But with search enabled, I am not able to scroll back in time to see more older logs. Scrolling back only works without search.
 
**Describe the solution you'd like**
I would like to be able to scroll up, even when searching, and dazzle fetches older matching lines from the logs.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by amir20** [comment]
Dozzle performs searching on the browser. Simplicity is the biggest reason. Docker API doesn't support search otherwise it should be done at the API layer. 

Right now, scrolling up during search "should" work. I say _should_ because I have found bugs when the client doesn't know if there are any more logs so sometimes it stops loading more. 

I want to come back to this feature and possibly move all search to the backend. But that's not an easy task.

**Comment by bluepuma77** [comment]
I can live with loading all data and filtering on the client, but for me the scroll-up in search-mode does not work.

**Comment by amir20** [comment]
I don't think you understood my comment. Because the search is on client, there will be bugs. For example, if you scroll up, Dozzle tries to return another X items from Docker. But if none of those X items have the "search query" it just won't do anything because the filter is done after the client gets the logs. 

By the way, I have tested it a little and for my few use cases it does seem to work. There is no way for me to debug your environment though. 

One easy way would be to have your network tab open and see what data is returned when scrolling up.

- If no network request is sent that's a bug. 
- If a network request is sent but the data is empty then logs don't exist. 
- And finally if data does exist, but nothing is shown then the client has filtered all out which is the edge case I have been talking about.
