### ISSUE TITLE
Docker Compose Default Settings

### ISSUE THREAD

**Issue by x0tester0x** [amir20/dozzle#2161]
Is it possible to set the default settings in the docker compose file with environment variables?

**Comment by amir20** [comment]
Not possible right now. All the settings are done on the client so it would be hard to pass it through. 

Just out of curiosity, which setting do you want to change?

**Comment by x0tester0x** [comment]
24 hour style and dark color scheme :)

**Comment by amir20** [comment]
So I did some thinking...and it would be difficult to pass default data to the page. All user settings are stored in `localStorage` and all common configurations are done at API level since it is user agnostic. 

I don't think it would be worth the time to implement such a hard feature. 

Notably, 24hour style and color scheme are both default to `auto`. Which means it uses the browser `locale` and `theme` to automatically changes the style. 

I'll close for now as I don't plan to add default configuration.
