### ISSUE TITLE
Is it possible to use Goaccess?

### ISSUE THREAD

**Issue by gurumark** [amir20/dozzle#218]
This is a great tool! Thanks so much!
I was wondering if it can get integrated to https://goaccess.io/ for log processing and more.

Thanks in advance.

**Comment by amir20** [comment]
Hi there @gurumark. Goaccess sounds like an interesting tool. I spent some time looking at it. It seems like it parses and visualizes logs. In my opinion, goaccess and dozzle solve two different problems. Dozzle is a real time viewer like `tail -f` where goaccess aims to show aggregated data in a dashboard.  Since they solve different problems then I don't see how they could be integrated. Also Dozzle is coupled right now with docker and its API. There doesn't seem to exist anything else like Dozzle to show docker logs easily. But goaccess is a general tool that could work outside of docker as well.

Hope this helps.
