### ISSUE TITLE
Long swarm names are broken 

### ISSUE THREAD

**Issue by amir20** [amir20/dozzle#2187]
> @YouveGotMeowxy Can you provide exact example of some of the container names so I can test? Don't use Dozzle. Use `docker ps` in case of another bug.

I'm still seeing issues with the regex in `4.10.7`:

![image](https://github.com/amir20/dozzle/assets/39491297/29ba9372-7c2d-407e-8fdd-889fde9094dc)

Here's my entire list of container names: https://pastebin.com/be0q31Mt

It's strange, on Regex101 the above regex seems to work fine: https://regex101.com/r/6nHFEe/1

Sorry this is being such a pain!

_Originally posted by @YouveGotMeowxy in https://github.com/amir20/dozzle/issues/2144#issuecomment-1543466176_

**Comment by amir20** [comment]
@YouveGotMeowxy I think I was able to fix it. 

I am going to add some test cases first.

**Comment by amir20** [comment]
@YouveGotMeowxy can you try `amir20/dozzle:master` before I release it again....

**Comment by YouveGotMeowxy** [comment]
Success! Looks like 4.10.8 did it, ty for fighting with this for me. :D

Minor tweak requests? lol

Can you please extend the class name that makes the hashes to also include the ellipses at the end? Or even give the ellipses their own class name? Otherwise the list will look odd, like this (See green highlights for example)

![image](https://github.com/amir20/dozzle/assets/39491297/767c17d8-9d70-48c7-9c48-e1e4d25bc0f0)

If the class name gets extended to include them, then they'll also automatically be dimmed the same color, or if they get their own class name, we can style them ourselves to hide, dim, or do whatever else we want with them.

Also, can you please give a class name to the container/service names themselves (the part now left after the hash has been dimmed; yellow highlight). This way again, we can style them ourselves if we would like to. I use a Chrome extension names [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) so I can always tweak and save any style changes I prefer. :)

**Comment by STaRDoGG** [comment]
You can hide the ellipses with:

```
.is-ellipsis {
    text-overflow: unset;
}
```
