### ISSUE TITLE
image: amir20/dozzle:latest, actually v3.10.1 version

### ISSUE THREAD

**Issue by andyge2014** [amir20/dozzle#2265]
The latest version on github is v4.10.14. But docker dozzle uses the latest version, which is v3.10.1.
If using docker-compose, how can I update to real latest version (v4.10.14)?

docker-compose.yml config like it:
![image](https://github.com/amir20/dozzle/assets/10277356/518d96ee-61a9-4c23-b191-ec2af6779f00)

thank you for your help.

**Comment by amir20** [comment]
This is a tricky one because it completely depends on your setup. 

My overall advice would be to use specific tags. Like `amir20/dozzle:v4.10.14'. However, for me, `docker-compose pull  && docker-compose up -d` has worked. Doing a `pull` _should_ pull the latest. I say should because sometimes I have seen it not. 

There is also https://stackoverflow.com/questions/37685581/how-to-get-docker-compose-to-use-the-latest-image-from-repository which I think can help a lot. 

v3 is pretty old so hopefully you can change it :) Alternately you can set up watchtower which I know a lot do.

**Comment by amir20** [comment]
Closing but we can reopen if needed.

**Comment by andyge2014** [comment]
Thanks, I know what's causing the problem.
