### ISSUE TITLE
List of containers with their CPU and RAM consumption, sort-able columns

### ISSUE THREAD

**Issue by carmatana** [amir20/dozzle#2314]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

To have in the starting page a list of the containers along with their CPU and RAM consumption, being these 2 columns "sort-able" to easy identify problematic or abnormal behaviors.

**Describe alternatives you've considered**

Docker Synology DSM 7.1 and earlier used to have these functionality, but in DSM 7.2 they dropped it.

**Additional context**

Thanks for the attention

**Comment by amir20** [comment]
It's so funny you ask for this request. A few back I created a prototype with exactly this: 

<img width="2168" alt="Screenshot 2023-07-19 at 3 05 51 PM" src="https://github.com/amir20/dozzle/assets/260667/9c7cf699-ff48-4cec-af1c-ea3de62c5acc">

The problem was that CPU and memory were volitive so the sorting would be outdated very fast. I had to implement moving average to fix that. 

I hope to come back to this when I have more time to improve.

**Comment by amir20** [comment]
@carmatana how would you propose the dashboard would look when a user has multiple hosts? Right now it shows all containers across ALL hosts.

**Comment by carmatana** [comment]
Hello @amir20 

thanks for your time and attention

This view is very nice, somethng like this is what I was thinking.

https://user-images.githubusercontent.com/260667/254721895-9c7cf699-ff48-4cec-af1c-ea3de62c5acc.png

My comments:

CPU AND RAM

regarding the volatility of the CPU and RAM values maybe a refresh button could help, I mean an indication that the order is a snapshot and needs to be refreshed manually or at certain intervals.

An other option to the sorting problem is to not implement it but to have the values in color (both the background and the font to make them salient) to indicate level of consumption, in relation to total CPU and RAM.

the top 33 in red, the next in yellow and the rest in green or no colors but bars, I am just thinking aloud. Or rather than percentile,. 

MULTIPLE HOSTS

I only have one host, I am a user home with a handfuf of containers obsessed by this type of data because of the limited capacity of my NAS

But some ideas:

Maybe another column with the name of the host could help

Or a filter at the top to select one, some or all hosts.

A third option is to show relative values in relation to the corresponding host value, in the case of CPU is already shown as a percentage, the same could be for RAM.

**Comment by amir20** [comment]
Thanks for the detailed response. 

> regarding the volatility of the CPU and RAM values maybe a refresh button could help, I mean an indication that the order is a snapshot and needs to be refreshed manually or at certain intervals.

I was thinking of a refresh button. But while testing, I also saw the numbers for CPU to 20, 4, 22, 8, 30... When I implemented moving avg, it made the numbers a lot smoother like 20, 18, 19, 18...so I think it made easier when sorting. It also provides a less confusing experience IMO. 


> An other option to the sorting problem is to not implement it but to have the values in color (both the background and the font to make them salient) to indicate level of consumption, in relation to total CPU and RAM.

I am hoping I can reuse the chart or something similar from the container pages. But I like your idea of changing colors. 

I think with multiple hosts the best would be to just provide another column. 

This is something I am working on slowly so I'll share another screenshot when I have some progress.

**Comment by amir20** [comment]
@carmatana can you try `amir20/dozzle:pr-2317` and provide feedback?  I think it's looking OK. I have some bugs and haven't implemented many other things. But maybe I can release this for now.

**Comment by amir20** [comment]
Looking like this right now...
![13 containers - Dozzle @ clashleaders com](https://github.com/amir20/dozzle/assets/260667/5bd61160-5882-402b-b0f7-0781799bef91)

**Comment by amir20** [comment]
I have merged into master now. So use `master` tag.

**Comment by carmatana** [comment]
@amir20 

I agree that it looks OK and more than only OK.

Sorting by Memory is not working correctly, with my containers it showing a not sorted list, for example:

5 MB
10 MB
7 MB
120 MB
800 K

and so on.

In the case of CPU it is sorting correctly.

Also in the case of Memory the background color can be improved.

In my case I have only 14 containers, with a total Memory consumption of ~6.5 GB. Qbittorrent is consuming 5.5GB, I guess the background color should be RED for this container, but it is shown in GREEN. if the color is in relation to the total memory available, maybe the color green is ok. I have 12GB.

The mobile view is, obviously, a little more complicated. In landscape in a 6" screen it looks reasonable well.

In portrait each container line occupy several rows making it not very easy to be read.

In general I like much more this new presentation than the one without the CPU and Memory columns.

Thank you again !!!

**Comment by carmatana** [comment]
@amir20 

Great work ! 

I like much more this new view than the one without the new columns.

comments:

- In a mobile phone, view when in portrait is a little bit difficult, each container is presented in several lines. A natural consequence of having more columns. I do not know if it is better to have a scroll-able screen to present everything in one line per container.

But at the end, with a littel practice it can be read OK.

- In landscape it looks very good !.

- sorting by memory is not working, it presents not sorted values.

- I do not know if background colors are working as you intended.

In my case I have 14 containers with a total CPU of ~8% and total Memory consumption of 6.5 GB.

My system has 12 GB, so in terms of CPU and MEM everythign is OK. 

However of the 6.5 GB of memory there is one container consuming 5.5 GB. For me this container should be presented in RED but it has a GREEN background.

The same for CPU. I have one container consuming more than half (5%) of the total CPU consumption and is presented in GREEN.

I guess that it is a matter first of defining what each color means.

Overall: a great progress (for me).

Thanks for the attention and the effort !

**Comment by amir20** [comment]
hello hello @carmatana 

Thanks for collaborating on this. Sometimes I feel I am all alone with innovation here. :) 

> In a mobile phone, view when in portrait is a little bit difficult

I am using pre-defined components from [Oruga](https://oruga.io/components/Table.html). I think this is the default behavior. I am not a big fan to be honest. Something I'll come back to later. 

Mobile is a major use case for me so I think it's good to try to improve this. 

> sorting by memory is not working, it presents not sorted values.

So this is actually working but you may have not realized why. Docker returns two values for memory. One is % usage of allocated memory. Second, being total memory in terms of KBs. Example, a docker container can be allocated 1GB and using 750MB. Which means  75% usage. If the memory is not limited, then I believe % is just total memory available to Docker. This confused me as well because it could have sorted a container by %. But when looking at total MB allocated, it is actually different. 

I think to reduce confusion, I can do: 

1. Sort and only show %
2. Sort and only show total MB. The progress bar wouldn't make much sense here as Dozzle doesn't see total memory available. 

I am thinking option 1 is preferred. Personally if I had allocated limited memory to a container (which I do in for my docker containers) I would want those that are about to be OOM to be on top. 

What do you think? 

> I do not know if background colors are working as you intended.

I have not implemented this yet. The reason being I want to also change the colors on the historical container page. 

I try to ship as little as possible but often which incremental features. :) 

Let me know your thoughts on memory and I can release.

**Comment by carmatana** [comment]
@amir20 

As you may have realised, I am a home user with very little of sophisticationz so probably I am not in your target market.

I did not you can limit MEM per container until now.

In the case of the sorting I guess that however the criteria is (nominal or percentage), visually one has to see increasing or decreasing values that is the universal convention.

I guess that showing percentages works in all cases and showing nominal values not always.

A brief note explaining how Dozzle does the sorting may be sufficient, for example a description when someone hovers over the MEM column head.

**Comment by amir20** [comment]
> As you may have realised, I am a home user with very little of sophisticationz so probably I am not in your target market.

That's probably true for a lot of people who use Dozzle. The majority of users are home users and about 10% of users are small teams in smaller companies. 

> In the case of the sorting I guess that however the criteria is (nominal or percentage), visually one has to see increasing or decreasing values that is the universal convention.

This makes sense to me. I will change all labels to match the sorting. 

> A brief note explaining how Dozzle does the sorting may be sufficient, for example a description when someone hovers over the MEM column head.

I haven't added tooltips any where yet. I have put that on hold while I fix some other issues.

**Comment by amir20** [comment]
Released latest version. Will close this for now and come back to colors laters.

**Comment by amir20** [comment]
@carmatana sadly I had to revert some of these changes due to performance issue. Follow #2322
