### ISSUE TITLE
Total noob question

### ISSUE THREAD

**Issue by PostWarTacos** [amir20/dozzle#2337]
I have a total noob question and I feel like a bit of a dumbass for asking it lol. Please help me figure out how to generate the pem and public key for connecting to a remote host.
thanks!

**Comment by amir20** [comment]
I wouldn't be the person to give advice here since I think it's really hard. I did write a similar answer at https://github.com/amir20/dozzle/issues/2226#issuecomment-1567548604 which I think might work for you. I am lazy and use `docker-machine`.  I use `docker-machine create -d generic --generic-ip-address {ip-address} {docker-vm-name}
` with SSH. Works well.

**Comment by sebtech33** [comment]
Hello, sorry for reopening this, but im at a loss here too.
I have two servers at home, one that i have up with monitoring softwares and one with many services running. i was hoping to set this up on the monitoring server and have this server connect to the service server. both running docker, but they are not in a swarm. i have use the tecnativa docker socket, but mostly for connecting to the docker socket locally and restricting access to the api.

As you recommended with your comment here about docker-machine i tried that but fail to get it working over ssh. im unsure how to open for incomming connections to the docker sock too. i dont know if you have the time to maby add some more info to the "remote hosts" on the website/wiki or maby like to some places with more info for uss new to this.

**Comment by amir20** [comment]
@sebtech33 

>  i have use the tecnativa docker socket, but mostly for connecting to the docker socket locally and restricting access to the api.

Are you saying you did this and it didn't work? This is the easiest way to connect between hosts. You don't need swarm. Dozzle only needs `CONTAINERS` access. 

> As you recommended with your comment here about docker-machine i tried that but fail to get it working over ssh.

What broke? 

> i dont know if you have the time to maby add some more info to the "remote hosts" on the website/wiki or maby like to some places with more info for uss new to this.

This is not a simple request. Given all the different versions of Linux and configurations, I wouldn't have time investigate. In the comment above, there are instructions on how to use Docker to generate certs. But since I don't do that personally, I am not able to provide much help. 

Maybe stackoverflow or reddit?

**Comment by PostWarTacos** [comment]
Still not working...
Here's my compose file

`# Dozzle
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      DOZZLE_REMOTE-HOST: tcp://192.168.50.39:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
            
# Docker Socket Proxy
  socket-proxy:
    container_name: docker-socket-proxy
    image: tecnativa/docker-socket-proxy
    privileged: true
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    restart: unless-stopped`


and the log file for Socket Proxy

`08/10/2023 9:01:06 PM
[WARNING] 222/020106 (1) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
08/10/2023 9:01:06 PM
Proxy dockerbackend started.
08/10/2023 9:01:06 PM
Proxy dockerfrontend started.
08/10/2023 9:01:06 PM
[NOTICE] 222/020106 (1) : New worker #1 (8) forked`

**Comment by amir20** [comment]
Can you show the logs for Dozzle?

**Comment by PostWarTacos** [comment]
Not a whole lot going on there lol
```
level=info msg="Dozzle version v4.10.26"
level=info msg="Connected to 1 Docker Engine(s)"
level=info msg="Accepting connections on :8080"
```

**Comment by amir20** [comment]
That's because you have a typo. It should be DOZZLE_REMOTE_HOST. Underscore. Not dash. 😁

**Comment by PostWarTacos** [comment]
🤣🤣🤣🤦‍♂️🤦‍♂️🤦‍♂️ #rookiemistake ****ing typos

**Comment by PostWarTacos** [comment]
Got it working! Thanks!

**Comment by amir20** [comment]
With next release, warning log is shown if env vars are not recognized. 😬
