### ISSUE TITLE
DOZZLE_NO_ANALYTICS - Default to true (i.e no data sent out by default)

### ISSUE THREAD

**Issue by accforgithubtest** [amir20/dozzle#2375]
Appreciate your work on this neat simple and easy to use tool !

**Describe the bug**
Being a open-source project with an MIT license, it makes sense to not collect any data by default.
I believe DOZZLE_NO_ANALYTICS should default to not collecting any data.

Given this tool could be used mainly by selfhosting community, I suspect security principles to be on the vulnerable / error prone side.
Hence any default collection should be avoided.

I also recommend to rename this variable to avoid double negatives. (Something like DOZZLE_ANALYTICS_ENABLED ? )

**To Reproduce**
N/A

**Expected behavior**
DOZZLE_NO_ANALYTICS should default to not collecting any data.

**Screenshots**
N/A

**Comment by amir20** [comment]
I basically copied other OSS projects which all have analytics enabled by default. 😬 homebrew is one that I remember reading how they do analytics. 

If I were to disable analytics then in all honesty I would only get about 1% of the data which would defeat the purpose. I use this data to know how much usage I am getting and which features to prioritize. Since it's anonymized and aggregated and helps me a lot to build prioritize features then opt out seems to be a good choice.
