### ISSUE TITLE
Arm v6

### ISSUE THREAD

**Issue by Ian-Drunkenson** [amir20/dozzle#2399]
Dozzle used to run on my Rpi Zero with ARM v6 architecture but now it dosnt work any more. Is there anything I can do about it?

**Comment by amir20** [comment]
Hmmm yea, what happened to v6? I must have removed it a while ago. I added it back in #2401. 

Can you try `amir20/dozzle:pr-2401` and if all good I'll merge? Thanks!

**Comment by Ian-Drunkenson** [comment]
Unfortunately Portainer says: Stopped for a few seconds with exit code 132
Is there any posibility to see whats wrong by creating dozzles own log?

**Comment by amir20** [comment]
Hi @Ian-Drunkenson, then it might not be Armv6. 

> Is there any posibility to see whats wrong by creating dozzles own log?

I don't think it would help a lot because it sounds like the app is not even running. You can verify this by doing `docker run amir20/dozzle:pr-2403 --help`. You should see help message but exist 132 means something else went wrong. 

I did some [searching](https://stackoverflow.com/questions/60930359/docker-containers-exit-code-132) and it sounds like the instructions for arch still doesn't match. 

So I am not exactly sure what version you need. So I started thinking I should provide the same exact builds as Go [Docker image](https://hub.docker.com/_/golang/tags). They provide versions arm/v5, 386, etc... but NOT arm/v6. This is interesting. 

So in #2403 I did the same thing. You can pull `amir20/dozzle:pr-2403`. 

If that doesn't work, then I think you'll need to help investigating a little. My RPi is some where in the closet so I can't test it easily. 

But perhaps as a last resort, you can `git clone` Dozzle and do `make docker`. If that works, then I just need to know which version to build. 

Let me know how it goes! For now, I'll keep #2403 open.

**Comment by Ian-Drunkenson** [comment]
Portainer sais about my hardware:
OS Information: linux armv6l Raspbian GNU/Linux 11 (bullseye)
Kernel Version: 6.1.21+

Funny that it used to run quite well a while ago and suddenly it stopt working..

**Comment by amir20** [comment]
Did you try the new PR?

**Comment by Ian-Drunkenson** [comment]
Yes, still no success. Would be nice if i could find out what goes wrong on dozzle start like verbose 4 or 5.

**Comment by Ian-Drunkenson** [comment]
I cant reproduce either, dut its was not working for a while any more before I decided to post here. I didnt play around with the system. Its is used for one of several home DNS servers. All I have running is:pihole, portainer, unbound and watchtower. And it works all fine. 
But I still want to thank you for at least trying to help, I really do apreciate.

**Comment by amir20** [comment]
OK closing for now since there isn't anything I can do.
