### ISSUE TITLE
[Request] Support for cetusguard

### ISSUE THREAD

**Issue by lordraiden** [amir20/dozzle#2429]
It would be nice to have support for https://github.com/hectorm/cetusguard and a proposal for its configuration "CETUSGUARD_RULES"

In adition I would add to the compose    

 read_only: true

**Comment by amir20** [comment]
I tried reading the documentation and was a little confused. It seems like something like https://github.com/hectorm/cetusguard/blob/master/examples/compose/compose.socket-socket.yml should work for Dozzle. 

Dozzle does need the `sock` file. If you are connecting remotely, then just use https://github.com/hectorm/cetusguard/blob/master/examples/compose/compose.socket-socket.yml which only limits to `container/list`. 

I won't have time cetusguard because it seems little confusing. If you try it, then let me know and I can update the documentation.

**Comment by lordraiden** [comment]
Another option would be docker proxy

But I'm not sure yet what permissions would require dozzle, any Idea?
https://github.com/Tecnativa/docker-socket-proxy

  wpsocketproxy:
    image: tecnativa/docker-socket-proxy
    privileged: true
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - wp-netsocketproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=notice # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      - EVENTS=1
      - PING=1
      - VERSION=1
      ## Revoked by Default
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=0 # Watchtower
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1 # Traefik, portainer, etc.
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=0 # Portainer
      - INFO=0 # Portainer
      - NETWORKS=0 # Portainer
      - NODES=0
      - PLUGINS=0
      - SERVICES=0 # Portainer
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0 # Portainer
      - VOLUMES=0 # Portainer
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

**Comment by amir20** [comment]
Sorry the link didn't go through the first time. That's already covered https://dozzle.dev/guide/remote-hosts#connecting-with-a-socket-proxy. You only need `CONTAINERS=1`
