### ISSUE TITLE
Add filter for log levels

### ISSUE THREAD

**Issue by Corbie-42** [amir20/dozzle#2432]
The log level detection is already working fine. Now it would be great, if we could filter the output by log level. Every level should be filterable individually.

**Comment by amir20** [comment]
Yea, that's a good idea. But there is an issue why I didn't implement this. Right now, I _guess_ the level.  https://github.com/amir20/dozzle/blob/021d3f7a9938d81878d9ad71ec2dc36384f7e2a6/docker/level_guesser.go#L11

I use a combination of regex and filters to check for level. It could totally be wrong.  I haven't implemented this because I don't think I am always right. So what should happen to the filtering when it can't find the level? 

Example would be say there are 4 lines, WARN, WARN, INFO, NO_LEVEL. If I filter by WARN, should it not show NO_LEVEL too?

**Comment by EDIflyer** [comment]
Perhaps rather than treating as levels (as proper logging would, where you'd see that level and anything higher but nothing lower) you could instead treat them more like custom filters in Excel where the user could pick any combination of them that they want by ticking/unticking them? Hope that makes some sense!

**Comment by Corbie-42** [comment]
Maybe you can treat NO_LEVEL just like the level detected above. This often happens, if a log entry consists of multiple lines, like a stack trace.

You could also make it a option to treat such entries differently and show/hide them on demand.

@EDIflyer that's what I meant 😊

**Comment by amir20** [comment]
I think it would be weird if someone is filtering by INFO and then WARN doesn't show up. What do other tools do? Does anybody have examples?

**Comment by Corbie-42** [comment]
You can have a look at the [Chrome developer console](https://developer.chrome.com/docs/devtools/console/log/#level). There the log levels can be selected individually.

**Comment by EDIflyer** [comment]
Ah yes, good idea of an example!
![image](https://github.com/amir20/dozzle/assets/13610277/760a03b4-0ab5-4c8f-ae4d-a2812aa75dcd)

**Comment by amir20** [comment]
This is the javascript console right? I think with JS, you can only have `console.log`, `console.error` and `console.warnings` so that makes sense. 

But perhaps this is good enough and one option could be undefined levels. 

I'll keep thinking about this. Gotta finish the mult-user authentication first. :)

**Comment by EDIflyer** [comment]
Yep just the standard console in Chrome - It covers non JS things too (CSS, etc.) that might be why it has those other levels...
![image](https://github.com/amir20/dozzle/assets/13610277/ccf40a78-a79d-4c3b-b682-1f44f0e6fd8a)

**Comment by Corbie-42** [comment]
There is also `console.debug` in JavaScript, that's what they mean by verbose. In some languages verbose is the same as trace, which are both one level below debug. So there is no common usage.
There ate

**Comment by madrussa** [comment]
Most log tooling I've used will track what log levels it has detected and allow you to select from those that it has seen. The UI shows a toggle list of levels its seen so that the user is able to select those they deem important. You can then select a series of levels or a single level if you know what you're filtering for.

I don't feel as though Dozzle should decided what level is more important than another... considering that some systems use "critical", "emergency" or "serious" as log levels; but who knows what order they should appear! And then you can have a single container running multiple applications, each with their own log levels, this becomes even more confusing.

So getting back to KISS methodology, detect any level, allow user to choose those they want. 

In my opinion the only aspect of log levels that Dozzle may be opinionated about is ordering and colouring that appear in the list it has detected.

**Comment by amir20** [comment]
I started working on this https://github.com/amir20/dozzle/pull/3306 Still work in progress but can be tested with `amir20/dozzle:pr-3306`

**Comment by amir20** [comment]
I am releasing this now with `8.6.0`

**Comment by EDIflyer** [comment]
Thanks @amir20 - just tried and working well :)

**Comment by amir20** [comment]
Nice @EDIflyer. I am not super happy with it because I think it's annoying to uncheck all the levels. But I can't think of a better solution.

**Comment by EDIflyer** [comment]
Maybe have a 'clear all' option at the top of the list? When everything is unselected it could change to 'select all'?

**Comment by amir20** [comment]
I do like that idea. I was hoping to use an icon or toggle instead of having text. But I didn't think of unselecting vs selecting depending on the state.
