### ISSUE TITLE
[Request] Statistics related with the event volumes and notifications

### ISSUE THREAD

**Issue by lordraiden** [amir20/dozzle#2449]
**Is your feature request related to a problem? Please describe.**
I have many containers running the purpose of this is to detect containers with very chatty logs or anomalies.

- A very chatty log could degrade a HD and maybe those logs aren't useful so I could change the log level and this feature could help us to identify those containers.
- Additionally we could detect anomalies, for example a container that have very few logs per day but suddenly it gets tons of logs a single day.

**Describe the solution you'd like**
I would like to have a table with statistics per containers and accumulated in relation to the 

- events per second (average during the last X time)
- events per hour (average during the last x time)
- events per day (average during the last x days)

An histogram per contaniner to see the logs per hour or day during the last 12/24h or X days this could be useful to find anomalies.
An accumulated histogram for all the containers
This one is not accumulated but you get the idea.
https://www.ibm.com/support/pages/system/files/inline-images/image-20200318173736-1.png

A second phase could be to add alarms via telegram to notify anomalies, this could be used as well to notify error logs.

**Describe alternatives you've considered**
none
**Additional context**
In a 3rd phase maybe alarms/notifications could be defind based on regex.

**Comment by amir20** [comment]
Hi @lordraiden, 

This is something I have wanted to do for a long time. However, Dozzle architecture doesn't allow for this right now. Currently, the logs are _only_ streamed when a user opens a browser. Dozzle does NOT processes any logs in the background while not being used.  I made some tradeoff decision to keep Dozzle simple and most importantly minimize any disk/CPU usage when no body is using it. You can see this when opening container pages, the CPU history only starts when you open Dozzle.  There is no data before that. 

To do what you suggested, I would have to process all the logs across all containers continuously. After that, I could add stats and notifications.  I am not against it, but it would be _a lot_ of work. It would also be risky because now I have to store a lot of data even when users are not using Dozzle. If the stats you were looking for was for the last 5 minutes then I don't think it would be hard. I would just store it in memory. But as you suggested events per last x days requires persistence and storing all of this which would make it even more complicated.

For those reasons, I have kept Dozzle focused on seeing "now" as the most important use case. But maybe after all the current improvements to authentication, storing user searches and improving log levels I can come to it. 

But hopefully that makes sense what is needed before Dozzle could even process notifications and stats.

**Comment by lordraiden** [comment]
Hi, thanks for the quick answer, I understand that is an important change the architecture of the app.
But a first step could be to have a dashboard with all those statistics but those would be save on memory and only calculated if the web browser is open. That could be easier right?
You have the timestamps of all the logs you could get the statistics graphs on demand if the browser is open.
Maybe that part (searches, dashboards, etc.) could be leveraged with metabase, but it wouldn't be that clean vs native implementation, but an option.
https://www.metabase.com/

**Comment by amir20** [comment]
Yep. My first thought was to do a solution that is only container in the browser. That would be easier. With the understanding that when you refresh the browser, all the content and stats are lost. 

CPU usage might be a problem because I can't do _too_ much stats on the browser. 

Let me think about this more. I think in the perfect world Dozzle just keeps some memory stats. Re-deploying Dozzle would erase it but even with 100s containers it would be less than a megabyte.

**Comment by amir20** [comment]
This issue has been open for a while, but hasn't gained any interest. I still think it's cool, but the lack of interest makes me wonder if a lot of people want it. So closing.
