### ISSUE TITLE
Button to disable auto-scroll

### ISSUE THREAD

**Issue by binaryfire** [amir20/dozzle#2482]
Hi @amir20 

Any chance of adding a button to disable autoscroll? I've got several services that go nuts with the logs when they fail. It's very hard to find things in the log in these cases because the window keeps autoscrolling.

**Comment by amir20** [comment]
Hello @binaryfire. If you scroll up a little bit, Dozzle disables auto scroll. Are you saying there should be an additional way to disable without scrolling up?

**Comment by binaryfire** [comment]
Hey @amir20. Yeah an additional way (eg. a button in the top bar) would be really helpful. Scrolling up to stop things is very hit and miss when the logs are going crazy. It doesn't always work as expected.

**Comment by amir20** [comment]
I haven't seen a lot of people requesting this feature. There isn't a lot of space on the top, so personally, I don't think it would make sense for a button to always be visible when not everybody would find it useful. It would be distracting in my opinion. 

I'll have to think more what would be a good solution because I try to keep Dozzle very minimal. Which is I think makes it easy to use.  Maybe a better solution would be to figure out why it is "hit or miss" when scrolling up. I had tested a while back with like 100 logs / second and it seemed to have stopped fine.  Are you seeing something else? 

So let's keep this issue open, but probably not the highest priority.

**Comment by amir20** [comment]
I did a little more testing and it seems to work fine. So I am going to close this. If for some reason the pausing is not working correctly, we can create a new bug. I did notice you have to scroll a bit up but I do make it clear with a button that appears.
