### ISSUE TITLE
Full logs not displayed for files-on-disk

### ISSUE THREAD

**Issue by vutsalsinghal** [amir20/dozzle#2503]
I'm using [file-on-disk](https://dozzle.dev/guide/log-files-on-disk) with Dozzle to push output of a script. The output.txt is only ~300 lines long but dozzle is not displaying the entire file. The tail command I've tried with alpine images is:

```
OPTION1 - <docker preamble...> alpine:latest tail -n1000 -f /var/log/output.txt
```

```
OPTION2 - <docker preamble...> alpine:latest tail -c+0 -f /var/log/output.txt
```

Tried both option but Dozzle is displaying only the last 80-90% of the output.txt instead of 100% as expected.
- Version: Dozzle 5.4.2 (via docker on raspberrypi arm64v8).

---

Old related issue - https://github.com/amir20/dozzle/issues/200

**Comment by amir20** [comment]
I think I know what's happening. I was able to reproduce it. I am not sure if I have a fix for it though. 

So what happens when you scroll up, I capture that event and send a request to Docker asking for more data. When I do this, I call the API and say give me more logs with `/api/log?from=X&to=Y` where X and Y are relative to the top of the logs in the browser. 

The problem is that since `tail` dumps all these logs at **once** (eg. probably all within one millisecond), Docker doesn't return anything because there is nothing before that. 

This is a complicated fix since everything is based on timestamps in Docker. I wouldn't be able to fix it on my side. I can't just ask for "more data". Dozzle needs to ask for more data based on some key which if they are all at the same exact timestamp are equal. 

Does that make sense? 

I am not sure of any fixes on my side.

**Comment by vutsalsinghal** [comment]
Since `tail` dumps all logs at once, shouldn't Dozzle display all the logs? I understand the scroll event to docker log api wont fetch anything but shouldnt dozzle display atleast what already dumped by the log api?

**Comment by amir20** [comment]
> Since tail dumps all logs at once, shouldn't Dozzle display all the logs? I understand the scroll event to docker log api wont fetch anything but shouldnt dozzle display atleast what already dumped by the log api?

No, it only prints the last 300 lines. There has to be a limit otherwise browser will crash.

**Comment by vutsalsinghal** [comment]
ah that makes sense. I appreciate the quick response. I'll close the issue 🖖🏼

**Comment by vutsalsinghal** [comment]
Do you think the 300 lines caveat should be mentioned in the file-on-disk docs?

**Comment by amir20** [comment]
> Do you think the 300 lines caveat should be mentioned in the file-on-disk docs?

I was thinking about this when I first saw the bug.  But then I realized it might be unique to you. The common use case with `tail -f` is to follow a file that is being continuously updated.  In that situation, each line will be incremental. However, in your use case, you have an existing file which `tail -f` prints all at the same time. 

Dozzle focuses on streaming logs and not existing logs.
