### ISSUE TITLE
Be able to toggle on/of wrapping new lines 

### ISSUE THREAD

**Issue by 2snEM6** [amir20/dozzle#2519]
Sometimes we want to properly wrap new lines for debugging purposes. This is specially handy when working with GraphQL queries on a development environment. It's way easier to read query logs if the new lines are properly formatted

**Describe the solution you'd like**
It would be great if a toggle or similar allowed to do this

**Comment by amir20** [comment]
This is already possible in settings. 😁

**Comment by amir20** [comment]
<img width="485" alt="Screenshot 2023-11-20 at 6 36 09 AM" src="https://github.com/amir20/dozzle/assets/260667/2417ce9c-c356-4c5f-8067-16450629c140">

**Comment by 2snEM6** [comment]
For some reason it does not work for me when the value to be wrapped is part of a JSON property, see:

![image](https://github.com/amir20/dozzle/assets/7485885/df9c6f5b-70c8-49e2-a2dc-34cb366d9301)

**Comment by amir20** [comment]
Ah. It doesn't work for structured data. I parse the JSON and show the logs formatted. 

I don't know how json would respect line wrapping. What did you expect it to do?

**Comment by 2snEM6** [comment]
> Ah. It doesn't work for structured data. I parse the JSON and show the logs formatted.
> 
> I don't know how json would respect line wrapping. What did you expect it to do?

I got the inspiration from Grafana Loki, where it optionally parses JSON and then for each JSON property, allows soft wrapping display if enabled

**Comment by amir20** [comment]
Oh you mean the value? Could you share a screenshot with soft wrapping enabled vs disabled? That would help.

**Comment by 2snEM6** [comment]
With wrap lines on:

![image](https://github.com/amir20/dozzle/assets/7485885/94eabc73-0d51-4e39-8f5b-4af8ab083c23)


Wrap lines off:

![image](https://github.com/amir20/dozzle/assets/7485885/0bca23fd-ae08-46d1-8817-dcfe75483755)

**Comment by amir20** [comment]
Thanks. This helps. I don't think this actually wrapping. The picture above is just pretty formatting of JSON. Each field is placed on its own line. 

Is that what you had in mind?

**Comment by amir20** [comment]
I take that back. GraphQL is actually not valid JSON. So I am not sure how I would detect it and format it. 

I am going to close this until I find a better solution to support this.

**Comment by 2snEM6** [comment]
No problem @amir20 , I think maybe detecting \n characters with a regexp could work. I will submit a PR

**Comment by amir20** [comment]
Sounds good. Just heads up this might be a little more complicated. You would have to make sure it doesn't break other uses cases.  Based on your screenshot, you could make it so that "query" is automatically parsed with some kind of gql formatter. I searched for something like this. I couldn't find it. I think your idea of searching for `\n` might also work. An easier idea would be to also just use the `<pre>` html tag. I just don't know where you would show it since the properties are in one line. 

If you use Graphql a lot then I do think you are the best person to provide a PR because I don't personally use it often.
