### ISSUE TITLE
support url path by container name

### ISSUE THREAD

**Issue by flamestro** [amir20/dozzle#2523]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when the container id changes and my bookmarks are broken.

**Describe the solution you'd like**

I would like to have url's to container logs that are predictable.
This would allow creating reliable bookmarks.
The best fitting option for me would be to allow /container/<url_encoded_container_name>

**Describe alternatives you've considered**

An alternative is to go into dozzle and use the search feature to find a container, but thats actually as convenient as having the most important containers in my bookmarks. ( i run around 80 containers from which many are helpers and irrelevant in terms of logging)

**Additional context**

Another reason I would like to have this is because I use a self implemented VPS management tool (dockwave dot io) in which I added the possibility to install dozzle on a vps instantly.
I would also like to link to specific logs by a unique container name via a button in that tool, however, thats just a nice side-effect.

**Comment by amir20** [comment]
https://dozzle.dev/guide/faq#we-have-tools-that-uses-dozzle-when-a-new-container-is-created-how-can-i-get-a-direct-link-to-a-container-by-name

Have you seen that? 

This question gets asked a lot. Maybe I should move it to be more obvious. 🤔

**Comment by flamestro** [comment]
Oh this is awesome!
Thanks for the hint, I have not seen that this already exists.

**Comment by amir20** [comment]
If you are in the mood to update the documentation, that would be greatly appreciated. Also since you are in germany, maybe you can help out with the german translations.

**Comment by flamestro** [comment]
Sure I can do that.
I will submit a PR for the translations (assuming there are any issues in them).
I will also try to find a proper spot to put the container name related documentation into.

**Comment by ADTC** [comment]
@flamestro the most obvious way to expose this would be to put in the actual deployed Dozzle's home page itself. This is sometimes called a permalink, which is the wording I used in the mock below, but it can be anything. `Direct link`, a `Copy link` button, or an Icon? Or maybe the container name itself could link to the direct link instead of the container ID link?

<img width="1016" alt="image" src="https://github.com/amir20/dozzle/assets/6047296/50562162-1573-4afb-b933-91f63997aab3">

If you don't wish to re-open this issue, we can make a new issue. :)

**Comment by ADTC** [comment]
CC @amir20 

**Issue is that the direct link is not exposed in the UI.** One has to read the FAQ documentation to find out this feature even exists.

In my mock above, there's a new Permalink column which could be a link that is based on the container name, so that we can click to open it, copy it, bookmark it, anything we like. And it's already there in the first page a new Dozzle user sees.

Related: #1199

**Comment by amir20** [comment]
Not sure if it makes sense to be in home page. Home page is meant for things that are used often. Perm link isn't used often and it would just take extra space for no reason. A better place would be the drop down under each container. However, it would be confusing because copy/paste only works in https. I don't think it's worth implementing right now. PRs are welcomed though.

**Comment by ADTC** [comment]
@amir20 how about if you use the permalink instead of the container ID link in all the container names (both home page container name, and sidebar) ?

Since the page is like a single-page-app, there would not be any delay in resolving the permalink to the ID link, isn't it? It would still instantly load the logs when clicked?

Re: what you said about menu, maybe it could be a "Show permalink" option that just opens a modal that has the permalink in a text-box that the user can copy. Or you could have a Share button on the right side of container name or the left side of memory graph, which also opens the modal.

<img width="607" alt="image" src="https://github.com/amir20/dozzle/assets/6047296/4abf66cb-569b-4920-a2b5-5da6982fde68">

This would be pretty easy to do, and super obvious, and near the URL bar too... noticeable to someone about to copy from the URL bar. (Ignore the crappy design in mockup, obviously needs better design.)

**Comment by amir20** [comment]
> how about if you use the permalink instead of the container ID link in all the container names (both home page container name column, and sidebar list) ?

I think this a valid question. It has been asked before. I chose IDs because IDs are immutable. Once an ID is given, it won't ever change for the life time of that container. Names can be torn down. So it is possible that there were two containers with the same name but _at different_ times.  I think IDs make more sense since it would be confusing if `/container/foo` goes to one container and completely different container in the future. See https://stackoverflow.com/questions/59043514/docker-container-name-vs-container-id

> Re: what you said about menu, maybe it could be a "Show permalink" option that just opens a modal that has the permalink in a textbox or textarea that the user can copy. 

Yes, that would be the better way to do it. But doing a popup and some text is not possible in Dozzle right now. If someone wants to, PRs are welcomed. 

> Or it could simply be a link that says "Permalink" so the user can just right-click it and copy it. The easiest solution.

I think you missed my earlier point. Sharing and using perm links is not a common feature. It has been asked maybe less than a handful of times in the last few years. It wouldn't make sense to take any UI real state for something so minimal. My principle for showing UI content all times is for something to be used my majority of people. Which is why informational is always present (eg memory, cpu, logs, name), actionable items are under drop down (copy/restart/download).  This is a common pattern for UX.

**Comment by ADTC** [comment]
> showing UI content all times is for something to be used my majority of people.

Sorry if I wasn't clear with the last suggestion. I did not mean to repeat my earlier suggestion to put it as a column in home page. I meant adding the link on the header of the container logs page. Seems like it's a good place to have one without taking much UI real estate. This space is unused otherwise anyway:

<img width="694" alt="Screenshot 2024-04-19 at 1 52 26 PM" src="https://github.com/amir20/dozzle/assets/6047296/94778d55-7e53-4e42-837e-ef06cdb350eb">

I preferred it here because it's obvious and it's right under the browser URL bar, which acts as a reminder to someone about to copy the URL bar that there's a permalink they can copy instead. It could be just the link icon 🔗 without any text which shows a tooltip "Permalink to container by name. Right-click to open the browser menu and copy it.". Very little space will be used.

But if you don't want it in the UI **at all**, we could just hide it as a simple link inside the menu... without any modal or textbox, or anything like that. So anyone can open the menu, right-click the menu item, and copy the link. 

What do you think? @amir20

**Comment by ADTC** [comment]
_If I can figure it out, yes I can send a PR. It's probably Vue/HTML/CSS, right? Shouldn't be too hard :)_

Could we make the container name in the header a link?

<img width="713" alt="Screenshot 2024-04-20 at 5 50 26 PM" src="https://github.com/amir20/dozzle/assets/6047296/438d70f6-00ce-40a8-8f9c-901535470ca5">

That will take up zero space, since it already exists as (non-linked) plain text in the header. We can also show a tooltip when hovered, saying _this is a name-based permalink to the container_ (something like that).

I prefer this because it's more accessible than an extra item tucked away in the overflow menu. In the repo README and in `dozzle.dev` FAQ, we can also tell users that this is where you can copy the name-based permalink, so they don't have to manually create the URL by hand.

I can send a PR if this is acceptable. _This won't need any popup or custom copy/paste features btw, since it's just a plain old link._

**Comment by amir20** [comment]
That's an interesting idea. The issue with that is I would personally expect it to go to current container eg. `/container/[id]` and not the share url which would be `/show?name=foo.bar`.

I think you are making it more complicated than it needs to be honestly. I have a view of which features people request the most. Being able to share is not one of them. So there is no reason to put something with one click.  

A better solution would be to put in the drop down and create a custom keyboard shortcut like `command + shift + L` or something like that and have that copy the URL too. 

Let's move this conversation to a new issue.
