### ISSUE TITLE
Adding actions into mobile menu

### ISSUE THREAD

**Issue by ab623** [amir20/dozzle#2561]
Following up on https://github.com/amir20/dozzle/issues/2532, what are your through to where docker actions can be added into the mobile view. An overflow menu the far right of the status bar could be an option?

![image](https://github.com/amir20/dozzle/assets/3438974/9bf037cb-c094-47bb-9de6-f0af5cd038ec)

@akash-ramaswamy @amir20 thoughts?

**Comment by amir20** [comment]
For mobile, I had to make a decision to remove some functionality because there were just not enough space to show all options. For example, dates are shortened, search is not enabled and most of the functionality is bare minimum. 

So first, I think we need to figure out if this is not a good approach. I personally use mobile to look at quick logs to make sure none of my services are broken. In that case, I don't think it would make sense to have a lot of the same options as desktop. 

But of course I am curious if others use mobile for more advanced use cases.

**Comment by akash-ramaswamy** [comment]
@ab623 its heavy floods out here at chennai, and hope this comment gets posted inspite of the infinitely slowwww network 😅

I think that @amir20 design choices make sense, since i too have used mobile to peruse through logs, so that i feel safe, i HAVE NOT broken anything 😂.

**Comment by amir20** [comment]
Hi, coming back to this. I think the logical next step is to propose what functionalities should be enabled/disabled on mobile. 

| Feature | Desktop | Mobile |
|--------|--------|--------|
| See Logs | X | X |
| Homepage | X | X |
| Search containers | X | X |
| See stats | X | X |
| Stat history | X |   | 
| Search logs | X |   | 
| Settings | X |  X | 
| Download | X |   | 
| Clear | X |   | 
| out/err | X |   | 

This is what it looks like right now. If we want to change anything and add the dropdown, then I'd like to see proposals on what should be included. Personally, I have simplified the mobile version because I don't think people are trying to complicated things.

**Comment by surfingbytes** [comment]
Can we please add the action menu to mobile? It's one button that certainly fist next t the search icon and hamburger menu and would allow to use this app much better. Currently, mobile is kind of "read only" so I can't restart containers with it.

This menu from desktop:
<img width="264" height="496" alt="Image" src="https://github.com/user-attachments/assets/48db2bf0-6900-42e1-bb8c-a8f19e716d47" />

And here is a space for it on mobile:

<img width="552" height="107" alt="Image" src="https://github.com/user-attachments/assets/bc87826b-84c2-4592-85f7-ed60dae0fe61" />

**Comment by akash-ramaswamy** [comment]
Im kinda in middle now.. Im not able to strongly accept that mobile menu is need. But at the same time, I too have felt some times _(veerryyy feww timeeesss)_ that it would be nice to have this.

What do you think @amir20 ?

**Comment by amir20** [comment]
It's not a big deal because you can just rotate your phone to landscape. 


<img width="929" height="427" alt="Image" src="https://github.com/user-attachments/assets/9f826dcf-a06c-4e23-a09c-810067fa5d2e" />

Since there is a workaround, I don't plan to implement it.

**Comment by surfingbytes** [comment]
I don't think what you posted is mobile view, it's more likely tablet. On mobile, even if you rotate it, you see this (Samsung S23 Ultra), and the menu is not there (despite having plenty of space for the menu icon, in both portrait and landscape mode).

![Image](https://github.com/user-attachments/assets/5d6a9aca-2ae2-4419-ba29-152a4e7d451d)

**Comment by amir20** [comment]
That's on the iPhone Pro max. Seems like your screen is smaller. 

Adding the menu on smaller screens is too much work for me. So no plans to work on it.
