### ISSUE TITLE
filter by date

### ISSUE THREAD

**Issue by StephanKrauss** [amir20/dozzle#260]
Hello,

is there a way to filter the log messages by date.
When i press the Strg + Shift buttons i see the search field.
Can i enter a date like 'now' or 'yesterday'.

Your sincerly

Stephan

**Comment by amir20** [comment]
Hi @StephanKrauss. No that is not possible right now. Everything is unstructured data so filtering only works on plain text. 

I wonder if this should be supported? My thought is that it doesn't make sense as Dozzle is about most recent data and not filtering old data. Which is why I have focused so much on fetching everything in real-time.
