### ISSUE TITLE
Notify when detecting a expected value / message in log

### ISSUE THREAD

**Issue by akash-ramaswamy** [amir20/dozzle#2614]
**Is your feature request related to a problem? Please describe.**

Hi @amir20 ! Many times during development, I used to log something related to check whether a feature is behaving the expected way. If dozzle is able to notify and make users to *Jump to Context* even when not in the dozzle window, It would be very useful!

**Describe the solution you'd like**

Implement notification strategy and the **Buzz word input**, so that the dozzle frontend can check upon the logs of currently viewing container, and show a notification, clicking on it will land onto the context.

**Describe alternatives you've considered**
Maybe just highlight the buzz word!

**Comment by amir20** [comment]
Hi there @akash-ramaswamy,

There are things I like about this idea and things I think would make implementation complicated. 

I think overall, it fits with Dozzle's principle. Focusing on real-time debugging and helping engineers to look at the most recent logs makes sense to me. 

However, to implement this, you probably need to think of 2 things. 

1. How does a user configure the buzz word? This can be complicated and I wouldn't be a fan of a bunch of new settings. 
2. How are notifications sent? HTML5 has [Notifications](https://developer.mozilla.org/en-US/docs/Web/API/notification).  But I don't see a lot of people using it. 

On the first point, I think the coolest implementation would be extend the search functionality. For example, if user doesn't `ctrl+f` and searches for `buzz` then maybe there would be an option to notify when new logs are found. Personally, I think this makes sense because if you think about it, most people will search for `buzz` and then want to be notified. I doubt they would just want to be notified without searching. 

On second point, I remember a while back I tried prototyping notifications. But then realized it's more complicated because there needs to be background workers. So I gave up. 

So I think directionally I am supportive but might be complicated. Do I think notification will add value? For sure, because I can imagine in the future to also alter on ERROR logs.

**Comment by amir20** [comment]
Thoughts on this @akash-ramaswamy ? 

Would you be able to prototype something? I was thinking it might actually be harder than I thought because most browsers shut down tabs that aren't used.

**Comment by akash-ramaswamy** [comment]
> Would you be able to prototype something? I was thinking it might actually be harder than I thought because most browsers shut down tabs that aren't used. 

Yes @amir20 I'm working on this! Thanks for sharing this info! I will try to provide some prototype.

**Comment by amir20** [comment]
Hi @akash-ramaswamy, happy new year and holidays! 

I think you are heading the right direction but under estimating the work needed for this. I still think it's worth it and would be fun a little project for you to try to learn. See my responses: 
 
> Like a notification icon, which would be in active state when clicked and notifies if any new log contains such buzz word. The icon remains active until the user again clicks the notification icon. This was the approach which I thought, since it reduces UI changes by only an addition of icon in the search bar.

I like this idea too. It is what I was thinking. The only difference is, I suggest we put the notification icon on the right. Generally speaking info icons are on the left and action icons are on the right. In this case, the icon should be left of the close button. 

> We can use [ServiceWorkerAPI](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) and it seems its achievable and not that hard? Also we can implement the buzz word input in the search component itself in the following way:

As far as I know, ServiceWorkers don't do any work. They intercept push and network events. So _some other_ code would need to be processing the logs. 

Now remember, all the search processing happens on client. This is something that I think might need to change if you want to have proper offline notifications.  

> Also, regarding the background workers, to make sure that the worker is not doing anything after dozzle closes, or to make sure they receive notifications even when the page is suspended by chrome, I think we could explore this for more info: [PageLifecycleAPI](https://developer.chrome.com/docs/web-platform/page-lifecycle-api#new_features_added_in_chrome_68)

Yea, that's an idea we can explore later. 

Here is what I think you can try: 

1. First see if you can keep the architecture the same with search happening on client.  Prototype webworker or search on main thread (that's how it is now) to see if suspending the tab breaks it. To be clear, this should only be a test. 
2. If on client doesn't work due to browser limitations, then you will need to start moving the logic to server and start thinking about service workers. 

My recommendation is to prototype little by little and choose a direction on where the logic needs to go. This is how I would build a big application at work so hoping similar advice would help here. 

Let me know if this makes sense.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! Happy new year :)

Thanks for your detailed response. Now I'm getting even more clarity on your thought process. Glad that you brought up this much detail, since this makes me feel we both are in same track!

I will start prototyping this today, and let you know whether this could be achievable on client side or not :)

**Comment by amir20** [comment]
Any update on this?

**Comment by akash-ramaswamy** [comment]
Hi @amir20 !

As you said, the client side notification doesn't work when the browser shutsdown the page 😐! The event stream itself gets paused!

So researching on that a little bit.

**Comment by amir20** [comment]
Yikes. Alright. Let me know how it goes. 

If you'd want to not implement this I would be OK with that. I think it would be pretty hard. You could just start with moving search to backend as a start because that would remove some complexity. But I also don't know your commitment to this project :)

**Comment by akash-ramaswamy** [comment]
>You could just start with moving search to backend as a start because that would remove some complexity. 
Hi @amir20 ! Yeah, I will try this way.

Actually I really want this feature to be implemented. In fact I modified the dozzle source code with the Notification API and use it in mydaily work :) (but that is a bit naive implementation...)

Also I just wanted you to know that I manage my work, student-life and Open source contributions :) This is my favourite tool which I use daily and Im still committed to contribute to this project! I will be updating you as and when I progress!

**Comment by stwins60** [comment]
Hi @amir20, you could implement a notification using slack by asking users to add their webhook, and use grep to find keywords. These will require additional config in terms of running the command or using curl

**Comment by amir20** [comment]
The bigger challenge is where to process data, not where to show the notification. :)

**Comment by amir20** [comment]
Hi @akash-ramaswamy any update?

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! Apologies for the delay :)

I've just gotten back into the project after a busy period. Can I provide you with an update in the next couple of days as I catch up and resume work on this?

**Comment by amir20** [comment]
Sounds good! There has been some interest on this. Just wondering which direction you were thinking. I can't think of a way except to move logic to server.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 !

>I can't think of a way except to move logic to server.

Yes! This can only be done from server side as of now, since the browser shuts down the tabs. But the question is:
*Are we moving the search logic to server?* OR *Are we introducing PushNotification service?*

What I thought was, without disturbing the search (since it is very intuitive), just introducing the Notification Service would be suffice?

**Comment by amir20** [comment]
How long does it usually take before the browser kills it? I think it would be confusing if someone sets it and doesn't get the notification. So perhaps, we should pause the work and not do it.

**Comment by akash-ramaswamy** [comment]
Hi @amir20 ! The time it takes, is not known exactly. It is depending on the memory usage and CPU usage, the browser freezes the page.

But the thing is, PageLifecycle API allows us to capture when the page gets freezed.

**Comment by amir20** [comment]
@akash-ramaswamy, so I think if there was a way to minimize the confusion that the tab was killed, it would be a good feature. However, I can't think of a good way. Even using `PageLifecycle` might not work out because the user be wondering why it doesn't work since there isn't anything Dozzle can show. Most people using Dozzle are not technical enough.  So they would be confused and it would lead to more issues for me. :)

So sadly, I think it will cause more confusion than worth doing right now.

**Comment by xFlum3** [comment]
Hey @amir20 ,
There is any way to make this integration to discord webhook maybe ?

**Comment by xFlum3** [comment]
Hey @amir20 ,
There is an api maybe that i can get from them the logs to make an Python integration to the web maybe ?

**Comment by amir20** [comment]
Just use `docker logs ...`? Dozzle's APIs are tightly coupled to the UI.

**Comment by xFlum3** [comment]
@amir20 i need it to discord not in cli

**Comment by amir20** [comment]
I don't know what you mean. Sorry. Dozzle just uses Docker APIs. So you could do the same thing.
