### ISSUE TITLE
Option to enable log colors

### ISSUE THREAD

**Issue by contagon** [amir20/dozzle#2639]
**Is your feature request related to a problem? Please describe.**
I've been using dozzle for a while and was surprised when a recent update disabled text colors in logs (I think via #2626). I was a big fan of the colors, they helped separate the various levels of logging for me when quickly glancing at them.

**Describe the solution you'd like**
Is there anyway the log colors could be put behind a setting? Perhaps even turned off by default and prefaced with a warning that the colors may not always work 100% to reduce any possible issues.

**Comment by amir20** [comment]
Hey @contagon, I am not against it. I made the decision to remove it because I found more people were complaining about the colors than actually wanting the colors. 

My general thought is that if enough people want this, then why not. I just don't want to make Dozzle complicated for very few use cases though. So let's leave this issue open for a while and see if any body else does +1. 

Hopefully after the holidays I can take a look.

**Comment by devioa** [comment]
I just wanted to give feedback on this issue because I found that recent updates have caused text colors in my container logs to disappear. If possible, I still prefer colored log text to help me distinguish severity levels.

**Comment by amir20** [comment]
I think there is enough interest to come back to this. I need to think of a more performant way though as the old way was causing some slowness which is why I moved to backend.

**Comment by amir20** [comment]
Colors are back and should be deployed now. I was trying to get fancy and have options to disable it but I think that's more work than I can commit to right now.
