### ISSUE TITLE
Teeny tiny enhancement

### ISSUE THREAD

**Issue by YouveGotMeowxy** [amir20/dozzle#2655]
There's a nice "jump to bottom" icon that pops up and you can click on to scroll to bottom when you've scrolled up; would it also be possible to add the same, but as a "scroll to top", that jumps to the very first entry in the log? :)

It would be very useful for loooooooong logs.

**Comment by amir20** [comment]
Would it be weird that top is not really not top, because Dozzle just loads more logs when scrolled to the top? 

Bottom made sense because it is the absolute bottom, top just means that's all that the browser has loaded. 

> It would be very useful for loooooooong logs.

Dozzle starts trimming after 1000 lines to save memory so I wonder if it would be confusing when scrolling up will have different logs each time.

**Comment by YouveGotMeowxy** [comment]
Yea, I wasn't sure how that would work either, but when manually scrolling up it does that "endless scroll": thing as it loads. I was wondering if there was a way to just have it "skip" the in-between loads, and just re-load the screen from the start. Or some other wizardry, like that? lol

**Comment by amir20** [comment]
"some other wizardry" 😆

That's similar to https://github.com/amir20/dozzle/issues/2363 where you could jump to a specific part of the log. 

It's a lot of work so I haven't had a chance to work on it.

**Comment by amir20** [comment]
Closing for now.
