### ISSUE TITLE
Big spacing between the lines, multiple pages in result

### ISSUE THREAD

**Issue by Beersteddy** [amir20/dozzle#2683]
Gaps between the lines are too big splitting the main page into multiple pages for no reason

Shrinking them will allow more info to be displayed.

Large gaps marked red on the screenshot below

![image](https://github.com/amir20/dozzle/assets/91010735/a773bca3-e4cc-4964-8b7f-6cd7eb0f0977)

**Comment by amir20** [comment]
@Beersteddy The space has nothing to do with the page size. I limit the number of items on the homepage because it would kill the browser if I put too many bar charts. 

I have been trying to reduce vertical space but I won't be putting more items on the homepage.  

Related https://github.com/amir20/dozzle/issues/2575
