### ISSUE TITLE
HTTPS for front-end

### ISSUE THREAD

**Issue by netcrystals** [amir20/dozzle#2739]
I suppose that there is no HTTPS feature for the Dozzle gui available yet, is this correct? The TLS connection to remote docker dameons works perfectly, therefore I thought it would be a good idea to provide parameters for ca, certificate and key file for the Dozzle server to connect to https 443 port.

Perhaps, these parameters already exist but I couldn't find them.

**Comment by amir20** [comment]
That's right. SSL is not supported. I thought about providing flags to support TLS certs or even use letsencrypt to automatically generate them. But I get so many features about "something doesn't work" that I figured it would be outside of the scope for Dozzle. There are better options out there to proxy with SSL. Caddy and Traefik are simple solutions that provide TLS out of the box. So I don't think it's worth adding to Dozzle. Especially since getting TLS to work can be tricky and I won't have time to support these issues.
