### ISSUE TITLE
Add progress indicator when loading large log files

### ISSUE THREAD

**Issue by siandco** [amir20/dozzle#2759]
I have a number of containers log files which, over time, can grow to be quite large.
When loading these logs it can appear to that Dozzle has frozen (and Chrome does report the page as not responding).

Would it be possible to include a periodic message indicating that loading is still in progress (and if possible a (%) complete?)

**Comment by amir20** [comment]
> When loading these logs it can appear to that Dozzle has frozen (and Chrome does report the page as not responding).

Would you be able to show this with a video? Dozzle only loads the last 300 lines so theoretically, there shouldn't be any long waits even for large logs.  Dozzle calls `docker logs -f -n xxx [id]` so it should be relative fast. 


> Would it be possible to include a periodic message indicating that loading is still in progress (and if possible a (%) complete?)

This would be hard to do because Dozzle don't know the difference between no logs vs slow connection. 

I think something else is happening which is causing Dozzle to be slow. Because even for my big logs, they are fast.

**Comment by amir20** [comment]
No, update. Closing.
