### ISSUE TITLE
[Question] Filtering logs

### ISSUE THREAD

**Issue by ldrahnik** [amir20/dozzle#2792]
Hi there,
I would like ask you about your point of view about filtering logs from healthcheck spam as new project feature. I would like avoid to have logs separately if it is not necessary. That would be one solution from my point of view. Another one could be remove healtchecks from containers and keep only health / healtz endpoints for black box exporter from prometheus as monitoring tool (in my case) but I have to research whether starting order of services inside container depends on health condition or this feature was removed and is not planned anymore.

![Screenshot from 2024-02-24 19 29 54](https://github.com/amir20/dozzle/assets/3233644/8b3ccbd3-02ad-447e-8a44-d363f8dba1a6)

**Comment by amir20** [comment]
I think what you are asking is for a way to "ignore" logs? 

This would be pretty hard to do. Since the filter would have to run on all logs. 

What possible solution would be to filter out all "info" level logs like suggested in #2432. Of course that wouldn't work if all your logs are the same level or in your case they don't even have a level. 

So perhaps, removing the logs for just this use case would be easier.
