### ISSUE TITLE
Embed Dozzle main panel into another application

### ISSUE THREAD

**Issue by clabnet** [amir20/dozzle#2793]
First: Dozzle is a very fantastic application. Thank's to developer.

Then, it should possible to embed the main log panel into another web application ? 
It should useful hide the selector left panel in this case and force the view only to a single container.

Only iframe or there are any other chances ?

**Comment by amir20** [comment]
> First: Dozzle is a very fantastic application. Thank's to developer.

🎉

> Then, it should possible to embed the main log panel into another web application ?

Is it not possible right now to iframe Dozzle? Someone else asked this question and I know it's possible. What functionality is missing to be able to iframe? 

> It should useful hide the selector left panel in this case and force the view only to a single container.

That's already possible with a button on the bottom left. 

> force the view only to a single container

Technically, this is possible because you can [search by name and redirect](https://dozzle.dev/guide/faq#we-have-tools-that-uses-dozzle-when-a-new-container-is-created-how-can-i-get-a-direct-link-to-a-container-by-name). 

Possible questions I would have: 

1. Dozzle uses container id to view logs. So it might not always make sense to show a single continaer. 
2. Should it auto hide the menu? 
3. Perhaps, you want to iframe for other users to not even be allowed to search other containers? 
5. Last, what is exactly your usecase? Is this an internal tool you are trying to iframe Dozzle?

**Comment by clabnet** [comment]
Yes, i would embed Dozzle into my web app Vue 3, and I interested only to see one container log's only.

**Comment by amir20** [comment]
Oh I see. So you are saying everything is working as expected but only want to hide the menu on the left permanently? 

I'll have to see how is easy that is. Perhaps I can pass a flag like `?embedded=true`

**Comment by amir20** [comment]
Try https://github.com/amir20/dozzle/pull/2796 with `amir20/dozzle:pr-2796`. You should be able to append `?hideMenu` which would force hide the menu.

**Comment by amir20** [comment]
I will add that if you want a secure option, this won't work. People can still jump in the javascript and look at other logs. But I think that's too hard to fix.

**Comment by clabnet** [comment]
Correct assertion related security, fortunately users are not all geeks.
Dozzle version v6.2.5 it seems the hideMenu is not working (or I missed any thing) 
`http://localhost:9999/show?name=log-drawings-processor&hideMenu=true`

**Comment by amir20** [comment]
I haven't released a new build yet. Waiting for you to test it. `amir20/dozzle:master` should work.
