### ISSUE TITLE
[Feature] Environment Variable to always show stopped containers

### ISSUE THREAD

**Issue by accforgithubtest** [amir20/dozzle#2798]
Every time the browser / container is restarted, the setting for "Show Stopped Containers" is reset to false, and needs to navigate to settings to set this again.

Can there please be a environment variable that can be passed via docker compose, etc, to say
```
DOZZLE_SHOW_ALL_CONTAINERS=true
```

The UI already neatly distinguishes (lighter font) and sorts the stopped containers below running containers.
So there should not be any confusion / issues in enabling to show all containers when dozzle starts up.

**Comment by amir20** [comment]
This sounds like a bug. And introducing yet another env variable sounds like hack. 

Can you tell me more about your env: 

- Are you using authentication? 
- Dozzle by default stores everything to `localStorage`. Are you using incognito mode or something? 
- Perhaps you have something else that disable local storage. Check console to make sure there are no error.

If you do have auth, then you need to mount `/data` which should store your settings between restarts.

**Comment by accforgithubtest** [comment]
Thanks for your reply @amir20 !

Will the user settings be preserved in /data folder even if auth is not enabled (as is my case), but /data is mapped in docker compose ?

Yes, I always use incognito, so that is why the settings are lost each time I restart the browser and that makes sense.

I have been using dozzle for a while now without knowing /data folder can be mapped, until I just saw your comment above about auth and /data.

**Comment by accforgithubtest** [comment]
I just mapped the /data folder in my docker compose. Do not have auth. Using Incognito.

Changes to setting are still lost when browser is restarted.

**Comment by amir20** [comment]
You do need to have auth enabled for data folder to work because I save settings per user. Without auth, it would be disabled as it would store one setting for all users. Which is probably not expected. 

I think for you just enabling auth could be best option. You can also pass username and password with a proxy as described here. https://dozzle.dev/guide/authentication#forward-proxy

Or don't use incognito mode. But I am sure you have your reason 😆

**Comment by accforgithubtest** [comment]
Perhaps there could be a default "dozzle" user if there is no auth enabled ? And the settings could be saved in there for the default user.

(Being a single user home set-up, setting up auth for local self-hosted applications just seems needlessly complex as many applications do not have a standard approach to Authentication / User Id / Access controls.)

**Comment by amir20** [comment]
A lot of people use Dozzle behind their own proxy. If I just had a default user then it would break for multi users without auth. So because of that I require auth. 

Again you just pass user as a proxy header and enable auth. Then it would use a single user to always store settings. 

But I think that work needs to happen on your side to not break other folks.
