### ISSUE TITLE
Simple Storage

### ISSUE THREAD

**Issue by Immortalin** [amir20/dozzle#280]
Like in a SQLite db, nothing complex or dependency heavy.

**Comment by amir20** [comment]
What's your question? 

Does Dozzle support storage? No, not at the moment. I haven't seen any solutions that use little memory.

**Comment by Immortalin** [comment]
SquashFs with Zstd compression? Text compresses amazingly well and Zstandard is pretty fast.

**Comment by amir20** [comment]
@Immortalin I don't think the hard part is to store all of this data. The hard part is to have a database than can effectively index everything by time so that I can query for the UI.  That would allow offline processing and coming back to Dozzle to see previous logs. Even better, search across time or across containers. 

However, most databases that provide this functionality are pretty heavy in memory. Something that Dozzle doesn't aim to be. I have looked at Elasticsearch and InfluxDB. Each with their own limitations. 

What is your use case? If it is to go back in time, then Dozzle already has infinite scroll back functionality. 

Tell me about the use case and let's see if it really make sense for Dozzle to have a such storage implemented.

**Comment by amir20** [comment]
I'll close since this is not a bug.
