### ISSUE TITLE
Open page with Clear command activated

### ISSUE THREAD

**Issue by clabnet** [amir20/dozzle#2800]
Is it possible to open the page with a blank content ? 
In other words, as pressing CLEAR command (CTRL + SHIFT + K) ?
Thank you

**Comment by amir20** [comment]
Not possible right now, but one idea would be to add `?since={timestamp}` so that it would only fetch logs since then. Similar to `docker logs --since`

**Comment by clabnet** [comment]
It could be easy to add ?clear or similar and you add the since time internally. If you can, certainly.

**Comment by amir20** [comment]
To be honest, I don't build features that are only useful to a few people. Not many people ask for a `?clear` option. Some people have asked for `since=xxx` option since they want to integrate it in their pipelines.  

Generally speaking, every feature (no matter how small) will take some time to build and maintain. So I only build when I see lots of interest.
