### ISSUE TITLE
Lower Idle CPU usage

### ISSUE THREAD

**Issue by smolpaw** [amir20/dozzle#2829]
**Is your feature request related to a problem? Please describe.**
So before running dozzle my idle cpu usage for 15 containers was 5.5% but after running dozzle as well it rose up to 8.5%. Verified it by shutting down dozzle and it went back down to 5.5%.

**Describe the solution you'd like**
The container is running collecting metrics and logs even when there are no active connections to dozzle (not in use). Dozzle is a kind of application which is used only to debug which doesn't happen often. So all of this leads to wasted resources and metrics collection which will never get viewed.
Start collecting metrics only when the user is connected from the frontend. As for the log i believe it doesn't need to be constantly collected. Not sure.

**Describe alternatives you've considered**
Give the option to not have metrics collected at all.

**Comment by amir20** [comment]
@smolpaw this has been asked a few times and there is a lot of tradeoffs that need to be considered. See https://github.com/amir20/dozzle/issues/2774. There are two reasons to keep it as is: 

- The code would be very complicated because all the stats monitoring happens in background. If I were to disable it then I would have to write a lot more code to read it just in time
- The opposite problem also happens. If it Dozzle was to use streaming per user then it would incur 3% for EVERY USER. Which is why I moved away from that model as many people in companies are using Dozzle with more than a few people. 30% CPU for 10 users doesn't sound good either. 

I also don't want to introduce another flag because I think Dozzle should just work out of the box. So I spend a lot of time on a PR that deactivates all stats after 12 hours. You can see that PR https://github.com/amir20/dozzle/pull/2830. But the OP for  https://github.com/amir20/dozzle/issues/2774 never tested and with my limited time I didn't have any more time to spend on it. 

If you want to help out, I think it would be great to provide feedback on a solution that could work without introducing different flags. We can figure out the right parameters to deactivate Dozzle. A lot more details can be found in other issues though.

**Comment by amir20** [comment]
I have updated https://github.com/amir20/dozzle/pull/2830. It seems to work for me but needs more testing.

**Comment by zvirja** [comment]
Hi! I've finally managed to test it - works like a charm. There is a slight delay when you open it after idle time - but that could be just how my Raspberry PI works.

The only glitch I've noticed is that old data is not cleared from stats history:

![image](https://github.com/amir20/dozzle/assets/1074182/aa658a44-1d14-4716-b430-35af9f3f028e)

Pay attention to a middle point where there is a drop in memory. It's where I started it after the idle time. Ideally the previous data should be cleared, as it could be misleading. 

But apart from it - it's awesome.

Will be also cool if one could control the timeout.

**Comment by amir20** [comment]
Awesome @zvirja. Thanks for testing! 

> There is a slight delay when you open it after idle time - but that could be just how my Raspberry PI works

I am afraid that is the tradeoff now. But it should only happen the first time and any time after it should be quick. On my laptop it is pretty fast though so your RPI might be slightly slower. 

> The only glitch I've noticed is that old data is not cleared from stats history:

Nice. I didn't think of this. I'll see if I can fix it. 

> Will be also cool if one could control the timeout

This code is so complicated right now that I am going to avoid any changing variables. I am sure there will be bugs once I release. Maybe in the future I can offer SHORT, DEFAULT, LONG parameters.

**Comment by smolpaw** [comment]
> the data is still there for the last 5 minutes, which helps a lot for debugging memory issues.

I can see how that would be helpful for some people but for others who already have monitoring solutions built it's a waste. My netdata container collects 2500 metrics every second yet consumes less cpu gives much more data to debug. Not blaming the project but that's just how `docker stats` work unfortunately.

Love the project. Will test the update and report back my findings

**Comment by amir20** [comment]
This has been released now. 

@smolpaw When Dozzle first started I was resistent to add too many functionalities. But not everybody knows how to do authentication, monitoring and logging. So for me Dozzle has became a small container that gets most people 80% there. 

I think it's fair point to not use CPU and I think deactivating after some time is the best I can do. I picked 6 hours because typically if people use Dozzle in the morning then then can use it to debug in their "9 - 5pm" job. 

> that's just how docker stats work unfortunately.

Yep. Ideally, `docker stats` wouldn't require one thread and socket per container. But even running `docker stats` make CPU usage high. 

> My netdata container collects 2500 metrics every second

Does your netdata container also collect stats about each container? If so then I would be open to just removing `docker stats` in favor of something better. AFAIK, there isn't anything that exposes docker stats except their API.

**Comment by amir20** [comment]
Closing as completed.

**Comment by smolpaw** [comment]
> Does your netdata container also collect stats about each container?

It does that by default. Collects detailed metrics of cpu, mem, pids, net, disk etc for every cgroup as to say every container. Helped me track down why using restart policy of always or unless-stopped is a bad practice in production. that one container was crashing and restarting over and over again starving the node of disk iops
It's highly customizable so as to say i can limit what needs to collected and how often

**Comment by smolpaw** [comment]
I also want to add that stats collected by netdata been more helpful and accurate than any docker stats tool i have used. Think cadvisor but better. Even cadvisor doesn't collect a quarter of what netdata does for each container

**Comment by amir20** [comment]
I found lots of documentation at https://www.netdata.cloud/docker-monitoring/ but looks like integrating something like that is more work. Dozzle's current stat collector might be good enough for users.  Funny enough, even the documentations says Docker's API is too heavy for monitoring.

**Comment by zvirja** [comment]
Thank you @amir20 for your time and finally merging this change! I agree that 6 hours is indeed a good compromise, especially for cases like my VPS where I almost never open Dozzle and it's there "just in case".

Will test it more as well.

Wish you great time of a day :blush:

**Comment by smolpaw** [comment]
Hey @amir20 dozzle seems to be working great on a newer cpu.
My old stack was hosted on t3.small which has Intel Xeon Platinum 8259CL CPU.

I moved to a new vm couple days ago which is a single core Ampere Altra arm cpu on oracle.
With running 19 containers the average cpu usage is 0.3% during normal operation and 0.1% when it stops collecting metrics.

![dozzle cpu usage](https://github.com/amir20/dozzle/assets/35697471/c74ee196-d855-4136-8e14-a596276facf4)
