### ISSUE TITLE
Start and stop buttons on mobile version

### ISSUE THREAD

**Issue by paullaffitte** [amir20/dozzle#2935]
**Is your feature request related to a problem? Please describe.**
When I use dozzle on my phone, I cannot start/restart/stop containers. I have to switch to desktop mode on my browser.

**Describe the solution you'd like**
I would like to have access to the same dropdown as the desktop version in the mobile version.

**Describe alternatives you've considered**
Switch to desktop mode on my browser.

**Additional context**
Desktop
![image](https://github.com/amir20/dozzle/assets/23403270/96f9f6a0-8d55-4fe7-b09e-950245bb9125)

Mobile
![image](https://github.com/amir20/dozzle/assets/23403270/cf3d2483-3411-4e8d-a5a4-f93efa7bd33e)

**Comment by amir20** [comment]
There isn't any space on the phone. And this has been discussed a few times. I think it would be pretty hard to provide access to the menu on mobile. 

There is a workaround though. You should be able to rotate your phone. 

<img width="499" alt="Screenshot 2024-05-06 at 7 55 41 AM" src="https://github.com/amir20/dozzle/assets/260667/8f98455b-ad50-4ace-8121-5afd6e448dd0">

I think it depends on your phone but seems like most people using Dozzle can do this. 

Since there is a workaround, I am going to close. In the future, all features provided on mobile can be reevaluated. But I never got any response from folks on this effort.
