### ISSUE TITLE
Graph for Disk and network I/O

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#2989]
**Is your feature request related to a problem? Please describe.**
As we already have RAM and CPU, and i assume the impl can be very similar, add also 2 little graph for disk and network I/O to the upper bar when visualizing a container 

**Describe the solution you'd like**
add it to the upper right bar

**Comment by FrancYescO** [comment]
Space? 🤔 in my case the top bar is totally empty, also putting 2more graph will keep the 50% of the bar empty

**Comment by amir20** [comment]
This is what it looks like for me on a 15" laptop with retina. 

<img width="1202" alt="Screenshot 2024-05-28 at 2 01 10 PM" src="https://github.com/amir20/dozzle/assets/260667/a386f9b5-f6bc-471e-9529-53dee5eb8b2c">

Not saying there is no solutions, but that there is a lot of complexity involved in building something that works across different screen sizes and devices. 

I just added "swarm mode" because so many people asked for it. 

I could prioritize this if more people ask for it.  I think network monitor has been asked a few times, not so much disk.

**Comment by FrancYescO** [comment]
yup basically also you have the space for another graph, putting the image name under the container name can be an easy solution that will give a lot of free space in this bar

**Comment by amir20** [comment]
Oh man, I was looking at this and it has input AND output which makes all monitoring even more complicated. Not sure if I am going to be to this in a couple hours.

**Comment by FrancYescO** [comment]
not very elegant solution, but consider to just sum up input and output to have an initial concept if your problem is to have more measurement in the same graph

**Comment by amir20** [comment]
Hmm so I think this is more complicated than I thought. After looking at the actual data, I realized that disk and network stats are total I/O. Which means that the number is always increasing, unlike CPU/MEM which fluctuate. That means the monitoring graph might not be the best solution. Perhaps, a new type of graph or just numbers are better. 

Additionally, on mobile there is even less space which I need to rethink. 

I only have a few hours a week to work on this project and prefer to work on features that most people want. Given the level complexity and little interest, I am not going to work on this in the near future.
