### ISSUE TITLE
loadMore is inefficient and mixing logs from different containers

### ISSUE THREAD

**Issue by FrancYescO** [amir20/dozzle#2993]
**Describe the bug**
when switching to a different container and the previous loadmore request is not full filled/parsed dozzle will mix up logs from different containers

**To Reproduce**

- open logs of container1 `container1/stream` is called and realtime logs of container1 will show up
- scroll up to show more log (something that have LOT of old logs and is slow to get loaded)
- BEFORE the older log of container1 gets fully loaded, fast switch to a different container2: realtime logs of container2 will show up
- wait a bit (until the `container1/logs` xhr request gets fully fullfilled) and the logs of container1 will mix up on top of the logs of container2 (loaded from the `container2/stream` endpoint)

PS. in some of my cases the `/logs` call can be pretty big like ~40MB, repeating this (loadmore, switch container, loadmore, switch container...) will cause the tab to use like 4GB of RAM and a full freeze of the ui

**Expected behavior**
the request to load logs of container1 should be aborted when switching to another container a/o the background-loaded logs, should be cached to the right container

**Comment by amir20** [comment]
🤔 That does sound like a big bug. There are two things though: 

1. Scrolling up should only load about 300 lines. This is calculated on the fly by taking first log and last log timestamp for current page. For this I assume the logs are at consistent throughput. Is your container1 varying in logs? I think I should this needs to be tested more. The problem is that with Docker API I can't say give me logs from `date AND no more than 300 lines`. So I have to calculate this myself.  If you give me an idea of how much your test container is producing that would help. 
2. It does seem like a bug that while a `fetch` is active it will add to the new logs. I'll take a look. 

Thanks! Any other information would be helpful!

**Comment by FrancYescO** [comment]
AFAICS the issue is here https://github.com/amir20/dozzle/blob/e00af4321f6a99133250df2aba932129997c9704/assets/composable/eventStreams.ts#L193

as a fast fix you can put the reference of the ongoing fetch request and kill any ongoing request before calling /stream

**Comment by amir20** [comment]
I think I was able to fix this and also found a bug where I was loading more logs than needed which should fix the large logs. 

https://github.com/amir20/dozzle/pull/2995

Can you try `amir20/dozzle:pr-2995`?  Looked good to me while testing.

**Comment by FrancYescO** [comment]
i was able to reproduce also with amir20/dozzle:pr-2995 a few spare time, but i think these were some rare edge that we can ignore (i didn't found an exact steps to reproduce path)

about the 300lines thing i can say that in my case is still causing interface freeze, probably is due to the fact that my container is having an inconsistent behaviour about logs (it can go from 500line/second to 1line/minute easily) ... but maybe i prefer a single initial freeze-to-parse-all than a keep going up and wait for more logs to load (probably you should consider putting "300" as a value that can be adjusted in settings or something like that)

**Comment by amir20** [comment]
> i was able to reproduce also with amir20/dozzle:pr-2995 a few spare time, but i think these were some rare edge that we can ignore (i didn't found an exact steps to reproduce path)

I can think of one race condition that might cause that. I'll try to fix that. It's hard to reproduce for me though, so it's all a guess. 

> probably you should consider putting "300" as a value that can be adjusted in settings or something like that

As I was explaining earlier, the number of lines are just a suggestion as Docker API doesn't have support for fetching "before a date AND number of line". So I have to calculate on the fly.  There used to be a configuration but I removed because people were confused. So I am going to keep it hidden to reduce confusion.

**Comment by amir20** [comment]
https://github.com/amir20/dozzle/pull/2996 should fix rare edge cases.

**Comment by FrancYescO** [comment]
> As I was explaining earlier, the number of lines are just a suggestion as Docker API doesn't have support for fetching "before a date AND number of line". So I have to calculate on the fly. There used to be a configuration but I removed because people were confused. So I am going to keep it hidden to reduce confusion.

basicallly that's okay, and in general, in my cases for some containers is fetching to few logs, and for another the blob is too much large, but it's clear that this is due to the fact that is just a guess on "how much to get based on what i'm showing", in general i prefer when the blob is larger also if freezing the UI, but just for a better user experience idk if it's possible to move the log parsing (i think is the try-toparse-json and find for loglevel that slowdown) in something like a background thread to avoid locking the main presentation thread and "merge the HTML" only once the job is done

**Comment by amir20** [comment]
> i think is the try-toparse-json and find for loglevel that slowdown

That's all done in Go. :) UI does very minimal logic. For the most part it is a thin client to render. The problem is browser and rending 1000+ lines causes intense amount of work rendering spiking CPU and memory.
