### ISSUE TITLE
No line is clickable in Chrome

### ISSUE THREAD

**Issue by MarcS1975** [amir20/dozzle#3091]
**Describe the bug**
Everything on the Dozzle webpage becomes unclickable. I can still scroll but I can't click on anything. Its like I'm looking at a screen shot and I have to refresh the page or if I wait long enough it comes back.

1. Go to Dozzle URL
2. Click on anything
3. Nothing happens

**Expected behavior**
See logfile of clicked container 

**Desktop (please complete the following information):**

- OS: Windows 11
- Docker 27.0.3
- Browser & version Chrome Chrome is up to date, Version 126.0.6478.127 (Official Build) (64-bit)

- Version 'head'

**Comment by amir20** [comment]
It works for me just fine. 

I did `docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 amir20/dozzle` and every thing is smooth. 

Did it used to work for you? I am trying to figure out if something changed. 

I think I'll need more details to help.  Can you run in a new env and see if it works? 

Sorry I can't help more since I can't reproduce it.

**Comment by amir20** [comment]
Possibly related to #3085 which wasn't a Dozzle issue.

**Comment by amir20** [comment]
Haven't heard back. This doesn't like a Dozzle issue so closing.

**Comment by amir20** [comment]
Sorry. Can't help much since I can't reproduce this. It might a browser extension or something else.
