### ISSUE TITLE
Don't show "all values are hidden" in empty log lines

### ISSUE THREAD

**Issue by pothitos** [amir20/dozzle#3109]
### Describe the feature you would like to see

Hello Amir and many thanks for this cool container!

This is something minor but it can improve logs. When there's an empty line, Dozzle shows

> all values are hidden

It could instead display just a blank line instead.

### Decribe how you would like to see this feature implemented

When for example I execute

```
docker run --rm alpine sh -c 'sleep 1; echo Hello; echo; echo world; sleep 10;'
```

Dozzle displays

```
Hello
all values are hidden
world
```

instead of

```
Hello

world
```

I guess that we could change this line but I'm not sure https://github.com/amir20/dozzle/blob/749886b/assets/components/LogViewer/ComplexLogItem.vue#L29

P.S. Interestingly, if I add the `-t` parameter, Dozzle displays what I want.

```
docker run --rm -t alpine sh -c 'sleep 1; echo Hello; echo; echo world; sleep 10;'
```

```
Hello

world
```

### Describe any alternatives you've considered

This behavior was introduced in 7.0.4, so one can downgrade to an earlier version to avoid it.

**Comment by amir20** [comment]
This is one of those things where you'd think it's wanted but in practice introduces a lot of confusion. 

It used to be blank. But once in a while I would get issues where people would ask why is there a blank line. I was stumped myself until I realized there was nothing to show. 

So IMO the right UX here is to avoid confusion by providing some indication there is nothing to show vs really a blank line. 

I'll like to avoid issues being opened due to user confusion as much as possible. I get a lot of them. 🥲

**Comment by pothitos** [comment]
Thanks for your feedback, Amir! If this is indeed intended then, let's close this issue. It was something minor anyway 😉

Have a nice rest of vacations!
