### ISSUE TITLE
CPU percentage

### ISSUE THREAD

**Issue by Mephisto090** [amir20/dozzle#3134]
Hi

It would also be great to have a setting to show the CPU percentage as 400% or 100% for 4 CPUs. It is sometimes a bit confusing when you have 120% utilization, but that is not so bad

![image](https://github.com/user-attachments/assets/d9a3eec0-3311-4801-bc5b-9fb32fe3daa6)

somehow the progress bar only has 100%. This should be designed for 400% and also display with the setting at 100% or max in our example 400%

**Comment by amir20** [comment]
I am not understanding this question.  Are you saying at 4 cores it should be max 400%? 

It used to be like that, but that led to a lot of confusion. See https://github.com/amir20/dozzle/issues/2944#issuecomment-2106040112 Majority of users have CPU less than 100% so it led to a lot of confusion with folks with 16 cores to see a very little bar. 

I don't know of a better solution. Open to suggestions.

**Comment by amir20** [comment]
I am very familiar with ctop. I actually collaborated with the author a little bit. Sadly, ctop hasn't been updated in a very long time and breaks on my arm64 laptop. 

In Dozzle, memory works identical to ctop and `docker stats`. Docker reports a % which is `memory used / memory limit`. For your 100M containers, you should see the % reported correctly. 

For CPU, Docker just reports CPU used. There is no limit that I am aware of.  I would have to calculate number of cores myself and show a smaller progress bar. 

As I said before, it used to be like that. But since the majority of people use less than 100%, it led to a lot of confusion. 

Even in your screenshot, it would be confusing. If CPU goes to 10% and I only show 1% on a 10 core machine, it is confusing. 

Going to close this since I don't think there is a better solution. 

There is another open issue #3128 which would show total configured memory. That would bring the UI closer to docker `stats` and `ctop`.
