### ISSUE TITLE
Search all logs for string

### ISSUE THREAD

**Issue by DaveTSG** [amir20/dozzle#3163]
### Describe the feature you would like to see

It would be great if there was the option to search every log file within Dozzle (across all containers) for a string. That way, I could search, for example, for "error", and it'd show me every container with an error. As a bonus, it would also be great if there was a new column shown in the main Dozzle page "time since last error". Thank you for considering.

### Describe how you would like to see this feature implemented

1. Search bar at the top of the Dozzle main page.
2. Column as described in the Dozzle main page.

**Comment by amir20** [comment]
This isn't possible to search across _ALL_ containers because it would a performance issue. The search is done in the browser so Dozzle would have to fetch every single container logs and search across that. 

However, as of the most recent version, you could use `swarm view` or `merged logs` to search across multiple streams. You could even search across _ALL RUNNING CONTAINERS_ which is basically what you are asking. It just wouldn't search historical logs because they wouldn't fit in the browser.

**Comment by amir20** [comment]
I guess the real ask in this feature would be to search across historical logs. This has been asked a few times and it would be difficult to do without a proper database. I don't plan to work on it.

**Comment by DaveTSG** [comment]
> I guess the real ask in this feature would be to search across historical logs. This has been asked a few times and it would be difficult to do without a proper database. I don't plan to work on it.

I suppose it depends on the definition of "historical logs". I was only thinking e.g. the last 5 minutes or so.

In any case, I understand why you're not going to include this feature. Thank you for responding.
