### ISSUE TITLE
Strange characters appear in the logs of exported Java programs

### ISSUE THREAD

**Issue by hausen1012** [amir20/dozzle#3182]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

latest

### ✅ Command used to run Dozzle

docker run -d \
--name dozzle \
-v /var/run/docker.sock:/var/run/docker.sock \
-p 9999:8080 \
--restart always \
amir20/dozzle

### 🐛 Describe the bug / provide steps to reproduce it

java   springboot   program

### 💻 Environment

-

### 📸 If applicable, add screenshots to help explain your bug

![image](https://github.com/user-attachments/assets/c2080f3f-d21a-4e2f-bce6-5db566e6ede4)

**Comment by hausen1012** [comment]
> 您是否启用了交互模式或 tty？

No, I downloaded the logs directly.
By the way, can I change the time zone displayed in the log?

**Comment by amir20** [comment]
> No, I downloaded the logs directly.

You didn't answer my question.  Are you using `--tty` or `--interactive` for this container? 

I stream logs directly from Docker so this isn't a Dozzle bug. Sometimes in interactive mode, applications have colors which would show as those escaped logs. 

I am guessing `docker log` is similar. 

> By the way, can I change the time zone displayed in the log?

Not in downloaded logs. Dozzle doesn't transform any logs for downloading. 

The UI uses your browsers timezone. 

Closing for now because there isn't anything to fix.
