### ISSUE TITLE
Add filter support to `users.yml` file

### ISSUE THREAD

**Issue by shariquealavi** [amir20/dozzle#3187]
### Describe the feature you would like to see

It would be a nice to have feature to have a filter support added to the `users.yml` file ... This way we would be able to create multiple users with different filters applied to their dozzle views. Easily allowing a simple yet powerful ACL like functionality.

What do you think about it?

### Describe how you would like to see this feature implemented

Just add a filter support to the `users.yml` file code and apply the filter fetching this info from the `users.yml` file upon login.

### Describe any alternatives you've considered

None yet

**Comment by amir20** [comment]
I think this makes sense. It would be significant amount of work though to implement this. So I wouldn't want to do it unless there is at least a bit of interest from few folks. 

Perhaps the implementation could be similar how `--filter` is implemented. The tricky part is that the filter is sent to Docker right now, so to implement such filter, a new client would need to be created per user. Which is why I think it would be a lot of work. 

Maybe there is a better way. Open to PRs from anybody who might be interested to work on this. @shariquealavi would you?

**Comment by shariquealavi** [comment]
I need to get a hold of the code. Will then try to push something as a PR.

**Comment by amir20** [comment]
If you can get Dozzle running locally, I can help with the rest. Maybe we should figure out where the changes might be. 

A really simple change is to do it https://github.com/amir20/dozzle/blob/ffc4559047f52a8e0ac3f31cf30ecdc24be1c293/internal/web/logs.go#L203 but there is a few places that code is called so I guess you would have to find a better place to do it. 

I won't have time to work on this for a while.

**Comment by amir20** [comment]
@shariquealavi Were you able to get anywhere with this?

**Comment by shariquealavi** [comment]
@amir20 Not yet, will keep you posted INSHALLAH.

**Comment by amir20** [comment]
Closing this as I don't plan to work on it and not many people have requested it. Feel free to send PRs. But out of scope for me personally.

**Comment by amir20** [comment]
This is now implemented. Thanks for trying.

**Comment by shariquealavi** [comment]
That's such awesome news :). Thank you so much.

Apologies that I couldn't get to implement ... Tried looking into the code
but couldn't get time to make changes ...
