### ISSUE TITLE
"all values are hidden" replacing non empty lines

### ISSUE THREAD

**Issue by omasseau** [amir20/dozzle#3297]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v7.0.7

### ✅ Command used to run Dozzle

```
  # Dozzle
  bdoc-gateway-logs:
    image: amir20/dozzle:v7.0.7
    restart: unless-stopped
    deploy:
      resources:
        limits:
          # strict minimum required: 10m
          memory: 25m
    networks:
      gateway_internal_network:
        # if an ip address is not explicitly defined, docker will attribute to the container an available ip from the defined subnet
        ipv4_address: ${DOZZLE__DOCKER_SUBNET_IP:-}
    ports:
      - '${DOZZLE__HTTP_PORT:-9999}:8080'
    logging:
      # logging options
      driver: "json-file"
      options:
        max-file: "25"
        max-size: "10m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOZZLE_BASE=/logs
      - DOZZLE_NO_ANALYTICS=true
```

### 🐛 Describe the bug / provide steps to reproduce it

Sometimes, Dozzle wrongly replaces the content of some lines with "all values are hidden".

Here is a concrete example :

The content of the logs :
```
2024-09-30T13:00:58.162459442Z Replaced 18 variables in file /usr/local/openresty/nginx/conf/app-specific/http/2-upstreams.conf
2024-09-30T13:00:58.162463169Z 
2024-09-30T13:00:58.162466431Z Replacing variables in file /usr/local/openresty/nginx/conf/app-specific/http/1-variables.conf ...
2024-09-30T13:00:58.162470035Z Replaced 0 variables in file /usr/local/openresty/nginx/conf/app-specific/http/1-variables.conf
2024-09-30T13:00:58.162473691Z 
2024-09-30T13:00:58.204334523Z Replacing variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/2-app-locations.conf ...
2024-09-30T13:00:58.204357942Z Replaced 0 variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/2-app-locations.conf
2024-09-30T13:00:58.204368835Z 
2024-09-30T13:00:58.204371234Z Replacing variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/1-variables.conf ...
2024-09-30T13:00:58.204373658Z     Replacing ${PROXY__WEB_DESIGN_IIS_PATH} with : webdesign
2024-09-30T13:00:58.204389119Z     Replacing ${PROXY__INTERACTIVE_IS_MULTITENANT} with : false
2024-09-30T13:00:58.204392738Z     Replacing ${PROXY__INTERACTIVE_DEFAULT_TENANT} with : ''
2024-09-30T13:00:58.204395074Z     Replacing ${PROXY__INTERACTIVE_PATH} with : interactive
2024-09-30T13:00:58.204397326Z     Replacing ${PROXY__USE_IIS_FOR_WEB_DESIGN} with : false
2024-09-30T13:00:58.204399695Z Replaced 5 variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/1-variables.conf
```

The output of Dozzle: 
```
Replaced 18 variables in file /usr/local/openresty/nginx/conf/app-specific/http/2-upstreams.conf

    all values are hidden

Replacing variables in file /usr/local/openresty/nginx/conf/app-specific/http/1-variables.conf ...
Replaced 0 variables in file /usr/local/openresty/nginx/conf/app-specific/http/1-variables.conf

    all values are hidden

    Replacing ${PROXY__WEB_DESIGN_IIS_PATH} with : webdesign
    Replacing ${PROXY__INTERACTIVE_IS_MULTITENANT} with : false
    Replacing ${PROXY__INTERACTIVE_DEFAULT_TENANT} with : ''
    Replacing ${PROXY__INTERACTIVE_PATH} with : interactive
    Replacing ${PROXY__USE_IIS_FOR_WEB_DESIGN} with : false
Replaced 5 variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/1-variables.conf
```

![image](https://github.com/user-attachments/assets/0ec7942f-afa5-4e6c-ac04-f8be68ab1c80)

As you can see this line is missing :
`Replacing variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/1-variables.conf ...`

### 💻 Environment

Version:    24.0.7

**Comment by amir20** [comment]
@omasseau you have a very old version. Always update before opening bugs. 

For this particular bug, I don't think there is much too fix. The lines are blank so Dozzle things it's all hidden. I think the fix would be easy but it's not critical for me to fix it right now.

**Comment by amir20** [comment]
> Replacing variables in file /usr/local/openresty/nginx/conf/app-specific/server/default/1-variables.conf ...

Oh wait. I misunderstood that. Let me see if I can reproduce this. I didn't think this could happen.

**Comment by amir20** [comment]
Hmmm. I can't reproduce this. The lines that say "all values are hidden" are actually blank lines, which is expected. Nevertheless, it's still a bug, though not critical.

**Comment by dodgex** [comment]
I was about to open an issue for exactly this but as this (and another one) already exist, I decided to give my feedback here.

To reproduce this, you can `exec` into any container and run `echo "" | tee /proc/1/fd/1`. this writes a blank line to the stdout (`fd/1`) of the container process (`proc/1` assuming the main pid is `1`) and thus into the logs.

I stumbled across this issue after (finally) installing dozzle on my raspberry where I have some containers running periodic task and seperating the outputs by some blank lines. I was extremely confused when seeing `all values are hidden`. While I understand your argument that it is [better UX to provide an indication instead of a real blank line](https://github.com/amir20/dozzle/issues/3109#issuecomment-2226937363), maybe it would be even better UX to have a similar output with `blank line` instead?

I tried to dig myself into the code to provide a PR, but unfortunately it seems, that building on windows is not supported and I currently have no linux based dev environment available.

**Comment by amir20** [comment]
@dodgex that is a different bug. This issue `["all values are hidden" replacing non empty lines]` was suggesting that I replace non-empty lines.  Which I don't think it is true. 

This reason this bug is happening is because Dozzle thinks an empty line is actually a JSON log with all fields empty. It's a pretty easy fix, just not on my priority. 

> I tried to dig myself into the code to provide a PR, but unfortunately it seems, that building on windows is not supported and I currently have no linux based dev environment available.

Is this true? The build mostly happen in Docker so it should theoretically work.
