### ISSUE TITLE
Log persistence

### ISSUE THREAD

**Issue by idan-h** [amir20/dozzle#3355]
### Describe the feature you would like to see

First, I love this project!
Second, I would love it if there would be a simple way to setup persistence, and see logs from the past.
Like mounting a volume that persists the logs, so you could see container logs after they have restarted.

Would something like this be possible? Are there any alternatives to that?

**Comment by amir20** [comment]
Hi @idan-h,

Thanks for the ❤️

We've discussed this several times. Unfortunately, persisting logs is quite complicated. I don't plan to implement it myself due to time constraints. More importantly, I don't believe Dozzle needs to be that complex. For me, Dozzle's primary purpose is to debug real-time logs, which I rely on heavily through the Docker API. If it were to be implemented, it could be part of a larger platform that includes a database.

If I had more time, I think Dozzle could integrate with [quickwit](https://quickwit.io/docs/log-management/send-logs/send-docker-logs). However, setting up logging to a database is a challenging task that would undermine Dozzle's simplicity.

Since this is a free project, I won't be pursuing it. There were discussions about adding this feature as a paid option, but I don't think enough people would pay for it to make it worthwhile.

**Comment by idan-h** [comment]
I got you - honestly I didn't look at the code, so I am not sure what is the internal implementation, but conceptually it could be quite simple -
If the app is built on top of abstractions, then change the log source to be some other source (that would have to implement a certain contract) and then other service could be responsible for the logging, while this will be mainly the front end.

Another option, is use even existing logging libraries and just persist to some file - and load the file contents together with the current log stream.

Ofcourse almost every new feature adds some complexity, but it does not have to be too much - depends on implementation.

I will take look at quickwit, and anyway thanks for this awesome project :)

**Comment by amir20** [comment]
I think we have different opinions on "complexity." 🤣 Everything you described would take me a few weeks to complete since I don't work on it full-time. There is actually a lot of abstraction in place. The Docker API is already abstracted in this file: https://github.com/amir20/dozzle/blob/master/internal/docker/client.go.

However, the issue is that there are many edge cases to consider. Supporting pagination, searching, scroll back, live streams, and filtering by various options requires significant effort. That's why I wouldn't take it on.

If you could get something like Quickwit to work and then provide a PR that reads from Quickwit instead of the Docker API, I would be open to that. Just a heads-up: that’s likely a lot of work, and a few people have tried and given up in the past.
