### ISSUE TITLE
dozzle healthcheck inaccurate on server/agent setup

### ISSUE THREAD

**Issue by m-shaffer** [amir20/dozzle#3358]
### Describe the feature you would like to see

When using `DOZZLE_REMOTE_AGENT` if a remote agent is down the healthcheck fails if an agent is inaccessible. The fact that the healthcheck fails if used as a container healthcheck the container will be in an unhealthy state on the basis of a remote agent being missing, which shouldn't be a failure state.

```
# docker compose exec dozzle /dozzle healthcheck
{"level":"info","url":"http://localhost:8080/healthcheck","time":"2024-10-29T04:52:28Z","message":"performing healthcheck"}
{"level":"fatal","error":"healthcheck failed with status code 500","time":"2024-10-29T04:52:28Z","message":"Failed to make request"}
```

### Describe how you would like to see this feature implemented

I don't think the healthcheck should fail if remote agents are inaccessible, or there should be a different healthcheck endpoint / argument that can be used to tolerate remote agent failures.

### Describe any alternatives you've considered

A different healthcheck could be manually written via curl or similar.

**Comment by amir20** [comment]
@m-shaffer The health check code is located at https://github.com/amir20/dozzle/blob/master/internal/web/healthcheck.go.

It's been a while since I last reviewed it, but if I recall correctly, I attempt to fetch all containers. If any node fails, the health check fails.

What do you propose as an alternative solution? Currently, there is no way to determine if it's a remote agent, so it's an all-or-nothing situation.

Here are some ideas:

1. Only fail if the local connection fails. But what should we do if there is no local connection?
2. Ignore all agents since they reconnect, while remote connections do not. I believe this is what you suggested. However, it may require more effort to identify what is failing.
3. Only fail if all connections fail. For example, if there are three connections and all three fail, then the health check should fail.

What do you think? I like the idea of option 2, but it does involve more work.

**Comment by m-shaffer** [comment]
With option 2, identified what failed can be done manually, it says they are offline in the interface.

Beyond that adding something like a prometheus metrics endpoint would be ideal for monitoring the state of agents.

Maybe reducing the log of the agent responses to a warning would be ok.

Lastly if you like the healthcheck doing what its doing, a solution would be to implement an additional endpoint such as healthz, which performs a different check specifically that the web interface is fuctional regardless.

**Comment by amir20** [comment]
> With option 2, identified what failed can be done manually, it says they are offline in the interface.

The more I think about this issue, I think it's better to disable agents in healtcheck by default.  As you said, agents reconnect and it wouldn't make sense for the UI to fail. 

> Lastly if you like the healthcheck doing what its doing, a solution would be to implement an additional endpoint such as healthz, which performs a different check specifically that the web interface is fuctional regardless.

With that idea, I can introduce parameters to the `healthcheck` command so that one could do `dozzle healthcheck --include agent,local,remote` and have include by default be `local.remote`. `agent`s have their own healthcheck so it would make sense. 

> Beyond that adding something like a prometheus metrics endpoint would be ideal for monitoring the state of agents.

I'll never do this because I don't use prometheus for my projects. But could be a PR if someone wants to add it. 

I won't get to this for a while though. So if you can help with a PR it would be great. 🙏

**Comment by amir20** [comment]
Merged a PR that only checks non-agents for healthcheck. It's in `master`.  I don't think I'll do the other stuff discussed in this issue because I don't have time.
