### ISSUE TITLE
part of the logs are not displayed correctly when scrolling up

### ISSUE THREAD

**Issue by kkuryshev** [amir20/dozzle#3373]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.7.2

### ✅ Command used to run Dozzle

-

### 🐛 Describe the bug / provide steps to reproduce it

1. selected host
2. selected container
3. scrolled logs up but didn't find some logs as expected by source code.
4. found that logs via dozzle search
5. found all excepted logs via docker logs 

so, some of the logs are not displayed in dozzle but they can be found in it

### 💻 Environment

`docker system info
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose`

### 📸 If applicable, add screenshots to help explain your bug

This screenshot with log how it shows in dozzle
<img width="1513" alt="Снимок экрана 2024-11-06 в 12 51 59" src="https://github.com/user-attachments/assets/77ec6665-0115-4559-8c82-569ee33a6b2d">

This are search results
<img width="1181" alt="Снимок экрана 2024-11-06 в 12 53 49" src="https://github.com/user-attachments/assets/268729eb-7c2a-4320-979c-82b8c8b2f7a0">

And this how logs shows via raw docker logs
![1](https://github.com/user-attachments/assets/a170c92a-1c9f-4e96-ad9e-b7e06947a66a)

**Comment by amir20** [comment]
Dozzle isn't filtering or removing any logs. Can't really think of a reason why this would be happening. 

Can you paste the raw logs? I can test it locally to see if something is happening. But I need the actual logs.

**Comment by kkuryshev** [comment]
Thanks for the quick reply! 
Here are raw logs of the container
[logs.zip](https://github.com/user-attachments/files/17655998/logs.zip)

Unfortunately, dozzle logs already erased. But they are like this one (I checked yesterday). I forgot enable debug mode.

2024-11-07T04:21:11Z INF Connected to Docker | clients=6
2024-11-07T04:21:11Z INF Accepting connections on :8080 
2024-11-07T04:21:20Z INF shutting down gracefully, press Ctrl+C again to force 
2024-11-07T04:21:34Z INF Dozzle version v8.7.2 
2024-11-07T04:21:34Z INF Consider using Dozzle's remote agent to manage remote hosts. See https://dozzle.dev/guide/agent for more information 
2024-11-07T04:21:34Z INF Adding remote host | host={"name":"s***","id":"tcp:***:2375","nCPU":0,"memTotal":0,"endpoint":"tcp://***:2375","dockerVersion":"","type":"","available":false}
2024-11-07T04:21:34Z INF Adding remote host | host={"name":"p**","id":"tcp:***:2375","nCPU":0,"memTotal":0,"endpoint":"tcp://***:2375","dockerVersion":"","type":"","available":false}
2024-11-07T04:21:34Z INF Adding remote host | host={"name":"m**","id":"tcp:***:2375","nCPU":0,"memTotal":0,"endpoint":"tcp://***:2375","dockerVersion":"","type":"","available":false}
2024-11-07T04:21:34Z INF Adding remote host | host={"name":"f**","id":"tcp:***:2375","nCPU":0,"memTotal":0,"endpoint":"tcp://***:2375","dockerVersion":"","type":"","available":false}
2024-11-07T04:21:34Z INF Adding remote host | host={"name":"i**","id":"tcp:***:2375","nCPU":0,"memTotal":0,"endpoint":"tcp://***:2375","dockerVersion":"","type":"","available":false}
2024-11-07T04:21:35Z INF Connected to Docker | clients=6
2024-11-07T04:21:35Z INF Accepting connections on :8080 

I'll turn on debug mode now and watch for a similar situation...

**Comment by amir20** [comment]
Thanks for the details. Attaching the logs helped. I was able to reproduce it. 🚀

Now I just have to figure out what is going on... Nothing obvious is going on right now.

**Comment by amir20** [comment]
My mind is blown. I was able to cut the log to 100 lines and it is consistently not showing up right. Something is wrong. So much going on though that I won't have time to investigate for a while.

**Comment by kkuryshev** [comment]
I hope a solution will be found. Dozzle is cool!

**Comment by amir20** [comment]
OK, I think I understand what's happening. It's not necessarily a bug, but it is confusing. It took me a while to figure this out. Are you seeing this issue when scrolling up? 

The stack traces in the logs are so long that they get cut off in the middle when paginating up. For example, one of your stack traces has 75 lines, while Dozzle paginates every 100 lines. Increasing this number would help, but it wouldn't completely resolve the issue, as a pagination split can occur anywhere in the logs while scrolling up. 

This is a known issue, although it hasn't been reported by anyone else. 

1. Can you confirm that this happens when you scroll up? 
2. I don't have a good solution. Paginating up relies on parsing timestamps and trying to go back in time, which doesn't work well, especially in cases where 70+ lines are printed at the exact same millisecond. 
3. One idea could be for Dozzle to group stack traces together, but that would require a lot of work.

**Comment by kkuryshev** [comment]
Yes, this behavior occurs when scrolling up. 

Am I right in understanding that pagination is only for display purposes and does not affect other features of the app? So the search works correctly and finds lines that are not displayed in normal mode? By the way, I couldn't find future to go from search results to a line in the source log. This can be handy when you need to look at the logs around what you found.

Part of the log item can be output as a separate message (possibly with some tag). This is better than not outputting anything. The page size (100 lines) can also be moved to environment variables as a temporary solution?

**Comment by amir20** [comment]
> Am I correct in understanding that pagination is only for display purposes and does not affect other features of the app?

Yes, just to clarify. Let's say there are three logs with timestamps T1, T2, and T3. T1 and T3 each have one line, while T2 has 100 lines. Docker sees this as 102 lines of logs, each with its own timestamp. However, all logs belonging to T2 will have the same timestamp. When I scroll up, I use the timestamp to load more logs. Since there are 100 logs with the same timestamp, pagination breaks.

I hope that makes sense!

> So, does the search work correctly and find lines that are not displayed in normal mode?

Yes, everything else should function properly. If the logs above were viewed in "live" mode, it should also work. Downloading, searching, and everything else should function as expected.

> By the way, I couldn't find a way to go from search results to a line in the source log. This feature would be helpful when you need to look at the logs surrounding what you found.

This feature used to exist when the search was performed in the browser. However, I recently moved it to the backend, making it difficult to show a log within context. The browser reloads the logs when the search stops. Interestingly, if the search had remained in the browser, it would have broken for you due to this bug. :)

> Part of the log item could be output as a separate message (possibly with a tag). This would be better than not outputting anything at all. The page size (100 lines) could also be moved to environment variables as a temporary solution.

I don't think that's the right approach. I make certain assumptions about the page size for performance reasons. Changing these numbers might slow down Dozzle or increase memory consumption.

**Comment by amir20** [comment]
Right now, there isn't a lot I can do to fix this bug. But let's keep it open. I think one idea would be to use another approach to paginate.

**Comment by amir20** [comment]
I think I found a nice fix by looking specifically for the last log on the page. @kkuryshev can you try `amir20/dozzle:pr-3377` when you get a chance? 

I haven't tested it a lot but I took your logs and seems like scrolling up worked perfectly.

**Comment by kkuryshev** [comment]
I checked and everything works correctly!
