### ISSUE TITLE
Feature to add Slack Webhook on Error

### ISSUE THREAD

**Issue by SUJAN-DSPL** [amir20/dozzle#3437]
### Describe the feature you would like to see

Could you create a page for notification channels where we will enter a webhook URL, and the error message will be forwarded to the particular channel?

**Comment by amir20** [comment]
Creating a page is not the hard part. Processing the logs in the background is not currently supported by Dozzle. Dozzle needs a way to monitor all logs across all containers and send messages to a webhook based on a filter. This feature is not implemented, and I do not plan to implement it because it would become unnecessarily complicated.
