### ISSUE TITLE
container authorization based on users or groups

### ISSUE THREAD

**Issue by Tassleh0ff** [amir20/dozzle#3439]
### Describe the feature you would like to see

Hi, first of all let me thank you for this fantastic project.

Recently I used it in a project for a no profit linux user group in my town, to let some users access their containers logs without any access on the Docker host OS console.

Those users had to access only some containers, so I used DOZZLE_FILTER env variable to let them see only their containers, and that's ok.

But what if other users need to access other container logs hosted on the same server, and they should not see the containers I previously mentioned?

In other words I think it would be very helpful if filters would be also implemented at user level, for example adding a --filter option during the user definition process working exactly as the DOZZLE_FILTER env variable, but at a user level instead of the whole Dozzle instance level.

In the future if you'll decide to add user groups, it would be helpful to have the same filter feature at a group level, so permissions would be define only at group level and inherited by the users members of the group.

Thank you for considering my suggestion.

### Describe how you would like to see this feature implemented

**Filters at user level**
During the user creation add a new option to define filters for that specific user we're about to create.

For example:
`docker run amir20/dozzle generate admin --password password --email test@email.net --name "John Doe" --filter "label=color" > users.yml`

or 

`docker run amir20/dozzle generate admin --password password --email test@email.net --name "John Doe" --filter "name=demo*" > users.yml`

**Filters at groups level**
1. Add users
`docker run amir20/dozzle generate admin --password password --email test@email.net --name "John Doe" > users.yml`
2. Create a group with an option to define filters for the specific group and users members.
`docker run amir20/dozzle generate-group admins --members "admin,manager,customer"--name "Administrators group" --filter "label=color" > groups.yml` 
or
`docker run amir20/dozzle generate-group admins --members "admin,manager,customer"--name "Administrators group" --filter "name=demo*" > groups.yml` 
3. Apply group defined filters to users which are members of that specific group

### Describe any alternatives you've considered

I have considered running several Dozzle instances for each group of containers, each of them with specific users and specific filters, but:

1. how does Docker will deal with several concurrent actions (start, stop, restart) triggered by several Dozzle instances at the same time?
2. in case of several Dozzle instances (maybe mounting /var/run/docker.sock in read only mode inside the container) it would be very inefficient to run them only as a workaround, instead to implement an authorization layer based on filters.

**Comment by amir20** [comment]
Thanks for the write up. I like the section of how this might work. 

> Recently I used it in a project for a no profit linux user group in my town, to let some users access their containers logs without any access on the Docker host OS console.

This sounds like an awesome project. :) 

> In other words I think it would be very helpful if filters would be also implemented at user level, for example adding a --filter option during the user definition process working exactly as the DOZZLE_FILTER env variable, but at a user level instead of the whole Dozzle instance level.

I think this would be a great addition to Dozzle. There is probably about half a dozen similar issues to this. While looking at it, it was pretty complicated because the `--filter` flag is passed all the way to the Docker client. So I think it would be complicated to have a specific Docker client for every user. There is a bit of refactoring that can be done to support this though. 

A few people offered to help, but then I never heard back so it didn't go any where. I don't think I have the time to implement this feature.  Also, what happens if Dozzle is configured with a filter and a user with their own filter? I can't merge the two because one would replace the other. So I think it's actually a little thinking about what Dozzle should do in this case. 

> how does Docker will deal with several concurrent actions (start, stop, restart) triggered by several Dozzle instances at the same time?

I think this should work. It would be confusing if a user starts it while another is stopping it. But your users would have to be aware of that. 

> in case of several Dozzle instances (maybe mounting /var/run/docker.sock in read only mode inside the container) it would be very inefficient to run them only as a workaround, instead to implement an authorization layer based on filters

Just to be clear, `docker.sock` in read only mode doesn't do anything. Read only mode doesn't protect the API. 


Given that many people want a full feature user authorization with groups, I think it would make sense to be implemented.  I don't have time this year to work on it. But I will leave it open. If you or someone else gets to it then that would be great. If I get time, I can revisit.  

This project has gotten so much attention that another idea might be I will charge for this features that people want and call it an "enterprise" version. I don't get a lot of donations so it's hard when this competes with my paying job. 😄

**Comment by amir20** [comment]
Code has been abstracted in https://github.com/amir20/dozzle/pull/3455 so that filters can be different per client. Once complete, I can add support for per user.

**Comment by amir20** [comment]
This is now implemented in #3456. Can you test it?  You should be able to add `filter: name=foo` to `users.yml`. I haven't merged it yet but I will after documentation.

**Comment by Tassleh0ff** [comment]
Wow man! I did not expect it to be so fast!
Sorry for not have been able to test it sooner but I was away for work.

I test it right now and it works perfectly!

Thanks!
