### ISSUE TITLE
When entering Dozzle through a /group/foobar URL, the "SWARM MODE" slider is not automatically flipped.

### ISSUE THREAD

**Issue by skyscooby** [amir20/dozzle#3467]
### 🔍 Check for existing issues

- [X] Completed

### How is Dozzle deployed?

Standalone Deployment

### 📦 Dozzle version

v8.9.0

### ✅ Command used to run Dozzle

NA

### 🐛 Describe the bug / provide steps to reproduce it

Added a custom tag `foobar` to all my containers in order to deal with rejection of #3458 and get them all onto the same stream. And now when I visit the /group/foobar URL directly (a link to which I have embedded into a developer dashboard), the page loads to the host view and not the very confusing "SWARM MODE" view.. 

Why do we need this SWARM MODE view at all.. why can't the custom groups just show up in the nav tree like everything else...

### 💻 Environment

NA

### 📜 If applicable, attach your Dozzle logs. You many need to enable debug mode. See https://dozzle.dev/guide/debugging.

NA

**Comment by amir20** [comment]
> the page loads to the host view and not the very confusing

That sounds like a bug.  I thought it was fixed. 

> Why do we need this SWARM MODE view at all.. why can't the custom groups just show up in the nav tree like everything else...

It may not be clear. Host mode displays containers relative to their host, while swarm mode does not show containers. Instead, it shows services and stacks _only_. The custom grouping uses the same logic as services, which is why it is included in swarm mode.

💡 A better idea might be to have custom groups in both modes. In host mode, all containers would be grouped together, while in swarm mode, there would be just one service.

If you can send a PR that would be awesome. Otherwise, I think this is going to be done when ever I get it to it.

**Comment by amir20** [comment]
Oh that's right, now I remember. The reason it's only on swarm mode is because custom labels can show containers across multiple hosts. Swarm mode is about showing containers across swarm, remote and agents all in one view. 

It would have to be clear that custom groups are only containers under the specific host.

**Comment by skyscooby** [comment]
How about a 'Clusters and Groups' section at the top, where the Swarm slider is now, that is conditionally shown based on the same logic the slider is now, but without having to flip to a different view.. It could have a small (?) icon when hovered over shows a note that "items listed here may include containers that span multiple hosts"

**Comment by amir20** [comment]
https://github.com/amir20/dozzle/pull/3470 fixes the toggle not being set correctly on page load.

**Comment by amir20** [comment]
> How about a 'Clusters and Groups' section at the top, where the Swarm slider is now

Then that would look like 

```
Clusters and Groups
  custom-group-1
    - container 1
    - container 2
  compose-group-1
    - container 1
    - container 2 

Running Containers 
  - container a
  - container b
```

That adds too much vertical space for no added value. I am trying to minimize vertical space as many have pointed out. 

Seems like I could just do

```
custom-group-1
  - container 1
  - container 2

compose-group-1
  - container 1
  - container 2 

Running Containers 
  - container a
  - container b
```

Having customer groups in host menu is more complicated because it trickles all the way to the backend where new containers with the same label on the same host are automatically added to the log view when started.

**Comment by amir20** [comment]
Try `amir20/dozzle:master`. I haven't spent a lot of time making swarm menu intuitive. There is some room for improvement there for sure.

**Comment by skyscooby** [comment]
I trust your judgement as I have not yet experienced multi host or swarm use case... I'll have to spin up a few VM's to see the full spectacle.

I do know however that if someone has invested time in creating custom groups then those are the things they are interested in most and it would make sense not to have to do an extra step to see them, they should be front and center.

**Comment by amir20** [comment]
> I do know however that if someone has invested time in creating custom groups then those are the things they are interested in most and it would make sense not to have to do an extra step to see them, they should be front and center

I agree. I think custom labels should be shown in host menu. Right now I am thinking, `/group/foobar?host=foo` and then on the very top it would say `3 containers on this host`. Or just `3 container` with (i) as you suggested. Not sure what makes sense. Maybe even do nothing until someone complains :)

**Comment by skyscooby** [comment]
Also I think that follows what has already been done for compose stacks?.. because in your example above you show compose-group-1 under Clusters and Groups but infact in single host mode today compose-groups do not show up on the swarm mode tab... mine only show on the host tab.

**Comment by skyscooby** [comment]
It's almost like the Swarm Mode slider should be changed to Multi-Host Mode.. and only used when multiple hosts/dockerd instances(agents) are detected.

**Comment by amir20** [comment]
> It's almost like the Swarm Mode slider should be changed to Multi-Host Mode.. and only used when multiple hosts/dockerd instances(agents) are detected.

No, because if you look at swarm mode, it doesn't show containers; it shows services. That's the whole point: services are irrelevant to where they run. You are correct that it could be labeled multi-host, but swarm mode can also operate on a single host with multiple replicated services. So that argument doesn't hold.

You can think of it this way: `docker compose logs` and `docker logs` are host-specific, while `docker stack logs` and `docker service logs` are host-agnostic. Those commands don't care where the containers are running. To use them, you must enable swarm with `docker swarm init`, which is why I believe it makes sense to call it "Swarm Mode."

What do you think?

**Comment by skyscooby** [comment]
Ah ok gotcha.. so In my case the compose stack is only showing in the Host tab because I have no replicas setup for any of the services.. They are all single instance services. To be honest I don't use docker swarm, when I need to orchestrate I go to minikube or kubernetes because that effort is then 95% cloud portable.

I'm just trying to find the happy medium between using docker as a developer vs using some of it's fancy orchestration stuff.. I'd honestly be reserving that stuff for your Enterprise Edition ;)..

So perhaps then show custom groups on the host page when there is only one replica or member in any given service, if replicas > 1 then use the current logic?

**Comment by amir20** [comment]
> So perhaps then show custom groups on the host page when there is only one replica or member in any given service, if replicas > 1 then use the current logic? Edit: and those replicas are present on said host

I think that's what makes sense too. I was just thinking of showing custom groups in host menu because it doesn't really need `docker swarm init` to work. It would just show similar to how compose stacks are shown.

**Comment by skyscooby** [comment]
This issue is fixed in the master branch, closing! I'll open another Feature issue for the continued convo here.
