### ISSUE TITLE
Optional coloring support

### ISSUE THREAD

**Issue by victordidenko** [amir20/dozzle#37]
Hello! First of all, thanks for the tool!
Looks like it doesn't understand colors. Can you add optional support for ANSI escape codes?
<img width="609" alt="Screenshot 2019-06-13 at 12 12 22" src="https://user-images.githubusercontent.com/15016227/59419937-a3ab3380-8dd4-11e9-9b55-9799c3fba135.png">

**Comment by amir20** [comment]
Glad you like it. 

I looked at some option to support ANSI colors. There doesn't seem to be a good way to support ANSI colors in HTML. I found [this little module](https://github.com/rburns/ansi-to-html#readme) that might do the trick. I have yet to give it try because not everybody needed it. I also use loggers where enable/disable [colors based](https://github.com/sirupsen/logrus#formatters) on TTY support. So I don't have a good way to test. 

Could you give me a simple docker image to test this and I can see if `ansi-to-html` would work. You can also send me a PR and we can work on it together.

**Comment by amir20** [comment]
Well, it looks like it works better than I thought!

<img width="1772" alt="Screen Shot 2019-06-13 at 9 14 37 AM" src="https://user-images.githubusercontent.com/260667/59449443-e90f3700-8dbb-11e9-9895-33957ceecfd0.png">

I am going to create a build now and have you try it.

**Comment by amir20** [comment]
@victordidenko try `1.11.0`. It should have colors now. I'll test it more when I get home. I am curious if there is any performance implications.

**Comment by victordidenko** [comment]
Sorry for delay, I didn't have time to answer to your first message :)

I was going to suggest you to run smth like this
```
docker run --rm -d ubuntu bash -c "apt update && apt install -y colortest && while true; do colortest-16; sleep 10; done"
```
but now I have already tested it myself :)

Thank you, everything is working!

**Comment by amir20** [comment]
Great. It works for me too. It also explains why I was seeing random characters. haha. Good call to get this to work.
