### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by vitalik** [amir20/dozzle#502]
Is there a way to set custom datetime format (like yyyy-mm-dd hh:mm:ss) ?

and also would be nice to set timezone shift (and even better take timezone from browser)

**Comment by amir20** [comment]
@vitalik 

> Is there a way to set custom datetime format (like yyyy-mm-dd hh:mm:ss) ?

No this is not possible right now. But I am not sure why you would need since it is currently being format with `date-fns`. PRs are welcomed if you think it can be improved. 

> and also would be nice to set timezone shift (and even better take timezone from browser)

That is the current behavior using [formatRelative](https://date-fns.org/v2.0.0-alpha.18/docs/formatRelative). AFAIK, it does exactly what you want already because it defaults to `defaultLocale`.

**Comment by vitalik** [comment]
yes seems timzones are covered..
but format seems only American (AM/PM)...

**Comment by amir20** [comment]
Oh I see what you mean. I don't think `formatRelative` has an option to different formats. The options is documented [here.](https://date-fns.org/v2.0.0-alpha.18/docs/Options) I don't see anything relevant to formatting AM/PM.

**Comment by amir20** [comment]
Possibly related https://github.com/date-fns/date-fns/issues/1129. The suggestion solution is an overkill IMO.

**Comment by amir20** [comment]
This is fixed now with time formatting.
