### ISSUE TITLE
Support for custom themes

### ISSUE THREAD

**Issue by 726a67** [amir20/dozzle#508]
**Describe the solution you'd like**
I would love to see dynamic support for user-defined themes so that certain web elements (e.g. icon, title, fonts, fore/background colors, etc.) can be customized at runtime. A definable 'html/css' folder would probably do the trick, but there may be more efficient implementations to consider.

**Comment by amir20** [comment]
I have thought about this a while back when someone else mentioned they wanted to be able to customize the colors. I did some investigation back then and realized it will be very hard to do this. Currently the HTML, CSS and JS are embedded in the Go binary. Customizing it would mean the binary would need to read from multiple places. 

To be honest, not many people have asked for this feature and I think the value it adds is not worth the effort. 

Why do you want custom themes? Is the current theme not good? 

I rather improve the product for all people instead of providing customization for less popular features.

**Comment by 726a67** [comment]
The current theme isn’t bad at all :)

My media server runs a variety of dockerized web applications and I use custom html/css to somewhat ‘standardize’ the disparate UIs across applications.

If it’s a lot of work to implement, don’t worry about it. No worries.

**Comment by amir20** [comment]
OK. If you are just trying to cutomize random pages, have you thought of using something like [Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en)?
