### ISSUE TITLE
see only stderr

### ISSUE THREAD

**Issue by rafipiccolo** [amir20/dozzle#511]
**Is your feature request related to a problem? Please describe.**
stdout + stderr is sometimes a lot, or usually very useless.

**Describe the solution you'd like**
i would like to see only stderr from each containers

**Describe alternatives you've considered**
Create a container reading all logs from other containers and discarding stdout while echoing stderr.

**Additional context**
if i could see only errors i could

**Comment by amir20** [comment]
Some logging framework default to stdout and others to stderr. I have no way of knowing which one to use. If I ignore stdout then a bunch of other users will be asking for stdout only. 

So I only see two options: 

1. Create a toggle (or cli flag) to disable stoud
2. Have the application filter `info` like level logs in stdout. 

Given that no one has asked for this feature and I think it would make sense to keep Dozzle simple and have application developers tailor their logging for their own needs. 

But I could be convinced otherwise, if capturing stdout shouldn't be default.  

FWIW, that's how papertrail and loggly work. They capture ALL logs. See https://12factor.net/logs

**Comment by amir20** [comment]
No response. Closing.

**Comment by danshilm** [comment]
I'd be interested in having such an option. 
A filter would be the best imho since some users might want to only view stderr for certain containers only.
