### ISSUE TITLE
Container stats

### ISSUE THREAD

**Issue by Albinzr** [amir20/dozzle#622]
Is is possible to add container stats to the UI at least cpu and ram usage?

**Comment by amir20** [comment]
I had wanted to do this for a while. But never got around because I kept Dozzle focused on only logging. 

Not too many people have asked for this feature. Let's keep the ticket open and I can gauge if others have interest too. 

Thanks for the idea!

**Comment by Albinzr** [comment]
Cool

**Comment by rafipiccolo** [comment]
from what i see in docker api we need to call 1 endpoint for each container to get stats. This is what "docker stats" does

if we poll all containers, then we can show the names in red on the sidebar if >90% cpu.

we could also poll stats from only the current displayed container and display a topbar over the logs ?
=> would be cool but not so useful for me

I feel like a dedicated project would be better.
a clone of dozzle but showing cpu + ram + net + io curves

cadvisor does some of this, but it is very ugly in both UX and functionalities

do you know other standalone projects that does that ?

**Comment by amir20** [comment]
I was thinking of only showing the CPU usage for the current container. 

But that is an interesting idea to change colors based on usage 🤔 One could quickly click to the red containers hoping to investigate why they are red. 

I hadn't done anything because I feel like a dedicated project would be better. When I use Dozzle, I am trying to debug. I already know what I want to look at. Having CPU / Mem doesn't solve that anymore. 

Maybe if more people upvote then I can investigate more. I wish there was a way to put a poll or feature request in Github. 😅

**Comment by Albinzr** [comment]
@amir20  The main reason I thought having  CPU / Mem here was I really wanted to know how an error or any other issue in sever code effect cup and memory same time Im looking at the live logs, This will help in better optimizing the code.

**Comment by amir20** [comment]
I added a WIP PR https://github.com/amir20/dozzle/pull/671. I was able to get the stats live from Docker. Works pretty well. There are some complication as Windows and Unix are handled differently. 

Now the harder part is to show it in the UI. I was thinking of adding in the header. But suggestions are welcomed. 

The left nav is already pretty crowded so I like the idea of just changing color.

**Comment by amir20** [comment]
@Albinzr and @rafipiccolo I have something in the works that looks actually pretty good. Thanks for the suggestions so far. I even found memory leaks in my code because I was looking at memory usage in Dozzle. 

I have pushed a test release `amir20/dozzle:stats` that should show this new feature in action. 

I am still not too sure about the UI but most of the backend work is done. Eventually, I can also turn menu items different colors. 

Can you please try installing `amir20/dozzle:stats` and provide feedback?

**Comment by rafipiccolo** [comment]
Hello,

- [x]  stats display on top. 

- [ ] I haven't tested the red since I have no load right now.

Dozzle seems to have low stat usage.

Great job

Will you add NET and DISK IO as the api provide them in the same call ? Can be useful for debugging too.

Can you reduce the header size by removing the container name ? I may not be the best in UX :)

Thanks

**Comment by amir20** [comment]
> I haven't tested the red since I have no load right now

That's not implemented yet so no worries. 

> Dozzle seems to have low stat usage

Dozzle has always been low. Golang has been pretty nice to work with. 

> Will you add NET and DISK IO as the api provide them in the same call ? Can be useful for debugging too.

I'll follow up with some of these. I am trying to get to a good point where I can release first. 

> Can you reduce the header size by removing the container name ? I may not be the best in UX :)

I thought about doing that. But the header plays an important role when multiple containers are pinned. It used to be hidden when only one container was displayed, but now I am always showing it so that it is consistent with thew stats. 

Mobile still needs work.

**Comment by amir20** [comment]
`amir20/dozzle:latest-dev` now has the latest patches in master.

**Comment by amir20** [comment]
If all looks good, I can release Tuesday.

**Comment by amir20** [comment]
<img width="1906" alt="Screen Shot 2020-09-07 at 1 58 39 PM" src="https://user-images.githubusercontent.com/260667/92416425-45bde680-f112-11ea-9eda-1f8ab42895a2.png">

v3 released. Some minor bugs coming. Overall looks good to me.
