### ISSUE TITLE
Viewing remote dozzle hosts

### ISSUE THREAD

**Issue by SAOPP** [amir20/dozzle#688]
Hi!

Thanks for Dozzle! Amazing and clear tool. 

I realize this probably doesn't look like an easy addition. But I will suggest it anyway - it would be great if we could view logs from remote hosts where the dozzle copy is located also. By analogy with the same portainer agent, this is just an example.

The message is: _"Have one main Dozzle instance and view all logs in one place through it."_ :1st_place_medal: 

Thanks in advance!

**Comment by amir20** [comment]
I have thought about this in the past. Ultimately, I'd like to support Docker Swarm so that it can handle `services`. 

The idea of `agent` create a lot of other dependencies that are just too complicated. Dozzle would need to be able to register itself which would require some kind of key-value storage like etcd. Right now alternative options to Dozzle are datadog, loggly, etc... All these require installing agents per node. That's too heavy IMO for Dozzle. 

For now, Dozzle supports `DOCKER_HOST` env var, so you could change env var and restart. I agree this not the most user friendly way of switching hosts. 

I think if Dozzle was to be a full enterprise logging solution then I'd agree that creating agents would be a nice to have. But for now, I am trying to keep it simple. 

If you want to work on this as a feature request then I am not opposed to it. You would just have to support Dozzle simple use cases in addition to agents.

**Comment by SAOPP** [comment]
@amir20 hi, I'm back with the question, don't remember if I see your full edited message... but, 'bout `DOCKER_HOST` as I understood it's a default variable for monitorig only one remote host right? Is it possible to add as many hosts as u would like in 1 instance? :) For example 1 local and 10 remote in one container without any remote agents as I asked before like. :)

**Comment by SAOPP** [comment]
...just has switching hosts in dozzle gui for log view

**Comment by amir20** [comment]
Hi there @SAOPP. No update on this. I don't plan to add this functionality as I don't have time these days. One of the reasons Dozzle has done so well is simplicity and focused on just debugging. I hope to keep it small.

**Comment by SAOPP** [comment]
Hi, yes I agree with u at all! I support this position 100%.

But for example, for a home laboratory, when there are several hosts, you have to keep ten dozzle instances somewhere on the bastion - so that you can open the logs from almost one place. It would be great if Dozzle could handle a lot of `DOCKER_HOST` variables - but obviously it just isn't possible.

**Comment by amir20** [comment]
It is now possible to set up remote hosts. See https://github.com/amir20/dozzle/#connecting-to-remote-hosts and https://github.com/amir20/dozzle/pull/2059
