### ISSUE TITLE
Authentication feature

### ISSUE THREAD

**Issue by theanht1** [amir20/dozzle#727]
Hi there,
Thanks for your awesome tool, it's really helpful for my personal projects.
In order to secure access to Dozzle, I think we should have an option to restrict access to the app, something like a token flag is good enough. I could help with this feature.

**Comment by amir20** [comment]
Hello,

I haven't added authentication because that can be handled by reverse proxy. I want Dozzle to be simple and things like authentication, proxy or IP whitelisting are too complex to be part of Dozzle.

However, I could be convinced otherwise. Can you think of any good reasons why auth should be support out of the box? I am running [traefik](https://traefik.io/traefik/) in front of Dozzle and it handles all of this. 

There is a [section in the README](https://github.com/amir20/dozzle#security) file about this too.

**Comment by amir20** [comment]
Closing this ticket because there has been no response. We can reopen if needed.

**Comment by theanht1** [comment]
@amir20 I tend to use Dozzle for personal projects because of its light-weight and simplicity, so I don't like to have another layer on top of it just for security. In the other hand, a basic or token authentication won't make it more complicated and still good enough for access limitation
